### PR TITLE
Fix LoopbackClient issues

### LINKED ISSUE #6449: [msal-node] LoopbackClient listen should not crash with unhandled rejection
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.18.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Trying to integrate the MSAL `PublicClientApplication` in the `acquireTokenInteractive` method.  This calls into the `LoopbackClient` for the `listenForAuthCode` method.  This method should set up an HTTP server and listen for when the server is actually listening.  The code should acquire a server and handle listening gracefully.  However, this crashes with an unhandled Promise rejection exception.

### Error Message

```
[node-tests] AuthError [NodeAuthError]: loopback_server_timeout: Timed out waiting for auth code listener to be registered.
[node-tests]     at new AuthError (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-common@13.3.0/node_modules/@azure/msal-common/src/error/AuthError.ts:49:9)
[node-tests]     at new NodeAuthError (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-node@1.18.3/node_modules/@azure/msal-node/src/error/NodeAuthError.ts:44:9)
[node-tests]     at Function.createLoopbackServerTimeoutError (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-node@1.18.3/node_modules/@azure/msal-node/src/error/NodeAuthError.ts:92:16)
[node-tests]     at Timeout._onTimeout (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-node@1.18.3/node_modules/@azure/msal-node/src/network/LoopbackClient.ts:54:41)
[node-tests]     at listOnTimeout (node:internal/timers:569:17)
[node-tests]     at processTimers (node:internal/timers:512:7) {
[node-tests]   errorCode: 'loopback_server_timeout',
[node-tests]   errorMessage: 'Timed out waiting for auth code listener to be registered.',
[node-tests]   subError: ''
[node-tests] }
```

### Msal Logs

_No response_

### MSAL Configuration

```javascript
{
    auth: {
      clientId: "some-client-id",
      authority: "https://login.microsoftonline.com/common",
    },
}
```

### Relevant Code Snippets

```javascript
This is the code that is causing the issue:


        await new Promise<void>((resolve) => {
            let ticks = 0;
            const id = setInterval(() => {
                if (
                    LOOPBACK_SERVER_CONSTANTS.TIMEOUT_MS /
                        LOOPBACK_SERVER_CONSTANTS.INTERVAL_MS <
                    ticks
                ) {
                    throw NodeAuthError.createLoopbackServerTimeoutError();
                }

                if (this.server.listening) {
                    clearInterval(id);
                    resolve();
                }
                ticks++;
            }, LOOPBACK_SERVER_CONSTANTS.INTERVAL_MS);
        });
```

The code should be calling the listen method with a callback for the listener instead such as:

```
this.server.listen(0, (event) => {
  // Do something with listening to the server
});
```
```


### Reproduction Steps

This test should run without crashing the test-server

  it("Throws an expected error if no browser is available", async function (this: Context) {
    // The SinonStub type does not include this second parameter to throws().
    const testErrorMessage = "No browsers available on this test.";
    (sandbox.stub(interactiveBrowserMockable, "open") as any).throws(
      "BrowserConfigurationAuthError",
      testErrorMessage
    );

    const credential = new InteractiveBrowserCredential(
      recorder.configureClientOptions({
        redirectUri: "http://localhost:8081",
        tenantId: env.AZURE_TENANT_ID,
        clientId: env.AZURE_CLIENT_ID,
      })
    );

    let error: Error | undefined;
    try {
      await credential.getToken(scope);
    } catch (e: any) {
      error = e;
    }

    assert.equal(error?.name, "BrowserConfigurationAuthError");
    assert.equal(error?.message, "No browsers available on this test.");
  });

### Expected Behavior

This should not crash with the following:

```
[node-tests] AuthError [NodeAuthError]: loopback_server_timeout: Timed out waiting for auth code listener to be registered.
[node-tests]     at new AuthError (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-common@13.3.0/node_modules/@azure/msal-common/src/error/AuthError.ts:49:9)
[node-tests]     at new NodeAuthError (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-node@1.18.3/node_modules/@azure/msal-node/src/error/NodeAuthError.ts:44:9)
[node-tests]     at Function.createLoopbackServerTimeoutError (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-node@1.18.3/node_modules/@azure/msal-node/src/error/NodeAuthError.ts:92:16)
[node-tests]     at Timeout._onTimeout (/Users/matthewp/git/azure-sdk-for-js/common/temp/node_modules/.pnpm/@azure+msal-node@1.18.3/node_modules/@azure/msal-node/src/network/LoopbackClient.ts:54:41)
[node-tests]     at listOnTimeout (node:internal/timers:569:17)
[node-tests]     at processTimers (node:internal/timers:512:7) {
[node-tests]   errorCode: 'loopback_server_timeout',
[node-tests]   errorMessage: 'Timed out waiting for auth code listener to be registered.',
[node-tests]   subError: ''
[node-tests] }
```

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

_No response_

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by tnorling**
This PR fixes 2 bugs in the LoopbackClient:

1. If the server doesn't spin up immediately, getting the redirectUri will fail. Addressed by moving the setInterval out of the `listenForAuthCode` function and instead wrapping the `getRedirectUri` with it
1. If the listener throws before the promise is awaited the rejection becomes unhandled. Addressed by attaching the catch handler on promise creation and storing the error for later.

### CODE REVIEW

File: lib/msal-node/src/client/PublicClientApplication.ts [hunk 1]
```diff
@@ -187,9 +199,12 @@ export class PublicClientApplication
 
             const authCodeUrl = await this.getAuthCodeUrl(validRequest);
             await openBrowser(authCodeUrl);
-            const authCodeResponse = await authCodeListener.finally(() => {
+            await authCodeListener.finally(() => {
```
Comment (xirzec) [inline lib/msal-node/src/client/PublicClientApplication.ts]: if you change the try/catch to a try/finally you can avoid needing to call `closeServer` in two places.

**Review by xirzec — COMMENTED** [review]
A clever way around changing the contract!

Would you also mind addressing the problem of `server.close()` being asynchronous? (That is to say, it doesn't actually close the server down if there are any open or idle connections.)

File: lib/msal-node/src/client/PublicClientApplication.ts (hunk 1 above)
Comment (tnorling) [reply lib/msal-node/src/client/PublicClientApplication.ts]: Done. Thanks for the suggestion!

File: lib/msal-node/src/network/LoopbackClient.ts [hunk 2]
```diff
@@ -119,8 +94,17 @@ export class LoopbackClient implements ILoopbackClient {
...
-        if (!!this.server) {
+        if (this.server) {
+            // Only stops accepting new connections, server will close once open/idle connections are closed.
             this.server.close();
+
+            if (typeof this.server.closeAllConnections === "function") {
+                /*
+                 * Close open/idle connections. This API is available in Node versions 18.2 and higher
+                 */
+                this.server.closeAllConnections();
```
Comment (xirzec) [inline lib/msal-node/src/network/LoopbackClient.ts:105]: if you wanted to handle it below 18.2 you could listen for "connection" events to get a reference to the socket connections, though perhaps that is more bookkeeping than you want to do. Another way to resolve this trouble is you can call `unref` on the server object to prevent it from keeping the Node runtime alive, I think that might be sufficient for our purposes.

```suggestion
                this.server.closeAllConnections();
                this.server.unref();
```

**Review by xirzec — APPROVED** [review]
Changes look good! Thank you for the fix.

After this is merged, can we backport it to the 1.x branch?

File: lib/msal-node/src/network/LoopbackClient.ts (hunk 2 above)
Comment (xirzec) [reply lib/msal-node/src/network/LoopbackClient.ts:105]: whoops, the suggestion should be calling unref outside of this if block for downlevel runtimes to benefit, but you get the idea :)

**Review by peterzenz — APPROVED** [review]

**Review by sameerag — APPROVED** [review]
