### PR TITLE
MSAL Guard should properly support hash routing and non-root base urls

### LINKED ISSUE #1447: MsalGuard constructs incorrect redirectStartPage when HashLocationStrategy is used
## Library
- [X] `@azure/msal-angular@1.0.0-beta.4`

## Framework
Angular v7.

## Description
PR #1343 introduced the `redirectStartPage` field in `AuthenticationParameters` and the `MsalGuard` started using it in order to preserve the Angular route being hit when redirecting. This was great!

Unfortunately this does not work when an Angular app such as ours uses `HashLocationStrategy` by setting the `useHash` field to `true` in the root router module. For completeness, this is our router module configuration:
```ts
RouterModule.forRoot(
  routes,
  {
    enableTracing: false,
    paramsInheritanceStrategy: 'always',
    useHash: true
  }
)
```

When the `MsalGuard` constructs the `routePath` on [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/06e879cf0b4eb07c6d4408934dceadf08352f296/lib/msal-angular/src/msal-guard.service.ts#L41), the hash is not included.
For example, when the route is meant to be the following:
```
http://localhost:4200/#/path/to/secure/route
```
What actually gets constructed is:
```
http://localhost:4200/path/to/secure/route
```
This is because `window.location.origin` is `http://localhost:4200` and `state.url` is `/path/to/secure/route`. The `/#` in between the two is missing.

I am trying to find out what the best way is to safely construct the full URL to the current route irrespective of whether `PathLocationStrategy` or `HashLocationStrategy` is used in an Angular app. I thought I would post this issue in the meantime in case you already know the answer @jasonnutter.

## Configuration
This issue is not dependent on the MSAL configuration but is instead dependent on setting `useHash` to `true` on the root Angular routing module as above.

## Expected behavior
When using `HashLocationStrategy`, deep-linking to a route protected by the `MsalGuard` should cause the correct `redirectStartPage` to be constructed, with the hash in the URL.

### PR DESCRIPTION
**Pull request by jasonnutter**
This PR addresses the issues raised in #1447: 
- Properly construct the `redirectStartUrl` if hash routing is used.
- Properly construct the `redirectStartUri` if the application uses a different root url than `/`

It also fixes the behavior in `msal` when `redirectStartUri` itself contains a hash. If this occurs, `msal` will process the response hash immediately, then redirect to the `redirectStartUri`. This is to prevent both hash values from being concatenated together, which confuses both msal and the Angular router.

Unfortunately, this may lead to `redirectStartUri` not receiving the `handleRedirectCallback` response (this would happen if `redirectUri` and `redirectStartUri` are not the same base url, e.g. `/redirect` and `/profile#edit`). I wasn't able to find a graceful way to handle this scenario, given the changes that were made in #1358.

Fixes:
- #1447 
- #1422

### CODE REVIEW

**Comment by tnorling** [comment]
Another thing to consider; In the case where a 2nd redirect is needed and a hash routing strategy is used, the 2nd redirect will throw an error due to no ```state``` being present in the hash. This is something we will want to also address in conjunction with #1413 where ```state``` is especially important in determining whether to process the hash at all

**Comment by jasonnutter** [comment]
> Another thing to consider; In the case where a 2nd redirect is needed and a hash routing strategy is used, the 2nd redirect will throw an error due to no state being present in the hash

I don't think that is true here, as we are clearing the response hash, processing it, then navigating to the original url (which has the Angular specific hash values, which won't pass MSAL's checks, which look for known properties in the hash).

**Comment by tnorling** [comment]
> > Another thing to consider; In the case where a 2nd redirect is needed and a hash routing strategy is used, the 2nd redirect will throw an error due to no state being present in the hash
> 
> I don't think that is true here, as we are clearing the response hash, processing it, then navigating to the original url (which has the Angular specific hash values, which won't pass MSAL's checks, which look for known properties in the hash).

I stand corrected. I didn't dig into the ```urlContainsHash``` function and assumed it was just a basic check whether or not the url contains a hash but it is in fact inspecting the hash for known properties. So this should be fine. I take back my original concern

**Review by tnorling — APPROVED** [review]

File: lib/msal-core/src/UserAgentApplication.ts [hunk 1]
```diff
@@ -1067,7 +1067,14 @@ export class UserAgentApplication {
                 window.location.href = "/";
                 return;
             } else if (currentUrl !== loginRequestUrl) {
-                window.location.href = `${loginRequestUrl}${hash}`;
+                // If loginRequestUrl contains a hash (e.g. Angular routing), process the hash now then redirect to prevent both hashes in url
+                if (loginRequestUrl.indexOf("#") > -1) {
+                    this.logger.info("loginRequestUrl contains hash, processing response hash immediately then redirecting");
+                    this.processCallBack(hash, stateInfo, null);
```
Comment (sameerag) [inline lib/msal-core/src/UserAgentApplication.ts:1073]: If there are two hashes does it always imply angular routing?

Comment (jasonnutter) [reply lib/msal-core/src/UserAgentApplication.ts:1073]: No, #1422 describes another scenario with a non-msal hash value.

Comment (jasonnutter) [reply lib/msal-core/src/UserAgentApplication.ts:1073]: @pkanher617 No, that was the problematic behavior that @tnorling fixed.

File: lib/msal-angular/src/msal-guard.service.ts [hunk 2]
```diff
@@ -27,6 +27,28 @@ export class MsalGuard implements CanActivate {
...
     ) {}
 
+    /**
+     * Builds the absolute url for the destination page
+     * @param path Relative path of requested page
+     * @returns Full destination url
+     */
+    getDestinationUrl(path: string): string {
+        // Absolute base url for the application
+        const baseUrl = this.location.normalize(document.getElementsByTagName("base")[0].href);
```
Comment (DarylThayil) [inline lib/msal-angular/src/msal-guard.service.ts:37]: Is this element always available?

**Review by DarylThayil — APPROVED** [review]
asked one question but looks good

File: lib/msal-angular/src/msal-guard.service.ts (hunk 2 above)
Comment (jasonnutter) [reply lib/msal-angular/src/msal-guard.service.ts:37]: The Angular CLI adds it be default, but yeah, there isn't a guarantee. I'll add a default if it isn't there.

Comment (jasonnutter) [reply lib/msal-angular/src/msal-guard.service.ts:37]: So Angular apps must either provide this base element, or provide the base path via the `APP_BASE_HREF` injection token. I'm not sure how to account for the `APP_BASE_HREF`, given if the Guard expects it to be injected, Angular will throw an error if it is not provided. So for now, I'll default to `window.location.origin`, and incrementally handle `APP_BASE_HREF`.
