### PR TITLE
Persist authority in in-memory cache

### LINKED ISSUE #4113: Stuck into "Silent flow client created"
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

^1.3.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Application get randomly stuck into "Silent flow client created" and I cannot access any protected routes

### Error Message

Verbose - Silent flow client created

### Msal Logs

appSettings is configured
[Thu, 30 Sep 2021 09:45:55 GMT] : @azure/msal-node@1.3.1 : Info - getAuthCodeUrl called
[Thu, 30 Sep 2021 09:45:55 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 09:45:55 GMT] : [93841f29-13d6-4c93-a6c3-3b2edf54ae1a] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 09:45:55 GMT] : [93841f29-13d6-4c93-a6c3-3b2edf54ae1a] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 09:45:55 GMT] : [93841f29-13d6-4c93-a6c3-3b2edf54ae1a] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 09:45:55 GMT] : [93841f29-13d6-4c93-a6c3-3b2edf54ae1a] : @azure/msal-node@1.3.1 : Verbose - Auth code client created
[Thu, 30 Sep 2021 09:45:57 GMT] : @azure/msal-node@1.3.1 : Info - acquireTokenByCode called
[Thu, 30 Sep 2021 09:45:57 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 09:45:57 GMT] : [085b37a6-ade6-4345-948a-7edf5ad6747a] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 09:45:57 GMT] : [085b37a6-ade6-4345-948a-7edf5ad6747a] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 09:45:57 GMT] : [085b37a6-ade6-4345-948a-7edf5ad6747a] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 09:45:57 GMT] : [085b37a6-ade6-4345-948a-7edf5ad6747a] : @azure/msal-node@1.3.1 : Verbose - Auth code client created
[Thu, 30 Sep 2021 09:45:57 GMT] : [085b37a6-ade6-4345-948a-7edf5ad6747a] : @azure/msal-common@5.0.0 : Info - in acquireToken call
[Thu, 30 Sep 2021 09:45:58 GMT] : [085b37a6-ade6-4345-948a-7edf5ad6747a] : @azure/msal-common@5.0.0 : Verbose - Persistence enabled, calling beforeCacheAccess
[Thu, 30 Sep 2021 09:45:58 GMT] : [085b37a6-ade6-4345-948a-7edf5ad6747a] : @azure/msal-common@5.0.0 : Verbose - Persistence enabled, calling afterCacheAccess

Response:
: {
  authority: 'https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb/',
  uniqueId: 'f2f25a2c-bfdb-4c50-a115-e9981472607b',
  tenantId: 'fed95e69-8d73-43fe-affb-a7d85ede36fb',
  scopes: [ 'profile', 'openid', 'email', 'User.Read' ],
  account: {},
  idToken: 'id-token',
  idTokenClaims: {},
  accessToken: 'access-token',
  fromCache: false,
  expiresOn: 2021-09-30T10:45:57.000Z,
  correlationId: '085b37a6-ade6-4345-948a-7edf5ad6747a',
  extExpiresOn: 2021-09-30T11:45:56.000Z,
  familyId: '',
  tokenType: 'Bearer',
  state: '',
  cloudGraphHostName: '',
  msGraphHost: ''
}
appSettings is configured
[Thu, 30 Sep 2021 09:45:59 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 09:45:59 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 09:45:59 GMT] : [e6e221b7-2645-4e56-9b2c-200f04de5738] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 09:45:59 GMT] : [e6e221b7-2645-4e56-9b2c-200f04de5738] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 09:45:59 GMT] : [e6e221b7-2645-4e56-9b2c-200f04de5738] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 09:46:00 GMT] : [e6e221b7-2645-4e56-9b2c-200f04de5738] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 09:46:01 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 09:46:01 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 09:46:01 GMT] : [a296bd01-d434-40dd-8900-dcb43c6c3cdf] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 09:46:01 GMT] : [a296bd01-d434-40dd-8900-dcb43c6c3cdf] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 09:46:01 GMT] : [a296bd01-d434-40dd-8900-dcb43c6c3cdf] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 09:46:02 GMT] : [a296bd01-d434-40dd-8900-dcb43c6c3cdf] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
appSettings is configured
[Thu, 30 Sep 2021 10:48:02 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:02 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:02 GMT] : [f6cc9587-d28a-4272-822a-cb4b2e5c5153] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:02 GMT] : [f6cc9587-d28a-4272-822a-cb4b2e5c5153] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:02 GMT] : [f6cc9587-d28a-4272-822a-cb4b2e5c5153] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:03 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:03 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:03 GMT] : [0c387d1f-5fe5-467a-b2e1-c3d40866f1e0] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:03 GMT] : [0c387d1f-5fe5-467a-b2e1-c3d40866f1e0] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:03 GMT] : [0c387d1f-5fe5-467a-b2e1-c3d40866f1e0] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:03 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:03 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:03 GMT] : [1002af07-8782-4dc2-9216-a5656406f169] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:03 GMT] : [1002af07-8782-4dc2-9216-a5656406f169] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:03 GMT] : [1002af07-8782-4dc2-9216-a5656406f169] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:03 GMT] : [f6cc9587-d28a-4272-822a-cb4b2e5c5153] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:03 GMT] : [0c387d1f-5fe5-467a-b2e1-c3d40866f1e0] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:03 GMT] : [1002af07-8782-4dc2-9216-a5656406f169] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:04 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:04 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:04 GMT] : [1cede367-4ed3-4e6b-b8e3-8b4a6fbdb1b8] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:04 GMT] : [1cede367-4ed3-4e6b-b8e3-8b4a6fbdb1b8] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:04 GMT] : [1cede367-4ed3-4e6b-b8e3-8b4a6fbdb1b8] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:04 GMT] : [1cede367-4ed3-4e6b-b8e3-8b4a6fbdb1b8] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:05 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:05 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:05 GMT] : [2a3242b2-5a1d-4350-ab7d-fb951aaeca05] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:05 GMT] : [2a3242b2-5a1d-4350-ab7d-fb951aaeca05] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:05 GMT] : [2a3242b2-5a1d-4350-ab7d-fb951aaeca05] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:05 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:05 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:05 GMT] : [512a0bbb-31c8-47f9-a2cd-b528a750b707] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:05 GMT] : [512a0bbb-31c8-47f9-a2cd-b528a750b707] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:05 GMT] : [512a0bbb-31c8-47f9-a2cd-b528a750b707] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:06 GMT] : [91b5b4e1-f2af-4889-80ce-1cdd8ba7cf37] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:06 GMT] : [91b5b4e1-f2af-4889-80ce-1cdd8ba7cf37] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:06 GMT] : [91b5b4e1-f2af-4889-80ce-1cdd8ba7cf37] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:06 GMT] : [2a3242b2-5a1d-4350-ab7d-fb951aaeca05] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:06 GMT] : [07be509c-ba88-448f-a8e1-661ee06daefa] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:06 GMT] : [07be509c-ba88-448f-a8e1-661ee06daefa] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:06 GMT] : [07be509c-ba88-448f-a8e1-661ee06daefa] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:06 GMT] : [512a0bbb-31c8-47f9-a2cd-b528a750b707] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:06 GMT] : [91b5b4e1-f2af-4889-80ce-1cdd8ba7cf37] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:06 GMT] : [e35529c2-f884-4f94-9782-c015f0e4d84f] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:06 GMT] : [e35529c2-f884-4f94-9782-c015f0e4d84f] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:06 GMT] : [e35529c2-f884-4f94-9782-c015f0e4d84f] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:06 GMT] : [cbab995a-f25a-46c5-b3c5-954360e607fb] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:06 GMT] : [cbab995a-f25a-46c5-b3c5-954360e607fb] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:06 GMT] : [cbab995a-f25a-46c5-b3c5-954360e607fb] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:06 GMT] : [07be509c-ba88-448f-a8e1-661ee06daefa] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:06 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:06 GMT] : [f363da54-50f9-4bad-ac78-0fccffedc00a] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:06 GMT] : [f363da54-50f9-4bad-ac78-0fccffedc00a] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:06 GMT] : [f363da54-50f9-4bad-ac78-0fccffedc00a] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:07 GMT] : [e35529c2-f884-4f94-9782-c015f0e4d84f] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:07 GMT] : [eaaff8e5-fd26-439a-9ed2-494b80d8ecc3] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:07 GMT] : [eaaff8e5-fd26-439a-9ed2-494b80d8ecc3] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:07 GMT] : [eaaff8e5-fd26-439a-9ed2-494b80d8ecc3] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:07 GMT] : [cbab995a-f25a-46c5-b3c5-954360e607fb] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:07 GMT] : [631e0fb3-731d-4b65-91a3-ec1240c46e63] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:07 GMT] : [631e0fb3-731d-4b65-91a3-ec1240c46e63] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:07 GMT] : [631e0fb3-731d-4b65-91a3-ec1240c46e63] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:07 GMT] : [f363da54-50f9-4bad-ac78-0fccffedc00a] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:07 GMT] : [16e45457-455f-438b-9bd0-16d2c2e9e8db] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:07 GMT] : [16e45457-455f-438b-9bd0-16d2c2e9e8db] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:07 GMT] : [16e45457-455f-438b-9bd0-16d2c2e9e8db] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:07 GMT] : [eaaff8e5-fd26-439a-9ed2-494b80d8ecc3] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:07 GMT] : [0ae44637-152c-46d1-9687-7c0ff092137d] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:07 GMT] : [0ae44637-152c-46d1-9687-7c0ff092137d] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:07 GMT] : [0ae44637-152c-46d1-9687-7c0ff092137d] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:07 GMT] : [631e0fb3-731d-4b65-91a3-ec1240c46e63] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:07 GMT] : [16e45457-455f-438b-9bd0-16d2c2e9e8db] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:07 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:07 GMT] : [fedb2b85-7755-45cd-a428-2e716c79aecc] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:07 GMT] : [fedb2b85-7755-45cd-a428-2e716c79aecc] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:07 GMT] : [fedb2b85-7755-45cd-a428-2e716c79aecc] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:08 GMT] : [c3dd1af6-ff77-4b98-8c57-0c17bb54971d] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:08 GMT] : [c3dd1af6-ff77-4b98-8c57-0c17bb54971d] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:08 GMT] : [c3dd1af6-ff77-4b98-8c57-0c17bb54971d] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:08 GMT] : [cc8d27b5-59f3-4b15-b3d9-987988f47899] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:08 GMT] : [cc8d27b5-59f3-4b15-b3d9-987988f47899] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:08 GMT] : [cc8d27b5-59f3-4b15-b3d9-987988f47899] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:08 GMT] : [0ae44637-152c-46d1-9687-7c0ff092137d] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:08 GMT] : [be40191c-255b-44d0-8d81-4cb081dfc282] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:08 GMT] : [be40191c-255b-44d0-8d81-4cb081dfc282] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:08 GMT] : [be40191c-255b-44d0-8d81-4cb081dfc282] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:08 GMT] : [fedb2b85-7755-45cd-a428-2e716c79aecc] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:08 GMT] : [c3dd1af6-ff77-4b98-8c57-0c17bb54971d] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:08 GMT] : [cc8d27b5-59f3-4b15-b3d9-987988f47899] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:08 GMT] : [be40191c-255b-44d0-8d81-4cb081dfc282] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:08 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:08 GMT] : [82ed5411-adae-4e0a-9a33-3928ad211d86] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:08 GMT] : [82ed5411-adae-4e0a-9a33-3928ad211d86] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:08 GMT] : [82ed5411-adae-4e0a-9a33-3928ad211d86] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:09 GMT] : [82ed5411-adae-4e0a-9a33-3928ad211d86] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:11 GMT] : [76c44378-a191-4f54-a8af-c083680412bd] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:11 GMT] : [76c44378-a191-4f54-a8af-c083680412bd] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:11 GMT] : [76c44378-a191-4f54-a8af-c083680412bd] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:11 GMT] : [7e0ad79a-e060-49db-91d8-942b024a3e62] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:11 GMT] : [7e0ad79a-e060-49db-91d8-942b024a3e62] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:11 GMT] : [7e0ad79a-e060-49db-91d8-942b024a3e62] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:11 GMT] : [3ae30799-9d28-441b-b9bc-5089df68e300] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:11 GMT] : [3ae30799-9d28-441b-b9bc-5089df68e300] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:11 GMT] : [3ae30799-9d28-441b-b9bc-5089df68e300] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:11 GMT] : [76c44378-a191-4f54-a8af-c083680412bd] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:11 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:11 GMT] : [3b2926ef-449a-47c7-933b-8812d95b74cc] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:11 GMT] : [3b2926ef-449a-47c7-933b-8812d95b74cc] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:11 GMT] : [3b2926ef-449a-47c7-933b-8812d95b74cc] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:11 GMT] : [7e0ad79a-e060-49db-91d8-942b024a3e62] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:12 GMT] : [b2c299dd-d5aa-47ae-b33a-35714f7080c0] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:12 GMT] : [b2c299dd-d5aa-47ae-b33a-35714f7080c0] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:12 GMT] : [b2c299dd-d5aa-47ae-b33a-35714f7080c0] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:12 GMT] : [3ae30799-9d28-441b-b9bc-5089df68e300] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:12 GMT] : [3b2926ef-449a-47c7-933b-8812d95b74cc] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:12 GMT] : [0a32b264-6501-4e40-babe-dda50cfd04ca] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:12 GMT] : [0a32b264-6501-4e40-babe-dda50cfd04ca] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:12 GMT] : [0a32b264-6501-4e40-babe-dda50cfd04ca] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:12 GMT] : [b2c299dd-d5aa-47ae-b33a-35714f7080c0] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:12 GMT] : [7d4e375c-5648-4175-b6aa-b7049a99c971] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:12 GMT] : [7d4e375c-5648-4175-b6aa-b7049a99c971] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:12 GMT] : [7d4e375c-5648-4175-b6aa-b7049a99c971] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:12 GMT] : [3df2f0f8-5322-407b-8fa0-c4db9e71807d] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:12 GMT] : [3df2f0f8-5322-407b-8fa0-c4db9e71807d] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:12 GMT] : [3df2f0f8-5322-407b-8fa0-c4db9e71807d] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:12 GMT] : [0a32b264-6501-4e40-babe-dda50cfd04ca] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:12 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:12 GMT] : [62d00b3b-aeca-4f65-843c-9a01d57a25ae] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:12 GMT] : [62d00b3b-aeca-4f65-843c-9a01d57a25ae] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:12 GMT] : [62d00b3b-aeca-4f65-843c-9a01d57a25ae] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:13 GMT] : [7d4e375c-5648-4175-b6aa-b7049a99c971] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:13 GMT] : [4ac400f8-5c41-45f3-bc7a-ac10059de7d8] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:13 GMT] : [4ac400f8-5c41-45f3-bc7a-ac10059de7d8] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:13 GMT] : [4ac400f8-5c41-45f3-bc7a-ac10059de7d8] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:13 GMT] : [3df2f0f8-5322-407b-8fa0-c4db9e71807d] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:13 GMT] : [4c0de672-535f-49a0-bb34-a1797193d745] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:13 GMT] : [4c0de672-535f-49a0-bb34-a1797193d745] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:13 GMT] : [4c0de672-535f-49a0-bb34-a1797193d745] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:13 GMT] : [62d00b3b-aeca-4f65-843c-9a01d57a25ae] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:13 GMT] : [4ac400f8-5c41-45f3-bc7a-ac10059de7d8] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:13 GMT] : [4c0de672-535f-49a0-bb34-a1797193d745] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:13 GMT] : [ddd82c47-52e6-42ab-9a4b-24b49d01c263] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:13 GMT] : [ddd82c47-52e6-42ab-9a4b-24b49d01c263] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:13 GMT] : [ddd82c47-52e6-42ab-9a4b-24b49d01c263] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:13 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:13 GMT] : [0841dffa-15b7-49b0-b365-106836417da7] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:13 GMT] : [0841dffa-15b7-49b0-b365-106836417da7] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:13 GMT] : [0841dffa-15b7-49b0-b365-106836417da7] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:14 GMT] : [ddd82c47-52e6-42ab-9a4b-24b49d01c263] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:14 GMT] : [0841dffa-15b7-49b0-b365-106836417da7] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:14 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:14 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:14 GMT] : [941ee8f3-e5f2-43a7-a6fa-b7fdcda74868] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:14 GMT] : [941ee8f3-e5f2-43a7-a6fa-b7fdcda74868] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:14 GMT] : [941ee8f3-e5f2-43a7-a6fa-b7fdcda74868] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:14 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:14 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:14 GMT] : [f120e1d6-42cf-4266-abed-3a8a830c5cb9] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:14 GMT] : [f120e1d6-42cf-4266-abed-3a8a830c5cb9] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:14 GMT] : [f120e1d6-42cf-4266-abed-3a8a830c5cb9] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:14 GMT] : [941ee8f3-e5f2-43a7-a6fa-b7fdcda74868] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:14 GMT] : @azure/msal-node@1.3.1 : Info - getTokenCache called
[Thu, 30 Sep 2021 10:48:14 GMT] : @azure/msal-node@1.3.1 : Verbose - initializeRequestScopes called
[Thu, 30 Sep 2021 10:48:14 GMT] : [6fc1ea55-0270-4d5b-85ac-3143d618d8cc] : @azure/msal-node@1.3.1 : Verbose - buildOauthClientConfiguration called
[Thu, 30 Sep 2021 10:48:14 GMT] : [6fc1ea55-0270-4d5b-85ac-3143d618d8cc] : @azure/msal-node@1.3.1 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/fed95e69-8d73-43fe-affb-a7d85ede36fb 
[Thu, 30 Sep 2021 10:48:14 GMT] : [6fc1ea55-0270-4d5b-85ac-3143d618d8cc] : @azure/msal-node@1.3.1 : Verbose - createAuthority called
[Thu, 30 Sep 2021 10:48:14 GMT] : [f120e1d6-42cf-4266-abed-3a8a830c5cb9] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created
[Thu, 30 Sep 2021 10:48:15 GMT] : [6fc1ea55-0270-4d5b-85ac-3143d618d8cc] : @azure/msal-node@1.3.1 : Verbose - Silent flow client created

### MSAL Configuration

```javascript
const appSettings = () => {

    // BASE_URI = `YOUR-APP-NAME`
    const domainName = process.env.BASE_URI || "localhost";
    
    let port, baseUri;
    
    // local development only
    if (domainName === 'localhost') {
        port = process.env.PORT || 8080;
        baseUri = `http://${domainName}:${port}`;
        console.log(`local development only baseUri = ${baseUri}`)
    } else {
        // deployed to Azure
        port = 8080;
        baseUri = `https://${domainName}.azurewebsites.net`;
        console.log(`deploy to Azure baseUri = ${baseUri}`)
    }
    
    
    
    const app_settings_vals = {
        "host": {
            "port": port,
            "baseUri": baseUri,
            "domainName": domainName,
            "ver":"0.0.1"
        },
        "credentials": {
            "clientId": process.env.AD_CLIENT_ID || "476d9437-71a1-44f0-8a97-64cb2422efb1",
            "tenantId": process.env.AD_TENANT_ID || "fed95e69-8d73-43fe-affb-a7d85ede36fb",
            "clientSecret": process.env.AD_CLIENT_ID_SECRET || "e~6wlL0e1z-.9Udp.Twb.wY16dNI8Bh3iv"
        },
        "settings": {
            "homePageRoute": "/home",
            "redirectUri": `${baseUri}/redirect`,
            "postLogoutRedirectUri": `${baseUri}/`
        },
        "resources": {
            "graphAPI": {
                "callingPageRoute": "/profile",
                "endpoint": "https://graph.microsoft.com/v1.0/me",
                "scopes": ["user.read"]
            },
            "reports": {
                "callingPageRoute": "/reports",                
                "scopes": ["user.read"]
            },
            "admin": {
                "callingPageRoute": "/admin",                
                "scopes": ["user.read"]
            },
            "portfolio": {
                "callingPageRoute": "/portfolio",                
                "scopes": ["user.read"]
            },
            "portfoliodue": {
                "callingPageRoute": "/portfoliodue",                
                "scopes": ["user.read"]
            },
            "welcomecall": {
                "callingPageRoute": "/welcomecall",                
                "scopes": ["user.read"]
            },
            "groupAnnex": {
                "callingPageRoute": "/groupannex",                
                "scopes": ["user.read"]
            },
            "portfolioAPI": {
                "callingPageRoute": "/portfolioapi",                
                "scopes": ["user.read"]
            },
            "getPortfolioCron": {
                "callingPageRoute": "/portfoliogetcron",                
                "scopes": ["user.read"]
            },
            "portfolioSetCronAPI": {
                "callingPageRoute": "/portfoliosetcronapi",                
                "scopes": ["user.read"]
            },            
            "getPortfolioSetCron": {
                "callingPageRoute": "/portfoliosetcron",                
                "scopes": ["user.read"]
            },
            "groupannexapi": {
                "callingPageRoute": "/groupannexapi",                
                "scopes": ["user.read"]
            },
            "getGroupAnnexCron": {
                "callingPageRoute": "/groupannexgetcron",                
                "scopes": ["user.read"]
            },
            "getGroupAnnexSetCron": {
                "callingPageRoute": "/groupannexsetcron",                
                "scopes": ["user.read"]
            }, 
            "groupAnnexSetCronAPI": {
                "callingPageRoute": "/groupannexsetcronapi",                
                "scopes": ["user.read"]
            },  
            "groupAnnexUpload": {
                "callingPageRoute": "/groupannexupload",                
                "scopes": ["user.read"]
            }, 
            "groupAnnexUploadAPI": {
                "callingPageRoute": "/groupannexuploadapi",                
                "scopes": ["user.read"]
            }, 
            "deleteBlobAPI": {
                "callingPageRoute": "/deleteblobapi",                
                "scopes": ["user.read"]
            },
            "underconstruction": {
                "callingPageRoute": "/underconstruction",                
                "scopes": ["user.read"]
            },
            "armAPI": {
                "callingPageRoute": "/tenant",
                "endpoint": "https://management.azure.com/tenants?api-version=2020-01-01",
                "scopes": ["https://management.azure.com/user_impersonation"]
            }
        }

    }
    console.log(JSON.stringify(app_settings_vals));
    return app_settings_vals;
}

module.exports = appSettings;
```

### Relevant Code Snippets

```javascript
The router:

const getRoutes = (mainController, authProvider,  router) => {
    // app routes
    router.get('/', (req, res, next) => res.redirect('/home'));
    router.get('/home', mainController.getHomePage);
    router.get('/underconstruction', mainController.getUnderConstruction)
    // authentication routes
    router.get('/signin', authProvider.signIn);
    router.get('/signout', authProvider.signOut);
    router.get('/redirect', authProvider.handleRedirect);
    // secure routes
    router.get('/id', authProvider.isAuthenticated, mainController.getIdPage);
    router.get('/profile', authProvider.isAuthenticated, authProvider.getToken,  mainController.getProfilePage); // get token for this route to call web API
    router.get('/tenant', authProvider.isAuthenticated, authProvider.getToken,  mainController.getTenantPage) // get token for this route to call web API
    router.get('/reports', authProvider.isAuthenticated, authProvider.getToken,  mainController.getReports)
    router.get('/admin', authProvider.isAuthenticated, authProvider.getToken,  mainController.getAdmin)
    router.get('/portfolio', authProvider.isAuthenticated, authProvider.getToken,  mainController.getPortfolioOnDemand)
    router.get('/portfoliodue', authProvider.isAuthenticated, authProvider.getToken,  mainController.getPortfolioOnDue)
    router.get('/welcomecall', authProvider.isAuthenticated, authProvider.getToken,  mainController.getWelcomeCallReport)
    router.get('/groupannex', authProvider.isAuthenticated, authProvider.getToken,  mainController.getGroupAnnexReport)
    router.post('/portfolioapi', authProvider.isAuthenticated, authProvider.getToken,  mainController.postPortfolioAPI)
    router.post('/groupannexapi', authProvider.isAuthenticated, authProvider.getToken,  mainController.postGroupAnnex)
    router.get('/groupannexupload', authProvider.isAuthenticated, authProvider.getToken,  mainController.groupAnnexUpload)
    router.post('/groupannexuploadapi', authProvider.isAuthenticated, authProvider.getToken,  mainController.groupAnnexUploadApi)
    router.delete('/deleteblobapi', authProvider.isAuthenticated, mainController.deleteBlobAPI)
    // secure and authorized
    router.get('/portfoliogetcron', authProvider.isAuthenticated, authProvider.getToken,  mainController.getPortfolioCron)
    router.get('/portfoliosetcron', authProvider.isAuthenticated, authProvider.getToken,  mainController.getPortfolioSetCron)
    router.post('/portfoliosetcronapi', authProvider.isAuthenticated, authProvider.getToken,  mainController.postPortfolioSetCron)

    router.get('/groupannexgetcron', authProvider.isAuthenticated, authProvider.getToken,  mainController.getGroupAnnexCron)
    router.get('/groupannexsetcron', authProvider.isAuthenticated, authProvider.getToken,  mainController.getGroupAnnexSetCron)
    router.post('/groupannexsetcronapi', authProvider.isAuthenticated, authProvider.getToken,  mainController.postGroupAnnexSetCron)
    // 404
    router.get('*', (req, res) => res.status(404).redirect('/404.html'));

    return router;
}

module.exports = getRoutes;
```

The app.js:

```
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

const express = require('express');
const session = require('express-session');
const path = require('path');
const getRoutes = require('./router');
const mainController = require('./controller');
const cache = require('./utils/cachePlugin');
const app = express();
var bodyParser = require('body-parser')
// get settings and set up Authentication into app
const appSettings = require('../appSettings')();
const msalWrapper = require('./msal-express-wrapper/auth-provider');
const authProvider = new msalWrapper.AuthProvider(appSettings, cache);
app.locals = {
    appSettings,
    authProvider
};

// View engine
app.set('views', path.join(__dirname, './views'));
app.set('view engine', 'ejs');

// Static files and other configurations
app.use('/css', express.static(path.join(__dirname, 'node_modules/bootstrap/dist/css')));
app.use('/js', express.static(path.join(__dirname, 'node_modules/bootstrap/dist/js')));
app.use(express.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, './public')));

/**
 * Using express-session middleware. Be sure to familiarize yourself with available options
 * and set the desired options. Visit: https://www.npmjs.com/package/express-session
 */
app.use(session({ secret: '8aced7b0-1f09-4bc9-912b-b949ebf9bff7', resave: false, saveUninitialized: false }));

// set up routes with authentication
app.use(express.text({ type: 'text/html' }));
app.use(getRoutes(mainController, authProvider, express.Router()));

app.listen(appSettings.host.port, () => console.log(`App listening on port ${appSettings.host.port}!`));
```

### Reproduction Steps

1. start the app
2. login
3. try to navigate to a protected route

### Expected Behavior

To be able to navigate to the protected routes

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, None (Server)

### Regression

_No response_

### Source

External (Customer)

### LINKED ISSUE #4276: AuthorityMetadata cache is lost after calling TokenCache.getAccountByHomeId() causing PublicClientApplication.acquireTokenSilent() very slow due to retrieving AuthorityMetadata on every call
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

@azure/msal-node@1.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

## Actual behavior 

```
await publicClientApplication.acquireTokenSilent({
  account: account,
  scopes: scopes,
  forceRefresh: false,
}); // this is slow as expected because it needs to retrieve AuthorityMetdata

// here, publicClientApplication.storage.cache will be filled with 8 entries including "authority-metadata-xxxx"
// It seems that this method call will call beforeCacheAccess() and overwrite data in memory
await publicClientApplication.getTokenCache().getAccountByHomeId(accountCache);

// here, publicClientApplication.storage.cache will be filled with 6 entries without "authority-metadata-xxxx"

publicClientApplication.acquireTokenSilent({
  account: account,
  scopes: scopes,
  forceRefresh: false,
}); // this will be slow because AuthorityMetadata cache is gone
```

## Expected behavior
The second call to `acquireTokenSilent()` will not trigger HTTP request.

And my question is, what should I do to make the second call to `acquireTokenSilent()` hit the cache? I have to call `getAccountByHomeId()` between `acquireTokenSilent()` calls because of bussiness logic.

### Error Message

_No response_

### Msal Logs

_No response_

### MSAL Configuration

```javascript
const config = {
  auth: {
    clientId: "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    authority: "https://login.microsoftonline.com/common",
  },
  system: {
    loggerOptions: {
      // @ts-ignore
      loggerCallback(loglevel, message, containsPii) {
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Error,
    },
  },
  cache: {
    cachePlugin, // this is a simple file based plugin, similar to the sample code
  },
};
```

### Relevant Code Snippets

```javascript
See Description
```

### Reproduction Steps

See Description

### Expected Behavior

See Description

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

_No response_

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by sameerag**
A bug in the spread operator is causing in-memory cache to not retain authority data that is cached. This PR fixes it such that consequent calls to the same authority need not always go to the network for `cloudDiscoveryData` and `authorityMetaData`.

Could not add UT because we mock our cache when we test it. Tested this with the manual sample.

update: Silent flow e2e is failing - will check

### CODE REVIEW

File: lib/msal-node/src/cache/NodeStorage.ts [hunk 1]
```diff
@@ -29,11 +29,19 @@ export class NodeStorage extends CacheManager {
     // Cache configuration, either set by user or default values.
     private logger: Logger;
     private cache: CacheKVStore = {};
+    private inMemoryCache: InMemoryCache;
```
Comment (sadasant) [inline lib/msal-node/src/cache/NodeStorage.ts]: I’m not sure if this makes sense, since right above this, you have a private `cache` 🤔 

I could be wrong, but you already have a `setCache` and `getCache` methods in this file, meaning that there’s already a way to keep track of an “in memory cache” through this class. Is the idea to keep track of _two_ in memory caches?

I believe the utility of the method `cacheToInMemoryCache` was to convert from one type to another, not to commit cache to memory.

Comment (sameerag) [reply lib/msal-node/src/cache/NodeStorage.ts]: `CacheKVStore`: Is the flat cache (Key-Value map)we refer to for all get, set, delete operations.
`InMemoryCache`: A temp data structure representing the serialized JSON cache to `CacheKVStore` format. I agree the name is confusing, can change it as needed.

Comment (sameerag) [reply lib/msal-node/src/cache/NodeStorage.ts]: And yes, you are right though, this should not be a class instance since it will end up retaining old cache instead of reading from the new one. Thanks @tnorling for pointing this out.

Comment (sameerag) [reply lib/msal-node/src/cache/NodeStorage.ts]: Made the changes.

File: lib/msal-node/src/cache/NodeStorage.ts [hunk 2]
```diff
@@ -89,16 +88,20 @@ export class NodeStorage extends CacheManager {
      * @param inMemoryCache - kvstore map for inmemory
      */
     inMemoryCacheToCache(inMemoryCache: InMemoryCache): CacheKVStore {
```
Comment (sadasant) [inline lib/msal-node/src/cache/NodeStorage.ts:91]: I wonder, what’s the use case in which a user passes an “inMemoryCache” into this method?

It seems to me that this method is more about converting the inputs from one type to another. However, internally it’s about merging the inputs with the state of this class into a new value that only gets returned.

Is the idea only to merge these two types?
Or to merge the internal cache with one given on the user input?
Or perhaps the idea is to update the internal cache of this class with the cache passed on the parameters?
Or is it all of the three?

**Review by hectormmg — APPROVED** [review]
LGTM

**Comment by ghost** [comment]
Reminder: The next release is scheduled for next week and this PR appears to be stale :( 

If changes have been requested please address feedback. 
If this PR is still a work in progress please mark as draft.

**Review by tnorling — APPROVED** [review]

File: change/@azure-msal-node-b12936ed-da98-48ac-9b2c-58a23b9e4cb4.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "Persist authority in inmemory cache",
```
Comment (peterzenz) [inline change/@azure-msal-node-b12936ed-da98-48ac-9b2c-58a23b9e4cb4.json]: In Memory, or in-memory or something other than inmemory.

File: lib/msal-node/docs/caching.md [hunk 4]
```diff
@@ -58,6 +58,9 @@ MSAL Node's cache schema is compatible with other MSALs. By default, MSAL's cach
 }
 ```
 
+## Cache in memory
+If a user chooses not to persist cache, the `TokenCache` interface is still available to access the tokens cached in memory. The life time of in memory cache is the same as MSAL instance. If the MSAL instance  restarts, the cache is erased when the process lifecycle finishes. We recommend persisting the cache with encryption for all real life applications both for security and desired cache longevity.
```
Comment (peterzenz) [inline lib/msal-node/docs/caching.md:62]: in memory is good.

**Review by peterzenz — APPROVED** [review]
Just some nits.

File: change/@azure-msal-node-b12936ed-da98-48ac-9b2c-58a23b9e4cb4.json (hunk 3 above)
Comment (tnorling) [inline change/@azure-msal-node-b12936ed-da98-48ac-9b2c-58a23b9e4cb4.json]:
```suggestion
  "comment": "Persist authority in in memory cache #4081",
```
