### PR TITLE
[msal-common][msal-browser] Fix issue where config was being overwritten by undefined values

### LINKED ISSUE #1623: Caching problems with acquireTokenSilent()
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

Vanilla JavaScript

## Description

It seem that after upgrading from `msal-browser@2.0.0-beta.0` to `msal-browser@2.0.0-beta.1`, caching is not working properly anymore.

Every time I call `await msalApp.acquireTokenSilent(request)`, both the metadata and token requests are made against Azure AD endpoints. This was NOT happening with `beta.0`.

## Security

No

## Regression

This was NOT happening with `msal-browser@2.0.0-beta.0`.

## Configuration

```js
{
  msal: {
    auth: {
      clientId: "<client_id>",
      authority: "https://login.microsoftonline.com/<tenant_id>/",
      redirectUri: location.origin,
      postLogoutRedirectUri: location.origin,
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false,
    }
  }
}
```

## Reproduction steps

See the Description section.

## Expected behavior

Calling `await msalApp.acquireTokenSilent(request)` shouldn't go to Azure AD endpoints every time.

## Browsers

Can be reproduced, at least, in Chrome and Firefox.

### PR DESCRIPTION
**Pull request by pkanher617**
This PR fixes an issue where the default system configuration in `msal-common` was being overwritten by the undefined values in `msal-browser`. This PR adds the default system values to `msal-common` exports and uses them in the `msal-browser` package.

This should fix #1623.

### CODE REVIEW

File: lib/msal-common/src/client/SPAClient.ts [hunk 1]
```diff
@@ -213,7 +213,13 @@ export class SPAClient extends BaseClient {
             // Get current cached tokens
             const cachedTokenItem = this.getCachedTokens(requestScopes, acquireTokenAuthority.canonicalAuthority, request.resource, account && account.homeAccountIdentifier);
             const expirationSec = Number(cachedTokenItem.value.expiresOnSec);
+            console.log(TimeUtils.nowSeconds());
```
Comment (tnorling) [inline lib/msal-common/src/client/SPAClient.ts:216]: Can we remove all these console.log statements?

Comment (pkanher617) [reply lib/msal-common/src/client/SPAClient.ts]: done
