### PR TITLE
Persist active account

### LINKED ISSUE #3075: Setting active account doesn't persist between page loads
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description

From the Angular B2C example

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/df55fda194a733a861c5ad08f12e5b2a3ff2108f/samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/home/home.component.ts#L24-L26

I am using the redirect way of authentication (instead of pop up), the above line should set the account after authentication. But instead, this doesn't happen.

I confirmed it with - `console.log(this.authService.instance.getActiveAccount());` - this shows null. But `console.log(this.authService.instance.getAllAccounts());` - does print all the accounts.

## Error Message

No error messages

## MSAL Configuration

```js
export const b2cPolicies = {
  names: {
    signUpSignIn: 'B2C_1_SignUpSignInFlow',
    forgotPassword: 'B2C_1_PasswordReset',
    editProfile: 'B2C_1_ProfileEditing'
  },
  authorities: {
    signUpSignIn: {
      authority: 'https://gollahalliauth.b2clogin.com/gollahalliauth.onmicrosoft.com/B2C_1_SignUpSignInFlow',
    },
    forgotPassword: {
      authority: 'https://gollahalliauth.b2clogin.com/gollahalliauth.onmicrosoft.com/B2C_1_PasswordReset',
    },
    editProfile: {
      authority: 'https://gollahalliauth.b2clogin.com/gollahalliauth.onmicrosoft.com/B2C_1_ProfileEditing'
    }
  },
  authorityDomain: 'gollahalliauth.b2clogin.com'
};
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

### PR DESCRIPTION
**Pull request by tnorling**
Updates `getActiveAccount` and `setActiveAccount` APIs to use window storage to persist across page loads.

### CODE REVIEW

**Comment by jasonnutter** [comment]
I don't see how this would be a breaking change, as any apps that rely on it not being persisted would just call `setActiveAccount` each page load (which wouldn't be needed anymore in theory), which should still work.

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 1]
```diff
@@ -377,6 +377,61 @@ export class BrowserCacheManager extends CacheManager {
...
+        const activeAccountId = this.browserStorage.getItem(activeAccountIdKey);
+        return this.getAccountInfoByFilter({localAccountId: activeAccountId || ""})[0] || null;
+    }
+
+    /**
+     * Sets the active account's localAccountId in cache
+     * @param account 
+     */
+    setActiveAccount(account: AccountInfo | null): void {
+        const activeAccountIdKey = this.generateCacheKey("active-account");
```
Comment (jasonnutter) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:394]: Is there an enum or constants file we can define this key?

File: lib/msal-angular/docs/FAQ.md [hunk 2]
```diff
@@ -97,8 +97,6 @@ We recommend setting the active account:
 - After any action that may change the account, especially if your app uses multiple accounts. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app/src/app/home/home.component.ts#L23) for an example of setting the account after a successful login.
 - On initial page load. Wait until all interactions are complete (by subscribing to the `inProgress$` observable and filtering for `InteractionStatus.None`), check if there is an active account, and if there is none, set the active account. This could be the first account retrieved by `getAllAccounts()`, or other account selection logic required by your app. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app) for an example of checking and setting the active account on page load.
 
-**Note:** Currently, active accounts are for each page load and do not persist. While this is an enhancement we are looking to make, we recommend that you set the active account for each page load.
```
[the remark this answers is not in the document]
Comment (tnorling) [reply lib/msal-angular/docs/FAQ.md:100]: Done

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 1 above)
Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Done

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 3]
```diff
@@ -377,6 +377,61 @@ export class BrowserCacheManager extends CacheManager {
...
+        const activeAccountIdKey = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
+        const activeAccountId = this.browserStorage.getItem(activeAccountIdKey);
+        return this.getAccountInfoByFilter({localAccountId: activeAccountId || ""})[0] || null;
+    }
+
+    /**
+     * Sets the active account's localAccountId in cache
+     * @param account 
+     */
+    setActiveAccount(account: AccountInfo | null): void {
```
Comment (sameerag) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:393]: So we call `setActiveAccount()` to remove an existing account too?

File: lib/msal-common/src/utils/Constants.ts [hunk 4]
```diff
@@ -74,7 +74,8 @@ export enum PersistentCacheKeys {
     CLIENT_INFO = "client.info",
     ADAL_ID_TOKEN = "adal.idtoken",
     ERROR = "error",
-    ERROR_DESC = "error.description"
+    ERROR_DESC = "error.description",
+    ACTIVE_ACCOUNT = "active-account"
```
Comment (sameerag) [inline lib/msal-common/src/utils/Constants.ts:78]: nit: Everything else is separated by a `.`, why a `hyphen` for this name?

File: samples/msal-angular-v2-samples/angular10-sample-app/test/home.spec.ts [hunk 5]
```diff
@@ -47,6 +47,7 @@ describe('/ (Home Page)', () => {
     beforeEach(async () => {
         context = await browser.createIncognitoBrowserContext();
         page = await context.newPage();
+        page.setDefaultTimeout(5000);
```
Comment (sameerag) [inline samples/msal-angular-v2-samples/angular10-sample-app/test/home.spec.ts:50]: Does it throw if we timeout?

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 3 above)
Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:393]: Yes, just from the "active" state. The account itself will remain in the cache.

File: samples/msal-angular-v2-samples/angular10-sample-app/test/home.spec.ts (hunk 5 above)
Comment (tnorling) [reply samples/msal-angular-v2-samples/angular10-sample-app/test/home.spec.ts:50]: This only sets the timeout value. But any navigation operations done on the page object will throw if they don't complete in 5 seconds. In some places this error is caught, but this is to prevent "stuck" navigations that will hold up the test for 30 seconds and cause the test to fail due to test timeout.

File: lib/msal-common/src/utils/Constants.ts (hunk 4 above)
Comment (tnorling) [reply lib/msal-common/src/utils/Constants.ts:78]: Other cache entries use hyphen; `server-telemetry` for instance. I believe the `.` is legacy for migration from v1

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 3 above)
Comment (sameerag) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:393]: Thanks

File: lib/msal-common/src/utils/Constants.ts (hunk 4 above)
Comment (sameerag) [reply lib/msal-common/src/utils/Constants.ts:78]: Okay

File: samples/msal-angular-v2-samples/angular10-sample-app/test/home.spec.ts (hunk 5 above)
Comment (sameerag) [reply samples/msal-angular-v2-samples/angular10-sample-app/test/home.spec.ts:50]: Got it. Thanks.

**Review by sameerag — APPROVED** [review]

**Review by jasonnutter — APPROVED** [review]

**Comment by svrooij** [comment]
Thanks @tnorling this feature is working great for us. Didn't had to change anything (update from 2.14.1)
