### PR TITLE
msal-node serializes/deserializes userAssertionHash

### LINKED ISSUE #5397: MSAL Node does not serialize/desiralize userAssertionHash in OBO
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Confidential

### Description

At the moment msal-node `Serializer` and `Deserializer` classes do not process `userAssertionHash` property in `AccessTokenEntity`. This means when cache is persisted via a cachePlugin, msal-node will not be able to read `userAssertionHash` from the serialized cache entry. Since `userAssertionHash` is a filter property for retrieving a cached AT in OBO flow, this causes the client object's `getCachedAuthenticationResult` method to return null when in memory cache is empty (e.g. server restarts etc.)

### Error Message

N/A

### Msal Logs

[Wed, 16 Nov 2022 20:19:53 GMT] : @azure/msal-node@1.14.3 : Info - getTokenCache called
[Wed, 16 Nov 2022 20:19:51 GMT] : @azure/msal-node@1.14.3 : Info - acquireTokenOnBehalfOf called
[Wed, 16 Nov 2022 20:19:51 GMT] : @azure/msal-node@1.14.3 : Verbose - initializeRequestScopes called
[Wed, 16 Nov 2022 20:19:51 GMT] : [a325b97b-eb28-49de-ae45-bd0d141b7c57] : @azure/msal-node@1.14.3 : Verbose - buildOauthClientConfiguration called
[Wed, 16 Nov 2022 20:19:51 GMT] : [a325b97b-eb28-49de-ae45-bd0d141b7c57] : @azure/msal-node@1.14.3 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/cbaf2168-de14-4c72-9d88-f5f05366dbef
[Wed, 16 Nov 2022 20:19:51 GMT] : [a325b97b-eb28-49de-ae45-bd0d141b7c57] : @azure/msal-node@1.14.3 : Verbose - createAuthority called
[Wed, 16 Nov 2022 20:19:52 GMT] : [a325b97b-eb28-49de-ae45-bd0d141b7c57] : @azure/msal-node@1.14.3 : Verbose - On behalf of client created
[Wed, 16 Nov 2022 20:19:52 GMT] : [a325b97b-eb28-49de-ae45-bd0d141b7c57] : @azure/msal-common@8.0.0 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
[Wed, 16 Nov 2022 20:19:53 GMT] : [a325b97b-eb28-49de-ae45-bd0d141b7c57] : @azure/msal-common@8.0.0 : Verbose - Persistence enabled, calling beforeCacheAccess
[Wed, 16 Nov 2022 20:19:53 GMT] : [a325b97b-eb28-49de-ae45-bd0d141b7c57] : @azure/msal-common@8.0.0 : Verbose - Persistence enabled, calling afterCacheAccess
[Wed, 16 Nov 2022 20:19:53 GMT] : @azure/msal-node@1.14.3 : Info - getTokenCache called

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "***************",
        authority: "https://login.microsoftonline.com/***************",
        clientSecret: "***************",
    },
    cache: {
        cachePlugin: require('./cachePlugin')('./cache.json')
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Verbose,
        }
    }
}
```

### Relevant Code Snippets

```javascript
const app = express();
const cca = new msal.ConfidentialClientApplication(config);

app.get('/obo', validateJwt, async (req, res, next) => {
    const oboAssertion = req.headers.authorization.split(' ')[1];

    try {
        const cache = cca.getTokenCache();
        const accounts = await cache.getAllAccounts();

        const oboRequest = {
            oboAssertion: oboAssertion,
            scopes: ["user.read"],
        };

        const response = await cca.acquireTokenOnBehalfOf(oboRequest);
        console.log(response);
    } catch(error) {
        next(error)
    }
});

app.listen(SERVER_PORT, () => console.log(`Msal Node Web API listening on port ${SERVER_PORT}!`))
```

### Reproduction Steps

1. Follow the steps in [msal node OBO sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/on-behalf-of) to make an OBO call.
2. Configure MSAL in each app to use a [cachePlugin](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/cachePlugin.js)
3. Restart the web API server, retry the OBO call.

### Expected Behavior

MSAL Node `acquireTokenOnBehalfOf` API successfully retrieves the cached AT from disk.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

_No response_

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by derisen**
In response to #5397 

p.s. will update the [obo sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/on-behalf-of) separately for manual testing. will also check if MSIDLabs support OBO flow for E2E testing.

### CODE REVIEW

File: lib/msal-node/src/cache/serializer/Serializer.ts [hunk 1]
```diff
@@ -84,7 +84,8 @@ export class Serializer {
                 key_id: atEntity.keyId,
                 token_type: atEntity.tokenType,
                 requestedClaims: atEntity.requestedClaims,
-                requestedClaimsHash: atEntity.requestedClaimsHash
+                requestedClaimsHash: atEntity.requestedClaimsHash,
+                userAssertionHash: atEntity.userAssertionHash
```
Comment (derisen) [inline lib/msal-node/src/cache/serializer/Serializer.ts:88]: Wasn't sure to follow camel or snake casing here (not sure why we switched). This method could possibly use a refactoring to not require manual mapping from `AccessTokenEntity` to `SerializedAccessTokenEntity`

**Review by bgavrilMS — APPROVED** [review]

**Comment by bgavrilMS** [comment]
LGTM

**Review by Robbie-Microsoft — APPROVED** [review]
