### PR TITLE
Include original request params on /token request in acquireTokenInteractive

### LINKED ISSUE #5390: acquireTokenInteractive Ignores Scopes when Requesting Access Token
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

When using `PublicClientApplication.getTokenInteractive`, only the default OIDC scopes are granted for the access token.
This is despite all the requested scopes being granted. 

This can be seen here where `request.scopes` is not accessed at all.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/42e1baf2c53b980b509678bf011d9cdaa469f9fc/lib/msal-node/src/client/PublicClientApplication.ts#L121-L127

As stated in <https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-client_secret>, the `scope` parameter should hold the desired scopes.

When testing using `@microsoft/microsoft-graph-client`, a simple request to `/me` fails since the `User.Read` scope is not granted.

### Error Message

There's no error message specifically, but the log in the First Code Sample below gives
```
Granted Scopes: [ 'openid', 'profile' ]
```

Error with `@microsoft/microsoft-graph-client` Test (Second Code Sample Below):
```
https://graph.microsoft.com/v1.0/me
(node:10584) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:61
                super(message || (baseError && baseError.message));
  ^
GraphError: Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.
    at new GraphError (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:61:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:76:18)
    at Function.<anonymous> (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:102:31)
    at step (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\node_modules\tslib\tslib.js:144:27)
    at Object.next (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\node_modules\tslib\tslib.js:125:57)
    at C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\node_modules\tslib\tslib.js:114:16)
    at Function.GraphErrorHandler.getError (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:85:24)
    at GraphRequest.<anonymous> (C:\Users\Redfire\silicon\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:391:55) {
  statusCode: 403,
  code: 'ErrorInsufficientPermissionsInAccessToken',
  requestId: 'cea8f798-7cfc-4456-9b2c-6aff7bd5367f',
  date: 2022-11-12T02:38:45.000Z,
  body: `{"code":"ErrorInsufficientPermissionsInAccessToken","message":"Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.","innerError":{"date":"2022-11-12T10:38:45","request-id":"cea8f798-7cfc-4456-9b2c-6aff7bd5367f","client-request-id":"0d1f7a1a-befd-aad2-708f-df3c0f98e948"}}`
}
```

### Msal Logs

```
[Sat, 12 Nov 2022 10:33:02 GMT] : @azure/msal-node@1.14.3 : Info - getTokenCache called
[Sat, 12 Nov 2022 10:33:02 GMT] : @azure/msal-node@1.14.3 : Info - getAuthCodeUrl called
[Sat, 12 Nov 2022 10:33:02 GMT] : @azure/msal-node@1.14.3 : Verbose - initializeRequestScopes called
[Sat, 12 Nov 2022 10:33:02 GMT] : [a2edfb47-ce31-4f91-9ba9-fc2920bde922] : @azure/msal-node@1.14.3 : Verbose - buildOauthClientConfiguration called
[Sat, 12 Nov 2022 10:33:02 GMT] : [a2edfb47-ce31-4f91-9ba9-fc2920bde922] : @azure/msal-node@1.14.3 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/consumers
[Sat, 12 Nov 2022 10:33:02 GMT] : [a2edfb47-ce31-4f91-9ba9-fc2920bde922] : @azure/msal-node@1.14.3 : Verbose - createAuthority called
[Sat, 12 Nov 2022 10:33:03 GMT] : [a2edfb47-ce31-4f91-9ba9-fc2920bde922] : @azure/msal-node@1.14.3 : Verbose - Auth code client created
[Sat, 12 Nov 2022 10:33:30 GMT] : @azure/msal-node@1.14.3 : Info - acquireTokenByCode called
[Sat, 12 Nov 2022 10:33:30 GMT] : @azure/msal-node@1.14.3 : Verbose - initializeRequestScopes called
[Sat, 12 Nov 2022 10:33:30 GMT] : [13813f63-fac3-414d-853f-435f84a754d5] : @azure/msal-node@1.14.3 : Verbose - buildOauthClientConfiguration called
[Sat, 12 Nov 2022 10:33:30 GMT] : [13813f63-fac3-414d-853f-435f84a754d5] : @azure/msal-node@1.14.3 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/consumers
[Sat, 12 Nov 2022 10:33:30 GMT] : [13813f63-fac3-414d-853f-435f84a754d5] : @azure/msal-node@1.14.3 : Verbose - createAuthority called
[Sat, 12 Nov 2022 10:33:30 GMT] : [13813f63-fac3-414d-853f-435f84a754d5] : @azure/msal-node@1.14.3 : Verbose - Auth code client created
[Sat, 12 Nov 2022 10:33:30 GMT] : [13813f63-fac3-414d-853f-435f84a754d5] : @azure/msal-common@8.0.0 : Info - in acquireToken call
```

### MSAL Configuration

```ts
const pcaOptions: Configuration = {
	auth: {
		clientId: process.env.MICROSOFT_CLIENT_ID,
		authority: "https://login.microsoftonline.com/consumers",
	},
	system: {
		loggerOptions: {
			loggerCallback: (_1, message, _2) => console.info(message),
			piiLoggingEnabled: true,
				logLevel: msal.LogLevel.Trace,
		}
	}
};
```

### Relevant Code Snippets

```ts
const scopes = ["User.Read", "Files.Read", "offline_access"];
const pca = new msal.PublicClientApplication(pcaOptions);

const interactive: InteractiveRequest = {
    openBrowser: async function (url) {
        await open(url);
    },
    scopes,
};

const credentials = await pca.acquireTokenInteractive(interactive);
console.log("Granted Scopes:", credentials.scopes);
```

```ts
import { Client } from "@microsoft/microsoft-graph-client";

const options: ClientOptions = {
	debugLogging: true,
	authProvider: new CustomAuthenticationProvider(callback => callback(null, accessToken)),
};

const client = Client.initWithMiddleware(options);
await client.api("/me").get();
```

### Reproduction Steps

1. Initialise a Public Client Application
2. Acquire a Token Interactively
3. Log Granted Scopes of the Token

### Expected Behavior

It is expected for the scopes of the granted token to contain all the scopes requested.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

_No response_

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by tnorling**
A bug in `acquireTokenInteractive` resulted in provided `scopes` and other request parameters being ignored on the `/token` request. This PR ensures that the `/token` request parameters match the parameters from the `/authorize` request

Fixes #5390

### CODE REVIEW

File: lib/msal-node/test/utils/TestConstants.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ export const TEST_CONSTANTS = {
     REDIRECT_URI: "http://localhost:8080",
     CLIENT_SECRET: "MOCK_CLIENT_SECRET",
     DEFAULT_GRAPH_SCOPE: ["user.read"],
+    DEFAULT_OIDC_SCOPES: ["openid", "profile", "offline_access"],
```
Comment (derisen) [inline lib/msal-node/test/utils/TestConstants.ts:20]: would it be better to import this from msal-common (`OIDC_DEFAULT_SCOPES`)

**Review by derisen — APPROVED** [review]
LGTM! Curios how this didn't become apparent before -is it because the scopes passed to getAuthCodeUrl() would be consented by the user  and later on acquireTokenSilent calls would succed using the RT.. 😕

**Comment by tnorling** [comment]
> kenSilent calls would succed using the RT

It's a new feature, not sure how much usage it has gotten yet.

**Review by sameerag — APPROVED** [review]
