### PR TITLE
Clear temporary cache items from cookies

### LINKED ISSUE #3007: Getting "BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API." on opening login page in new tab.
## Library

- [x] `@azure/msal-browser@2.11.1`

## Framework

- [x] React

### Repro steps:
- Launch site (The B2C login page appears)
- Close the tab without logging in
- Open the site in new tab 
- The B2C login page doesn't open. Below mentioned error is recorded in Console logs.

The error is thrown at
`await this.msalClient.loginRedirect({ scopes: this.loginScopes });`

### Stack Trace:

index.js:2177 BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
    at BrowserAuthError.AuthError [as constructor] (https://localhost:44307/static/js/bundle.js:1285:24)
    at new BrowserAuthError (https://localhost:44307/static/js/bundle.js:7827:28)
    at Function../node_modules/@azure/msal-browser/dist/index.es.js.BrowserAuthError.createInteractionInProgressError (https://localhost:44307/static/js/bundle.js:7888:16)
    at PublicClientApplication../node_modules/@azure/msal-browser/dist/index.es.js.ClientApplication.preflightInteractiveRequest (https://localhost:44307/static/js/bundle.js:11304:36)
    at PublicClientApplication.<anonymous> (https://localhost:44307/static/js/bundle.js:10674:45)
    at step (https://localhost:44307/static/js/bundle.js:836:23)
    at Object.next (https://localhost:44307/static/js/bundle.js:817:53)
    at https://localhost:44307/static/js/bundle.js:810:71
    at new Promise (<anonymous>)
    at __awaiter (https://localhost:44307/static/js/bundle.js:806:12)
    at PublicClientApplication../node_modules/@azure/msal-browser/dist/index.es.js.ClientApplication.acquireTokenRedirect (https://localhost:44307/static/js/bundle.js:10659:16)
    at PublicClientApplication.<anonymous> (https://localhost:44307/static/js/bundle.js:11566:44)
    at step (https://localhost:44307/static/js/bundle.js:836:23)
    at Object.next (https://localhost:44307/static/js/bundle.js:817:53)
    at https://localhost:44307/static/js/bundle.js:810:71
    at new Promise (<anonymous>)
    at __awaiter (https://localhost:44307/static/js/bundle.js:806:12)
    at PublicClientApplication../node_modules/@azure/msal-browser/dist/index.es.js.PublicClientApplication.loginRedirect (https://localhost:44307/static/js/bundle.js:11563:16)
    at Auth._callee$ (https://localhost:44307/static/js/bundle.js:487648:56)
    at tryCatch (https://localhost:44307/static/js/bundle.js:375584:40)
    at Generator.invoke [as _invoke] (https://localhost:44307/static/js/bundle.js:375818:22)
    at Generator.prototype.<computed> [as next] (https://localhost:44307/static/js/bundle.js:375636:21)
    at step (https://localhost:44307/static/js/bundle.js:487436:191)
    at https://localhost:44307/static/js/bundle.js:487436:361

## Expected behavior

The application should redirect to B2C login page.

## Identity Provider

- Azure AD B2C

## Browsers/Environment

Tested and Microsoft Edge and Google Chrome.

## Regression

- [x] Did this behavior work before?
This was working fine in
Version: 2.7.0

### PR DESCRIPTION
**Pull request by pkanher617**
Fixes #3007.

Adds cache clearing to msal-specific cookies during `cleanRequestByInteractionType`.

### CODE REVIEW

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 1]
```diff
@@ -558,6 +558,21 @@ export class BrowserCacheManager extends CacheManager {
         return "";
     }
 
+    clearMsalCookies(): void {
+        const cookiePrefix = `${Constants.CACHE_PREFIX}.${this.clientId}`;
+        const cookieList = document.cookie.split(";");
+        for (let i = 0; i < cookieList.length; i++) {
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:564]: Can we do `cookieList.forEach(cookie => {})` to avoid the Object Injection Sink warning below?

**Comment by jasonnutter** [comment]
Any tests we can add?

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 1 above)
Comment (pkanher617) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Done.

**Comment by pkanher617** [comment]
> Any tests we can add?

Done.

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 2]
```diff
@@ -691,11 +707,13 @@ export class BrowserCacheManager extends CacheManager {
...
-            if (!StringUtils.isEmpty(state) && key.indexOf(state) !== -1) {
-                this.removeItem(key);
-            }
-        });
+        if (!StringUtils.isEmpty(state)) {
+            this.getKeys().forEach(key => {
+                if (key.indexOf(state) !== -1) {
+                    this.removeItem(key);
+                }
+            });
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:715]: Do we need to clear cookies here too?

Comment (pkanher617) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:715]: `removeItem` already takes care of it.

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:715]: Right but isn't this the same problem you're fixing down below? It won't reach `removeItem` if `session/localStorage` is empty

Comment (pkanher617) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:715]: The issue was that `removeItem` wasn't being reached in `clearRequestByInteractionType`, which isn't the case here. Basically we should never be in a state that `session/localStorage` and cookies are out of sync, which is fixed by this PR.

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:715]: Correct me if I'm wrong: if we call `resetRequestCache` or `clearRequestByState` it will not clear the cookies (aside from the specific 7 listed below) unless there is a corresponding `session/localstorage` entry. This PR currently only addresses `clearRequestByInteractionType`

**Review by tnorling — APPROVED** [review]

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 2 above)
Comment (pkanher617) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:715]: resolved offline, added cookie clearing to cleanRequestByState also.

**Review by jo-arroyo — APPROVED** [review]
