### PR TITLE
Fixed incorrect IMDS resource ID query parameter

### LINKED ISSUE #7487: Correct IMDS resource ID query parameter
Specifying an identity by resource ID doesn't work on Azure Container Instances (and maybe some other platforms) because we specify the resource ID with query parameter "mi_res_id". ACI observes only "m**s**i_res_id", which we should prefer anyway because although IMDS observes both parameters, it [documents only msi_res_id](https://github.com/Azure/azure-rest-api-specs/blob/dba6ed1f03bda88ac6884c0a883246446cc72495/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable/2018-10-01/imds.json#L233-L239).

 ### Original issue: 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4911

### PR DESCRIPTION
**Pull request by Robbie-Microsoft**
Fixes #7487

> Specifying an identity by resource ID doesn't work on Azure Container Instances (and maybe some other platforms) because we specify the resource ID with query parameter "mi_res_id". ACI observes only "msi_res_id", which we should prefer anyway because although IMDS observes both parameters, it [documents only msi_res_id](https://github.com/Azure/azure-rest-api-specs/blob/dba6ed1f03bda88ac6884c0a883246446cc72495/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable/2018-10-01/imds.json#L233-L239).

> Original issue:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4911

### CODE REVIEW

File: lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ import {
 export const ManagedIdentityUserAssignedIdQueryParameterNames = {
     MANAGED_IDENTITY_CLIENT_ID: "client_id",
     MANAGED_IDENTITY_OBJECT_ID: "object_id",
-    MANAGED_IDENTITY_RESOURCE_ID: "mi_res_id",
+    MANAGED_IDENTITY_RESOURCE_ID: "msi_res_id",
```
Comment (bgavrilMS) [inline lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts]: The bug states that this change should only be done for IMDS, not for all sources.

**Review by bgavrilMS — CHANGES_REQUESTED** [review]
Only IMDS needs this.

File: lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts (hunk 1 above)
Comment (bgavrilMS) [reply lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts]: Also, pls take the time to improve your tests. The fact that you make a change like this and no test breaks is sign that code coverage can be improved.

Comment (rayluo) [reply lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts]: Isn't this change desirable to [more than just IMDS](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4911#issuecomment-2573920867)?

Comment (bgavrilMS) [reply lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts]: It seems that only IMDS documents this as "msi_res_id" and the rest do not. App service does not. Not sure about the others.

Comment (rayluo) [reply lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts]: Actually, for "the others", only Machine Learning is applicable, and we assume it follows IMDS's "msi_res_id", too.

**Review by neha-bhargava — APPROVED** [review]
Nice test coverage

File: lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts [hunk 2]
```diff
@@ -38,7 +38,8 @@ import {
 export const ManagedIdentityUserAssignedIdQueryParameterNames = {
     MANAGED_IDENTITY_CLIENT_ID: "client_id",
     MANAGED_IDENTITY_OBJECT_ID: "object_id",
-    MANAGED_IDENTITY_RESOURCE_ID: "mi_res_id",
+    MANAGED_IDENTITY_RESOURCE_ID_IMDS: "msi_res_id",
+    MANAGED_IDENTITY_RESOURCE_ID_NON_IMDS: "mi_res_id",
```
Comment (rayluo) [inline lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts:42]: But [my understanding](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4911#issuecomment-2573920867) is that we would like to do it the other way around?

Comment (4gust) [reply lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts:42]: In my testing, only `IMDS` is documented with `msi_res_id`
rest other services uses `mi_res_id`
this is correct

**Review by 4gust — APPROVED** [review]
LGTM!

File: lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts (hunk 2 above)
Comment (rayluo) [reply lib/msal-node/src/client/ManagedIdentitySources/BaseManagedIdentitySource.ts:42]: For the sake of precision, only [IMDS is documented with msi_res_id](https://github.com/Azure/azure-rest-api-specs/blob/dba6ed1f03bda88ac6884c0a883246446cc72495/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable/2018-10-01/imds.json#L233-L239), and only [App Service is documented with mi_res_id](https://learn.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Chttp#rest-endpoint-reference), the rest are undocumented and empirically support both, so that is why their implementation can use either one. But, conceptually it is better to think most undocumented Managed Identities follows IMDS, not App Service (Azure VM (IMDS) was launched earlier than App Service).

In fact, the reason we have this PR in the first place, is because the original issue https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4911 mentioned, "Azure Container Instances (and maybe some other platforms) ... observes only msi_res_id, which we should prefer anyway because although IMDS observes both parameters, it [documents only msi_res_id](https://github.com/Azure/azure-rest-api-specs/blob/dba6ed1f03bda88ac6884c0a883246446cc72495/specification/imds/data-plane/Microsoft.InstanceMetadataService/stable/2018-10-01/imds.json#L233-L239)." So, it is misleading to say `MANAGED_IDENTITY_RESOURCE_ID_NON_IMDS: "mi_res_id"`.
