### PR TITLE
Fix enabling CAE in OBO flow in the ConfidentialClientApplication

### LINKED ISSUE #5486: Claims are not attached to the request body when using acquireTokenOnBehalfOf API
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.5

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.1

### Public or Confidential Client?

Confidential

### Description

When setting the configuration object `clientCapabilities` to CP1 in a `ConfidentialClientApplication` instance using `acquireTokenOnBehalfOf` API, the application is not declared [capable of handling challenges](https://learn.microsoft.com/en-us/azure/active-directory/develop/claims-challenge?tabs=JavaScript#how-to-communicate-client-capabilities-to-azure-ad). The issue is in the [createTokenRequestBody](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/client/OnBehalfOfClient.ts#L234) function, as the `acquireTokenOnBehalfOf` doesn't attach the claims to the request body as other clients do, for example, in the [client credentials](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/client/ClientCredentialClient.ts#L221) flow. Is this intentional in msal-node when using OnBehalfOf flow?

MSAL.NET supports claims challenges when using OnBehalfOf flow, as demonstrated in the following [sample](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/6-AdvancedScenarios/1-call-api-obo).

### Error Message

No error message. We receive an access token without the [xms_cc claim](https://learn.microsoft.com/en-us/azure/active-directory/develop/claims-challenge?tabs=JavaScript#receiving-xms_cc-claim-in-an-access-token)

### Msal Logs

[Fri, 16 Dec 2022 00:22:48 GMT] : @azure/msal-node@1.14.5 : Info - acquireTokenOnBehalfOf called
[Fri, 16 Dec 2022 00:22:49 GMT] : [5526a90b-03a7-4268-a10e-41a15f41b21f] : @azure/msal-common@9.0.1 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given 

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        clientId: config.credentials.clientID,
        authority: `https://${config.metadata.authority}/${config.credentials.tenantID}`,
        clientSecret: config.credentials.clientSecret,
        clientCapabilities: ["CP1"],
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Info,
        },
    },
};
```

### Relevant Code Snippets

```javascript
const msal = require('@azure/msal-node');
const config = require('./authConfig');

const msalConfig = {
    auth: {
        clientId: config.credentials.clientID,
        authority: `https://${config.metadata.authority}/${config.credentials.tenantID}`,
        clientSecret: config.credentials.clientSecret,
        clientCapabilities: ["CP1"],
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Info,
        },
    },
};

// Create msal application object
const cca = new msal.ConfidentialClientApplication(msalConfig);

const getOboToken = async (oboAssertion) => {
    const oboRequest = {
        oboAssertion: oboAssertion,
        scopes: config.resources.downstreamAPI.scopes,
    };

    try {
        const response = await cca.acquireTokenOnBehalfOf(oboRequest);
        return response.accessToken;
    } catch (error) {
        console.log(error);
        return error;
    }
};
```

### Reproduction Steps

1. Initialize a ConfidentialClientApplication instance with the clientCapabilities to cp1 in the configuration object.
2. Acquire a graph access token with acquireTokenOnBehalfOf API.
3. Check if the token includes the required claims

### Expected Behavior

Access token to include [xms_cc claim](https://learn.microsoft.com/en-us/azure/active-directory/develop/claims-challenge?tabs=JavaScript#receiving-xms_cc-claim-in-an-access-token)

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

_No response_

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by salman90**
Fix the [issue ](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5486)of enabling CAE in OBO flow in the Confidential Client Application by attaching the client capabilities claim to the request's body when sending it to the authorization server.

### CODE REVIEW

File: lib/msal-common/src/client/OnBehalfOfClient.ts [hunk 1]
```diff
@@ -267,6 +268,10 @@ export class OnBehalfOfClient extends BaseClient {
             parameterBuilder.addClientAssertionType(clientAssertion.assertionType);
         }
 
+        if (!StringUtils.isEmptyObj(request.claims) || this.config.authOptions.clientCapabilities && this.config.authOptions.clientCapabilities.length > 0) {
```
Comment (bgavrilMS) [inline lib/msal-common/src/client/OnBehalfOfClient.ts]: This is ok, I won't block the PR on this and it'll fix the issue. We aren't making anymore releases this year. 

But @Robbie-Microsoft will need to follow up as there are several problems: 


- The request code is very WET. We duplicate this (and some other param setting) logic across confidential client. This issue is a good opportunity to make it DRY.
- Needs tests
- if claims (but not client capabilities) are set, token cache needs to be bypassed - I logged bug https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5494 for this. This also breaks CAE.

File: change/@azure-msal-common-0ca8815c-4766-49e5-a7ae-8ca348f01e9a.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "add claims to request body in OBO class",
```
Comment (derisen) [inline change/@azure-msal-common-0ca8815c-4766-49e5-a7ae-8ca348f01e9a.json]:
```suggestion
  "comment": "add claims to request body in OBO class #5493",
```

File: change/@azure-msal-node-dc148e9b-28a5-459f-a4be-c45954ba6f5e.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
```
Comment (derisen) [inline change/@azure-msal-node-dc148e9b-28a5-459f-a4be-c45954ba6f5e.json]: I believe tests would be "none" instead of "patch"

File: lib/msal-node/test/config/ClientConfiguration.spec.ts [hunk 4]
```diff
@@ -210,4 +211,61 @@ describe('ClientConfiguration tests', () => {
             )
         );
     });
+
+    test('client capabilities are handled as expected for OBO flow', async () => {
```
Comment (derisen) [inline lib/msal-node/test/config/ClientConfiguration.spec.ts:215]:
```suggestion
    test('client capabilities claim appear in request when configuration declares capabilities', async () => {
```

File: lib/msal-common/test/client/OnBehalfOfClient.spec.ts [hunk 5]
```diff
@@ -123,6 +130,77 @@ describe("OnBehalfOf unit tests", () => {
             sinon.restore();
         });
 
+        it("Adds claims when provided", async () => {
```
Comment (derisen) [inline lib/msal-common/test/client/OnBehalfOfClient.spec.ts:133]:
```suggestion
        it("Adds claims when provided in request", async () => {
```

File: change/@azure-msal-node-dc148e9b-28a5-459f-a4be-c45954ba6f5e.json [hunk 6]
```diff
@@ -0,0 +1,7 @@
...
+  "comment": "add tests for obo and clientConfig",
```
Comment (derisen) [inline change/@azure-msal-node-dc148e9b-28a5-459f-a4be-c45954ba6f5e.json]:
```suggestion
  "comment": "add tests for obo and clientConfig #5493",
```

File: lib/msal-common/src/client/OnBehalfOfClient.ts (hunk 1 above)
Comment (salman90) [reply lib/msal-common/src/client/OnBehalfOfClient.ts]: @bgavrilMS I added tests to ensure that the claims are in the request body on the token acquisition and when configuring the `clientCapabilities`, but for other items happy to close this if another PR takes precedence.

Comment (bgavrilMS) [reply lib/msal-common/src/client/OnBehalfOfClient.ts]: This is great, thanks @salman90

**Review by bgavrilMS — APPROVED** [review]

File: lib/msal-common/src/client/OnBehalfOfClient.ts (hunk 1 above)
Comment (tnorling) [inline lib/msal-common/src/client/OnBehalfOfClient.ts]:
```suggestion
        if (request.claims || (this.config.authOptions.clientCapabilities && this.config.authOptions.clientCapabilities.length > 0)) {
```

**Review by derisen — APPROVED** [review]
LGTM!
