### PR TITLE
Fix logger undefined

### LINKED ISSUE #4412: TypeError: Cannot read properties of undefined (reading 'loggerCallback')
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

The application breaks if `loggerOptions` is set to `undefined` explicitly.

### Error Message

```plaintext
TypeError: Cannot read properties of undefined (reading 'loggerCallback')
```

Minified vendor chunk (error reference)

```javascript
...
function y(m, v, E) {
  this.level = o.Info,
  this.localCallback = m.loggerCallback || function() {}, // <-- this line, according to types the variable m can be undefined
  this.piiLoggingEnabled = m.piiLoggingEnabled || !1,
  this.level = "number" == typeof m.logLevel ? m.logLevel : o.Info,
  this.correlationId = m.correlationId || "",
  this.packageName = v || s.gT.EMPTY_STRING,
  this.packageVersion = E || s.gT.EMPTY_STRING
}
...
```

### Msal Logs

_No response_

### MSAL Configuration

```typescript
const msalInstanceFactory = (environment?: IWebClientEnvironment): IPublicClientApplication => {
  return new PublicClientApplication({
    auth: {
      clientId: environment?.msal.clientId ?? 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
      authority: environment?.msal.authority ?? 'https://login.microsoftonline.com/common',
      redirectUri: environment?.msal.redirectUri ?? 'http://localhost:4200',
      postLogoutRedirectUri: '/',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      tokenRenewalOffsetSeconds: 300,
      loggerOptions:
        environment?.production === true
          ? void 0 // <-- This breaks the application
          : {
              loggerCallback,
              logLevel: LogLevel.Info,
              piiLoggingEnabled: false,
            },
    },
  });
};
```

### Relevant Code Snippets

Borwser system options type declaration in the library
```typescript
export declare type BrowserSystemOptions = SystemOptions & {
    loggerOptions?: LoggerOptions; // <-- seems like it can be undefined
    networkClient?: INetworkModule;
    navigationClient?: INavigationClient;
    windowHashTimeout?: number;
    iframeHashTimeout?: number;
    loadFrameTimeout?: number;
    navigateFrameWait?: number;
    redirectNavigationTimeout?: number;
    asyncPopups?: boolean;
    allowRedirectInIframe?: boolean;
};
```

Msal instance factory with loggerOptions set to undefined for the production environment
```typescript
const msalInstanceFactory = (environment?: IWebClientEnvironment): IPublicClientApplication => {
  return new PublicClientApplication({
    auth: {
      clientId: environment?.msal.clientId ?? 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
      authority: environment?.msal.authority ?? 'https://login.microsoftonline.com/common',
      redirectUri: environment?.msal.redirectUri ?? 'http://localhost:4200',
      postLogoutRedirectUri: '/',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      tokenRenewalOffsetSeconds: 300,
      loggerOptions:
        environment?.production === true
          ? void 0 // <-- This breaks the application
          : {
              loggerCallback,
              logLevel: LogLevel.Info,
              piiLoggingEnabled: false,
            },
    },
  });
};
```

### Reproduction Steps

1. configure application to use msal-angular;
2. set system.loggerOptions to `undefined` in the configuration explicitly;
3. start the application locally;
4. open a browser and the browser devtools (console);
5. load the application url;
6. the error should be there;

### Expected Behavior

According to existing types shipped with the library, nothing should be broken when `loggerOptions` is set to undefined.

Seems like either types shipped with the library should be fixed, or there should be explicit checks in the library code like

```typescript
if (typeof system.loggerOptions !== 'undefined') {
  // do something
}
```

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, and possibly all other browsers, but I have tested only in Chrome.

I am sorry, I don't have bandwidth to test in all available browsers.

### Regression

_No response_

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by bmahall**
Fixes #4412 

When loggerOptions is explicitly set to undefined/void 0, it leads to "Cannot read options of undefined" error which breaks the application. This PR makes loggerOptions optional to address this. 

Tests included for msal-browser and msal-node.
Covers: msal-browser,msal-angular,msal-node samples.

### CODE REVIEW

File: lib/msal-common/src/logger/Logger.ts [hunk 1]
```diff
@@ -62,10 +62,16 @@ export class Logger {
         const defaultLoggerCallback = () => {
             return;
         };
-        this.localCallback = loggerOptions.loggerCallback || defaultLoggerCallback;
-        this.piiLoggingEnabled = loggerOptions.piiLoggingEnabled || false;
-        this.level = typeof(loggerOptions.logLevel) === "number" ? loggerOptions.logLevel : LogLevel.Info;
-        this.correlationId = loggerOptions.correlationId || Constants.EMPTY_STRING;
+        const defaultLoggerOptions = {};
+        if(!loggerOptions)
```
Comment (bmahall) [inline lib/msal-common/src/logger/Logger.ts]: this is added for coherence with defaultLoggerCallback, can be removed based on the feedback as it doesnt impact the working/tests.

File: change/msal-6c65b933-30cb-4cc9-b6ae-4b890ca4b848.json [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "none",
+  "comment": "fix logger undefined error",
+  "packageName": "msal",
```
Comment (tnorling) [inline change/msal-6c65b933-30cb-4cc9-b6ae-4b890ca4b848.json]: Please remove as it doesn't appear any v1 changes were made

File: lib/msal-browser/src/interaction_client/StandardInteractionClient.ts [hunk 3]
```diff
@@ -152,9 +152,9 @@ export abstract class StandardInteractionClient extends BaseInteractionClient {
                 preventCorsPreflight: true
             },
             loggerOptions: {
-                loggerCallback: this.config.system.loggerOptions.loggerCallback,
-                piiLoggingEnabled: this.config.system.loggerOptions.piiLoggingEnabled,
-                logLevel: this.config.system.loggerOptions.logLevel,
+                loggerCallback: this.config.system?.loggerOptions?.loggerCallback,
```
Comment (tnorling) [inline lib/msal-browser/src/interaction_client/StandardInteractionClient.ts]: These should all be defined by this point in the flow (with defaults assigned if no logger was provided by the developer), so these '?' should not be needed

File: lib/msal-common/src/logger/Logger.ts (hunk 1 above)
Comment (tnorling) [reply lib/msal-common/src/logger/Logger.ts]: Logger options is a required parameter so this should never be hit

**Review by peterzenz — APPROVED** [review]

File: lib/msal-common/src/logger/Logger.ts [hunk 4]
```diff
@@ -62,10 +62,16 @@ export class Logger {
...
+        {
+        // eslint-disable-next-line no-param-reassign
```
Comment (tnorling) [inline lib/msal-common/src/logger/Logger.ts]: This lint rule is important, please refactor rather than ignoring

File: lib/msal-common/src/logger/Logger.ts [hunk 5]
```diff
@@ -62,10 +62,16 @@ export class Logger {
...
+            loggerOptions= defaultLoggerOptions;
+        }
+        this.localCallback = loggerOptions?.loggerCallback || defaultLoggerCallback;
```
Comment (tnorling) [inline lib/msal-common/src/logger/Logger.ts]: Logger options should be defined by now, '?' should not be needed

File: lib/msal-common/test/logger/Logger.spec.ts [hunk 6]
```diff
@@ -187,6 +187,18 @@ describe("Logger.ts Class Unit Tests", () => {
             expect(logStore[LogLevel.Verbose]).toBe(undefined);
             expect(logStore[LogLevel.Trace]).toBe(undefined);
         });
+
+        it("Doesn't throw if loggerOptions explicitly set to undefined", () => {
+            //@ts-ignore
+            loggerOptions=void 0 || undefined || null;
```
Comment (tnorling) [inline lib/msal-common/test/logger/Logger.spec.ts]: This will always evaluate to `null`, is the intent here to test `undefined`?

**Review by tnorling — CHANGES_REQUESTED** [review]

File: lib/msal-common/test/logger/Logger.spec.ts (hunk 6 above)
Comment (bmahall) [reply lib/msal-common/test/logger/Logger.spec.ts]: thanks, will update

File: lib/msal-common/src/logger/Logger.ts (hunk 5 above)
Comment (bmahall) [reply lib/msal-common/src/logger/Logger.ts]: When the user is setting the logger options in this way:-
{
loggerOptions:
           void 0
}
the sample throws the undefined error, its not using defaultCallback. Hence , had to make these as optional.

Comment (bmahall) [reply lib/msal-common/src/logger/Logger.ts]: In conjunction with L69, it need not be defined , got you. 
Do you prefer using defaultLoggerOptions or using '?' approach here?

Comment (tnorling) [reply lib/msal-common/src/logger/Logger.ts]: void 0 is not an accepted type therefore it's expected that this would fail

Comment (tnorling) [reply lib/msal-common/src/logger/Logger.ts]: By the time the Logger is initialized we should have a defined logger options object that can be passed in (whether it is user provided or defaults) but that logic lives further up the stack (in msal-browser/node) which is why it is a required parameter here

File: lib/msal-common/src/logger/Logger.ts (hunk 4 above)
Comment (bmahall) [reply lib/msal-common/src/logger/Logger.ts]: Have refactored to use a default setter method

File: lib/msal-browser/src/interaction_client/StandardInteractionClient.ts (hunk 3 above)
Comment (bmahall) [reply lib/msal-browser/src/interaction_client/StandardInteractionClient.ts]: have refactored and removed '?' , this PR is to cover when loggerOptions explicitly set to undefined/ void 0 to prevent breaking. when no logger is provided, I agree this is not needed at all.

File: lib/msal-common/test/logger/Logger.spec.ts (hunk 6 above)
Comment (bmahall) [reply lib/msal-common/test/logger/Logger.spec.ts]: updated to use undefined options only, thanks for pointing this out! :)

**Review by sameerag — APPROVED** [review]

File: lib/msal-browser/src/interaction_client/StandardInteractionClient.ts [hunk 7]
```diff
@@ -171,6 +172,16 @@ export abstract class StandardInteractionClient extends BaseInteractionClient {
         };
     }
 
+    private static createDefaultLoggerOptions(): LoggerOptions {
```
Comment (tnorling) [inline lib/msal-browser/src/interaction_client/StandardInteractionClient.ts]: This should be done in `Configuration.ts` instead

File: lib/msal-common/src/logger/Logger.ts [hunk 8]
```diff
@@ -62,14 +62,25 @@ export class Logger {
         const defaultLoggerCallback = () => {
             return;
         };
-        this.localCallback = loggerOptions.loggerCallback || defaultLoggerCallback;
-        this.piiLoggingEnabled = loggerOptions.piiLoggingEnabled || false;
-        this.level = typeof(loggerOptions.logLevel) === "number" ? loggerOptions.logLevel : LogLevel.Info;
-        this.correlationId = loggerOptions.correlationId || Constants.EMPTY_STRING;
+        const setLoggerOptions = loggerOptions || Logger.createDefaultLoggerOptions();
```
Comment (tnorling) [inline lib/msal-common/src/logger/Logger.ts:65]: Let's change `LoggerOptions` in the constructor to `Required<LoggerOptions>` and then you don't need to repeat the default logic here

File: lib/msal-node/src/client/ClientApplication.ts [hunk 9]
```diff
@@ -357,11 +357,9 @@ export abstract class ClientApplication {
                 proxyUrl: this.config.system.proxyUrl,
             },
             loggerOptions: {
-                logLevel: this.config.system.loggerOptions.logLevel,
-                loggerCallback: this.config.system.loggerOptions
-                    .loggerCallback,
-                piiLoggingEnabled: this.config.system.loggerOptions
-                    .piiLoggingEnabled,
+                logLevel: this.config.system.loggerOptions?.logLevel || LogLevel.Info,
```
Comment (tnorling) [inline lib/msal-node/src/client/ClientApplication.ts]: Like in browser, do this in `Configuration.ts`

Comment (bmahall) [reply lib/msal-node/src/client/ClientApplication.ts]: @tnorling , This error is occurring due to this bit in the Configuration.ts:-

`    auth,
    cache,
    system,
    telemetry
}: Configuration): NodeConfiguration {
    return {
        auth: { ...DEFAULT_AUTH_OPTIONS, ...auth },
        cache: { ...DEFAULT_CACHE_OPTIONS, ...cache },
        system: { ...DEFAULT_SYSTEM_OPTIONS, ...fixSystem },
        telemetry: { ...DEFAULT_TELEMETRY_OPTIONS, ...telemetry }
    };
}`


Either this can be modified so that app doesnt break, for the sake of simplicity of the code change involved, making a change in the ClientApplication was preferred.

Comment (tnorling) [reply lib/msal-node/src/client/ClientApplication.ts]: Not sure I understand - all top level configuration overrides should be done in `Configuration.ts`. We shouldn't be modifying the configuration anymore after that.

Comment (bmahall) [reply lib/msal-node/src/client/ClientApplication.ts]: Addressed

File: lib/msal-browser/src/interaction_client/StandardInteractionClient.ts (hunk 7 above)
Comment (bmahall) [reply lib/msal-browser/src/interaction_client/StandardInteractionClient.ts]: Addressed

File: lib/msal-browser/src/interaction_client/StandardInteractionClient.ts (hunk 3 above)
Comment (bmahall) [reply lib/msal-browser/src/interaction_client/StandardInteractionClient.ts]: Addressed & resolving

File: lib/msal-common/src/logger/Logger.ts (hunk 8 above)
Comment (bmahall) [reply lib/msal-common/src/logger/Logger.ts:65]: This will entail type changes in ClientApplication.ts for msal-node. @tnorling

File: lib/msal-browser/src/config/Configuration.ts [hunk 10]
```diff
@@ -270,6 +270,11 @@ export function buildConfiguration({ auth: userInputAuth, cache: userInputCache,
         }
     };
 
+    // eslint-disable-next-line @typescript-eslint/no-explicit-any
+    const providedSystemOptions:any = {...userInputSystem};
```
Comment (tnorling) [inline lib/msal-browser/src/config/Configuration.ts:274]:
```suggestion
    const providedSystemOptions: SystemOptions = {...userInputSystem};
```

File: lib/msal-browser/src/config/Configuration.ts [hunk 11]
```diff
@@ -270,6 +270,11 @@ export function buildConfiguration({ auth: userInputAuth, cache: userInputCache,
...
+    if (!providedSystemOptions.loggerOptions) {
+        providedSystemOptions.loggerOptions = DEFAULT_LOGGER_OPTIONS;
+    }
```
Comment (tnorling) [inline lib/msal-browser/src/config/Configuration.ts]:
```suggestion
    const providedSystemOptions: BrowserSystemOptions = {
        ...userInputSystem,
        loggerOptions: userInputSystem.loggerOptions || DEFAULT_LOGGER_OPTIONS
    };
```

File: lib/msal-node/src/config/Configuration.ts [hunk 12]
```diff
@@ -158,10 +158,14 @@ export function buildAppConfiguration({
     telemetry
 }: Configuration): NodeConfiguration {
 
+    const providedSystemOptions = {...system};
+    if (!providedSystemOptions.loggerOptions) {
+        providedSystemOptions.loggerOptions = DEFAULT_LOGGER_OPTIONS;
+    }
```
Comment (tnorling) [inline lib/msal-node/src/config/Configuration.ts]:
```suggestion
    const providedSystemOptions = {
        ...system,
        loggerOptions: system.loggerOptions || DEFAULT_LOGGER_OPTIONS
    };
```

**Review by tnorling — COMMENTED** [review]
Looks good, can you add some tests?

File: lib/msal-browser/src/config/Configuration.ts (hunk 11 above)
Comment (bmahall) [reply lib/msal-browser/src/config/Configuration.ts]: Addressed.

File: lib/msal-node/src/config/Configuration.ts (hunk 12 above)
Comment (bmahall) [reply lib/msal-node/src/config/Configuration.ts]: Addressed.

**Review by tnorling — APPROVED** [review]
