### PR TITLE
Make popup poll interval configurable

### LINKED ISSUE #5091: Login popup doesn't close and displays react app itself
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.5

### Description

Hi, I think I've just found a bug in MSAL.js. I installed the latest version in two different samples for React. When I try to log in, sometimes the popup shows the React Webapp itself and doesn't close.

- The first sample I used was this one: [https://github.com/Azure-Samples/ms-identity-javascript-react-spa](url)
FirstBug
- And the second one was here in this repository: [https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-18-sample](url)
SecondBug

### Error Message

_No response_

### Msal Logs

_No response_

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "my_client_id",
        authority: "https://login.microsoftonline.com/...",
        redirectUri: "http://localhost:3000"
    },
    cache: {
        cacheLocation: "sessionStorage", 
        storeAuthStateInCookie: false
    },
    system: {	
        loggerOptions: {	
            loggerCallback: (level, message, containsPii) => {	
                if (containsPii) {		
                    return;		
                }		
                switch (level) {		
                    case LogLevel.Error:		
                        console.error(message);		
                        return;		
                    case LogLevel.Info:		
                        console.info(message);		
                        return;		
                    case LogLevel.Verbose:		
                        console.debug(message);		
                        return;		
                    case LogLevel.Warning:		
                        console.warn(message);		
                        return;		
                }	
            }	
        }	
    }
}
```

### Relevant Code Snippets

```javascript
There is no relevant code snippet as I have only changed the MSAL configuration.
```

### Reproduction Steps

1. Clone the sample
2. Install the newest version of @azure/msal-browser and @azure/msal-react through npm.
3. Adjust MSAL configuration
4. Run the sample and try to log in several times.

### Expected Behavior

Login popup should close, but it doesn't.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-browser 2.15.0

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by hectormmg**
This PR:
- Makes poll frequency for Popup hash monitoring configurable for MSAL Browser
- Reduces default poll interval to 30ms in order to increase Popup interaction reliability
- Updates configuration docs

### CODE REVIEW

File: lib/msal-browser/src/interaction_handler/SilentHandler.ts [hunk 1]
```diff
@@ -5,17 +5,19 @@
...
-import { DEFAULT_IFRAME_TIMEOUT_MS } from "../config/Configuration";
+import { BrowserSystemOptions, DEFAULT_IFRAME_TIMEOUT_MS } from "../config/Configuration";
 
 export class SilentHandler extends InteractionHandler {
 
     private navigateFrameWait: number;
-    constructor(authCodeModule: AuthorizationCodeClient, storageImpl: BrowserCacheManager, authCodeRequest: CommonAuthorizationCodeRequest, logger: Logger, navigateFrameWait: number) {
+    private pollIntervalMilliseconds: number;
+
+    constructor(authCodeModule: AuthorizationCodeClient, storageImpl: BrowserCacheManager, authCodeRequest: CommonAuthorizationCodeRequest, logger: Logger, systemOptions: Required<Pick<BrowserSystemOptions, "navigateFrameWait" | "pollIntervalMilliseconds">>) {
```
Comment (tnorling) [inline lib/msal-browser/src/interaction_handler/SilentHandler.ts:17]: Make sure this change also gets addressed in 1P

**Review by tnorling — APPROVED** [review]

**Review by jasonnutter — APPROVED** [review]

File: lib/msal-browser/src/interaction_handler/SilentHandler.ts (hunk 1 above)
Comment (hectormmg) [reply lib/msal-browser/src/interaction_handler/SilentHandler.ts:17]: Thanks! Will do!
