### PR TITLE
[msal-core] Fix cached ID Token retrieval for acquireTokenSilent

### LINKED ISSUE #2185: MSAL 1.4.0 was released, and is causing infinite redirection loop
## Library
- [x] `msal@1.4.0` 
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
React

## Description
We noticed an upgrade of msal to the version 1.4.0 today in our dev environment. It was released at the same day (25. Aug. 2020). The login with underlying msal library does not work anymore and is ending in infinite redirection loop to login.microsoft.com. 

More, after short search on this project side I cannot find any migration guide or release note to the released version. Was this version released by accident? Could someone clarify?

For now we changed the version back to the latest 1.3.x and everything works fine.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

### PR DESCRIPTION
**Pull request by hectormmg**
This PR:
- Adds logic to always try to include an ID Token in the `acquireTokenSilent` auth response, regardless of `response_type`
- Adds `getIdToken` method to the `AuthCache` class to support retrieving ID Tokens from the cache
- Adds several utility private methods to UserAgentApplication dedicated to building an appropriate cache auth response based on the response type
- Adds exhaustive testing for the above updates to behavior
- Fixes #2185 which is caused by a cache miss when response_type is "id_token"

### CODE REVIEW

File: lib/msal-core/src/cache/AuthCache.ts [hunk 1]
```diff
@@ -206,6 +208,31 @@ export class AuthCache extends BrowserStorage {// Singleton
         return results;
     }
 
+    /**
+     * Get idToken in the cache
+     * @param  
+     */
+    getIdToken(clientId: string, homeAccountIdentifier: string): AccessTokenValue {
+        const key = Object.keys(window[this.cacheLocation]).find((key) => {
+            const keyMatches = key.match(clientId) && key.match(homeAccountIdentifier);
```
Comment (tnorling) [inline lib/msal-core/src/cache/AuthCache.ts:217]: The idToken cacheKey should be a standard format of `msal.clientId.idtoken`

Since this is in AuthCache you can just call `this.generateCacheKey(PersistentCacheKeys.IDTOKEN, true)` to get the idtoken key

File: lib/msal-core/src/UserAgentApplication.ts [hunk 2]
```diff
@@ -1356,9 +1355,49 @@ export class UserAgentApplication {
      */
     private getCachedToken(serverAuthenticationRequest: ServerRequestParameters, account: Account): AuthResponse {
         this.logger.verbose("GetCachedToken has been called");
-        let accessTokenCacheItem: AccessTokenCacheItem = null;
         const scopes = serverAuthenticationRequest.scopes;
+        const authority = (serverAuthenticationRequest.authority) ? serverAuthenticationRequest.authority : this.authority;
```
Comment (jasonnutter) [inline lib/msal-core/src/UserAgentApplication.ts:1359]:
```suggestion
        const authority = serverAuthenticationRequest.authority || this.authority;
```

File: lib/msal-core/src/cache/AuthCache.ts [hunk 3]
```diff
@@ -206,6 +208,24 @@ export class AuthCache extends BrowserStorage {// Singleton
...
+        const idTokenKey: AccessTokenKey = {
+            authority: authority,
+            clientId: clientId,
+            scopes: undefined,
+            homeAccountIdentifier: homeAccountIdentifier
+        };
+
+        const idTokenKeyString = JSON.stringify(idTokenKey);
+        const idToken = this.getItem(idTokenKeyString);
+        const idTokenValue = JSON.parse(idToken) as AccessTokenValue;
```
Comment (jasonnutter) [inline lib/msal-core/src/cache/AuthCache.ts:224]: What should happen if `JSON.parse` throws?

File: change/msal-2020-09-10-13-11-57-idtoken-cache-lookup.json [hunk 4]
```diff
@@ -0,0 +1,8 @@
+{
+  "type": "patch",
+  "comment": "Fix ID Token cache lookup",
```
Comment (tnorling) [inline change/msal-2020-09-10-13-11-57-idtoken-cache-lookup.json:3]: Can we put the PR number in here?

File: lib/msal-core/src/cache/AuthCache.ts [hunk 5]
```diff
@@ -206,6 +208,24 @@ export class AuthCache extends BrowserStorage {// Singleton
...
+        
+        return new AccessTokenCacheItem(idTokenKey, idTokenValue);
```
Comment (tnorling) [inline lib/msal-core/src/cache/AuthCache.ts:226]: Can we add a comment here explaining why a function for getting an idToken is returning an object called AccessToken?

File: lib/msal-core/src/cache/AuthCache.ts (hunk 3 above)
Comment (tnorling) [reply lib/msal-core/src/cache/AuthCache.ts:224]: IMO this should be in a try/catch and have a logger message + return null if it throws

File: lib/msal-core/src/cache/AuthCache.ts (hunk 5 above)
Comment (tnorling) [inline lib/msal-core/src/cache/AuthCache.ts:226]: We should check the expiration and only return if it is not expired similar to the access token scenario

File: lib/msal-core/src/UserAgentApplication.ts [hunk 6]
```diff
@@ -1356,9 +1355,49 @@ export class UserAgentApplication {
...
+                expiresOn: null,
+                account: account,
+                accountState: aState,
+                fromCache: true
+            };
+
+            this.logger.verbose("Response generated and token set");
+        }
+        
+        return (idTokenObj) ? ResponseUtils.setResponseIdToken(authResponse, idTokenObj) : authResponse;
```
Comment (tnorling) [inline lib/msal-core/src/UserAgentApplication.ts:1397]: We need to assert that what was requested is being returned if it exists and is not expired. Couple scenarios to keep in mind which I do not see covered here:

1. If `id_token` or `id_token_token` is requested and there is no cached `idToken` or it is expired we need to return `null`
2. If token or `id_token_token` is requested and there is no cached `accessToken` or it is expired we need to return `null`

I think it may be better to make the above if/else block a switch on the `responseType` and in each case build the complete response, verify all the parts you need are there and return either response or `null`.

**Review by tnorling — CHANGES_REQUESTED** [review]

File: lib/msal-core/src/cache/AuthCache.ts (hunk 5 above)
Comment (technical-boy) [reply lib/msal-core/src/cache/AuthCache.ts:226]: What's your opinion on renaming AccessTokenCacheItem to TokenCacheItem? Other than the overhead involved, is there a philosophical/technical reason not to make it a more general type?

File: lib/msal-core/src/cache/AuthCache.ts (hunk 3 above)
Comment (technical-boy) [reply lib/msal-core/src/cache/AuthCache.ts]: Implemented try/catch + returning null. The logger message was already there after the call to `getIdToken` in `acquireTokenSilent`. Updated the logic around the call as well to handle this possible exception.

File: change/msal-2020-09-10-13-11-57-idtoken-cache-lookup.json (hunk 4 above)
Comment (technical-boy) [reply change/msal-2020-09-10-13-11-57-idtoken-cache-lookup.json]: Done!

File: lib/msal-core/src/cache/AuthCache.ts (hunk 5 above)
Comment (technical-boy) [reply lib/msal-core/src/cache/AuthCache.ts]: Refactored the expiration validation a bit, now we remove the ID Token from the cache and return null if expired over the offset.

File: change/msal-2020-09-10-13-11-57-idtoken-cache-lookup.json [hunk 7]
```diff
@@ -0,0 +1,8 @@
...
+  "packageName": "msal",
+  "email": "hectormgdev@gmail.com",
```
[the remark this answers is not in the document]
Comment (technical-boy) [reply change/msal-2020-09-10-13-11-57-idtoken-cache-lookup.json]: Fixed, thanks for catching this!

File: lib/msal-core/src/UserAgentApplication.ts (hunk 6 above)
Comment (technical-boy) [reply lib/msal-core/src/UserAgentApplication.ts]: I think the latest changes should cover these observations/suggestions, thanks for the help!

File: lib/msal-core/src/UserAgentApplication.ts [hunk 8]
```diff
@@ -1356,11 +1355,119 @@ export class UserAgentApplication {
...
+            case ResponseTypes.id_token_token:
+                this.logger.verbose("Returning Access Token and ID Token AuthResponse cache result");
+                return this.buildIdTokenTokenAuthResponse(idToken, serverAuthenticationRequest, scopes, account);
+            default: // ResponseTypes.token
+                this.logger.verbose("Returning Access Token AuthResponse cache result");
+                return this.buildTokenAuthResponse(idToken, serverAuthenticationRequest, scopes, account);
+        }
+    }
+
+    private buildTokenAuthResponse(idToken: IdToken, serverAuthenticationRequest: ServerRequestParameters, scopes: Array<string>, account: Account): AuthResponse {
```
Comment (tnorling) [inline lib/msal-core/src/UserAgentApplication.ts:1378]: Could we turn these into one generic static function on `ResponseUtils`?

Comment (technical-boy) [reply lib/msal-core/src/UserAgentApplication.ts:1378]: I tried at first, but the refactor wasn't trivial. There are calls to private methods like `getCachedToken()` and `getAccountState`. I'll call those methods before calling these utility functions and pass the results as arguments.

Comment (technical-boy) [reply lib/msal-core/src/UserAgentApplication.ts]: Done!

Comment (technical-boy) [reply lib/msal-core/src/UserAgentApplication.ts]: Oh sorry, misread the part about making it a single method. Let me pass the switch into a utility function and handle it in ResponseUtils.

File: lib/msal-core/src/utils/ResponseUtils.ts [hunk 9]
```diff
@@ -31,4 +34,28 @@ export class ResponseUtils {
...
+                    account: account,
+                    scopes: scopes,
+                    accountState: accountState
+                };
+                
+                authResponse = ResponseUtils.setResponseIdToken(authResponse, idToken);
+                return (authResponse.idToken) ? authResponse : null;
+            case ResponseTypes.id_token_token:
+                authResponse = ResponseUtils.setResponseIdToken(authResponse, idToken);
+                return (authResponse && authResponse.idToken) ? authResponse : null;
```
Comment (tnorling) [inline lib/msal-core/src/utils/ResponseUtils.ts:53]: should we also be checking that `authResponse.accessToken` is truthy here?

**Review by tnorling — APPROVED** [review]
One comment but otherwise looks good! Nice work

File: lib/msal-core/src/utils/ResponseUtils.ts (hunk 9 above)
Comment (hectormmg) [reply lib/msal-core/src/utils/ResponseUtils.ts:53]: Adding the check, thanks for catching it. I'm fairly certain authResponse would be `null` if there was no access token, then `setResponseIdToken` would return null immediately if that was the case, making this line correctly return `null` in the end. However, I think it's a good idea to code defensively against future changes in `getCachedToken` that may not be caught by the current logic.

**Review by jmckennon — APPROVED** [review]
LGTM

**Comment by jsmed-renson** [comment]
Thank you, @hectormmg and everyone else who helped to fix this! It seems to work perfectly. 💯
