### PR TITLE
Managed Identity - Reformatted ManagedIdentityTokenResponse + adjusted unit tests

### LINKED ISSUE #7100: Managed Identity - failed network request returns wrong error type
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.8.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

This issue has been raised by the Azure Identity SDK team while adopting msal-node's Managed Identity implementation.

On error, something like this is shown as the error message.

`ServerError: bad request: undefined - [undefined]: undefined - Correlation ID: undefined - Trace ID: undefined`

Question: Does the IMDS endpoint return the data needed to populate the error message
[here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/d6a9dfed07f436831ea370dc1120d7ca090481a6/lib/msal-common/src/response/ResponseHandler.ts#L200)?

Answer: a `managed_identity_request_failed` error should be thrown, showing the correlation id and any other details returned from the managed identity source. 

### Error Message

_No response_

### MSAL Logs

_No response_

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

N/A

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

None (Server), Other

### Regression

_No response_

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by Robbie-Microsoft**
Updated msal-common ResponseHandler's validateTokenResponse function to account for undefined portions of a network error. It now accounts for [different error formats](https://microsoft.sharepoint.com/teams/ADAL/_layouts/15/Doc.aspx?sourcedoc={0339bdd6-b5e5-4d94-b4c9-ea47127f5023}&action=edit&wd=target%28ID4S%2FMSALs%2FTechnical%2FMSI.one%7Ca2a57687-9a17-4c9e-86d1-60aa32ab5005%2FMSI%20Errors%20%20Exceptions%7C41fe3612-4fac-475d-9667-4a114aebeeda%2F%29&wdorigin=NavigationUrl) from all Managed Identity sources.

Created new unit tests + overhauled existing Managed Identity unit tests.

Manual testing was completed for all Managed Identity sources except Service Fabric.

### CODE REVIEW

File: lib/msal-node/src/response/ManagedIdentityTokenResponse.ts [hunk 1]
```diff
@@ -28,6 +28,28 @@ export type ManagedIdentityTokenResponse = {
...
-    correlationId?: string; // will be converted to correlation_id
+
+    /*
+     * (Web/Function) App Service
+     * 500 errors can return this from all MI sources as well
+     */
+    message?: string;
+    correlationId?: string;
+
+    // IMDS, Azure Arc, Service Fabric (unconfirmed)
```
Comment (bgavrilMS) [inline lib/msal-node/src/response/ManagedIdentityTokenResponse.ts:39]: still uncofirmed?

File: lib/msal-common/src/response/ResponseHandler.ts [hunk 2]
```diff
@@ -197,7 +197,17 @@ export class ResponseHandler {
             serverResponse.error_description ||
             serverResponse.suberror
         ) {
-            const errString = `${serverResponse.error_codes} - [${serverResponse.timestamp}]: ${serverResponse.error_description} - Correlation ID: ${serverResponse.correlation_id} - Trace ID: ${serverResponse.trace_id}`;
+            const errString = `Error(s): ${
+                serverResponse.error_codes || Constants.NOT_AVAILABLE
+            } - Timestamp: ${
+                serverResponse.timestamp || Constants.NOT_AVAILABLE
```
Comment (bgavrilMS) [inline lib/msal-common/src/response/ResponseHandler.ts:203]: nit: if server doesn't provide timestamp, why not default to NOW (i.e. client timestamp)

**Review by bgavrilMS — COMMENTED** [review]
Great PR, 10 lines of product code changes, 100s lines of test changes!

File: lib/msal-node/src/response/ManagedIdentityTokenResponse.ts [hunk 3]
```diff
@@ -28,6 +28,28 @@ export type ManagedIdentityTokenResponse = {
...
+    error_description?: string;
+    error_codes?: Array<string>;
+    correlation_id?: string;
+    timestamp?: string;
+    trace_id?: string;
+};
+
+/*
+ * This is the only error property that exists for Cloud Shell
+ * It can also be the only thing App Service will return
```
Comment (neha-bhargava) [inline lib/msal-node/src/response/ManagedIdentityTokenResponse.ts:50]: In case of App service we don't get this format of error response. Cloud shell is the only one with nested json error response.

File: lib/msal-node/src/response/ManagedIdentityTokenResponse.ts [hunk 4]
```diff
@@ -28,6 +28,28 @@ export type ManagedIdentityTokenResponse = {
     token_type?: AuthenticationScheme;
 
     // error
-    message?: string; // will be converted to error
-    correlationId?: string; // will be converted to correlation_id
+
+    /*
+     * (Web/Function) App Service
+     * 500 errors can return this from all MI sources as well
```
Comment (neha-bhargava) [inline lib/msal-node/src/response/ManagedIdentityTokenResponse.ts:34]: Not sure what this comment means. The error responses from different MI sources have the same format for all the errors

Comment (Robbie-Microsoft) [reply lib/msal-node/src/response/ManagedIdentityTokenResponse.ts:34]: I'm not sure what _you_ mean. These are two separate comments. Does that that clarify it for you?

**Review by neha-bhargava — APPROVED** [review]
Good set of unit tests. Make sure to manual test to ensure everything that is being parsed and returned in the exception thrown.

File: lib/msal-node/src/response/ManagedIdentityTokenResponse.ts (hunk 3 above)
Comment (Robbie-Microsoft) [reply lib/msal-node/src/response/ManagedIdentityTokenResponse.ts:50]: Look at row # 14 in [this document](https://microsoft.sharepoint.com/teams/ADAL/_layouts/15/Doc.aspx?sourcedoc={0339bdd6-b5e5-4d94-b4c9-ea47127f5023}&action=edit&wd=target%28ID4S%2FMSALs%2FTechnical%2FMSI.one%7Ca2a57687-9a17-4c9e-86d1-60aa32ab5005%2F%28Web%5C%29%20App%20Service%7Cc6be58ff-26ae-408f-9373-c8dd1c40ede3%2F%29&wdorigin=NavigationUrl) of App Service errors.

File: lib/msal-node/src/response/ManagedIdentityTokenResponse.ts (hunk 1 above)
Comment (Robbie-Microsoft) [reply lib/msal-node/src/response/ManagedIdentityTokenResponse.ts:39]: Yes. CC @neha-bhargava

File: lib/msal-common/src/response/ResponseHandler.ts (hunk 2 above)
Comment (Robbie-Microsoft) [reply lib/msal-common/src/response/ResponseHandler.ts:203]: This is for server errors, not client errors. By leaving it as not-available, we know not to go looking for it in LogsMiner if this error message is shared with us.

Comment (bgavrilMS) [reply lib/msal-common/src/response/ResponseHandler.ts:203]: I think tools like LogsMiner adds a buffer to timestamps. Client timestamp is decent approx.

**Review by bgavrilMS — APPROVED** [review]

**Review by hectormmg — APPROVED** [review]
