### PR TITLE
[msal-common] Fix ID Token Claims type

### LINKED ISSUE #2084: Incorrect idTokenClaims Type
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
N/A

## Description
ID token claims include a mix of strings/numbers but the type used (StringDict) only allows string values

MsalTypes.d.ts(5, 5): The expected type comes from this index signature. */

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```ts
import { AuthenticationResult } from '@azure/msal-browser';

const idTokenClaims: AuthenticationResult['idTokenClaims'] = {
  exp: 1596411774067 // error
  // ...
}
```

## Expected behavior
Allow numbers and strings to be used for id token claims

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

### PR DESCRIPTION
**Pull request by technical-boy**
This PR:

- Fixes #2084 
- Changes the type for AuthenticationResult.idTokenClaims from StringDict to generic object in order to allow non-string values for ID Token claims

### CODE REVIEW

File: lib/msal-common/src/response/AuthenticationResult.ts [hunk 1]
```diff
@@ -27,7 +26,7 @@ export type AuthenticationResult = {
     scopes: Array<string>;
     account: AccountInfo;
     idToken: string;
-    idTokenClaims: StringDict;
+    idTokenClaims: Object;
```
Comment (tnorling) [inline lib/msal-common/src/response/AuthenticationResult.ts:29]: We have an IdTokenClaims type, can we use that instead of the generic "Object"?

Comment (technical-boy) [reply lib/msal-common/src/response/AuthenticationResult.ts:29]: We decided to go with a generic Object given that ID Token Claims can conceivably contain claims of any type (excluding functions). The IdTokenClaims type wouldn't solve this particular issue because it defines all the listed claims as string-typed.

Comment (tnorling) [reply lib/msal-common/src/response/AuthenticationResult.ts:29]: In that case, can we update the typing in `IdTokenClaims`? Each specific claim should in theory have their own type and we should make sure our internal type complies with what the server is sending. e.g. We can expect `exp` to always be `number`, `iss` to always be `string`, etc.

Comment (jasonnutter) [reply lib/msal-common/src/response/AuthenticationResult.ts:29]: We could attempt to explicitly type all of the possible claims, but my understanding is that those may change, and there are also many optional claims that applications can enable. Ultimately, we want to fix bugs like #2084 and #1766 where we have incorrectly asserted at all claims will be strings. And it would be easier and future-proof to only guarantee that it will be an object, instead of attempting to document all possible claims.

Comment (tnorling) [reply lib/msal-common/src/response/AuthenticationResult.ts:29]: This value of this is set to an object that is type `IdTokenClaims` in `ResponseHandler` and the `IdToken` constructor so I'm not sure changing it from `StringDict` to `Object` here is really going to solve this problem on it's own. We would either need to change the types in all places in the code or update the type for each claim.

Comment (technical-boy) [reply lib/msal-common/src/response/AuthenticationResult.ts:29]: I agree that only changing it here doesn't solve the problem. I was initially unaware that the IdTokenClaims type existed in the library, so I only knew to update the AuthenticationResult type that was throwing the error in #2084.  So if we were to decide on a generic Object type to replace IdTokenClaims, I'd apply that change in the ResponseHandler and the IdToken constructor (and anywhere else the IdTokenClaims type is found).

Having said that, is there any value in explicitly typing each claim? I don't think I have enough context to foresee what kind of future bug may arise for having the claims ambiguously typed as generic Object attributes (maybe the fact that developers won't immediately know which claims are supported by default?)

File: change/@azure-msal-common-2020-08-11-16-45-31-fix-id-token-claims-type.json [hunk 2]
```diff
@@ -0,0 +1,8 @@
+{
+  "type": "patch",
+  "comment": "Change AuthenticationResult.idTokenClaims type from StringDict to generic Object type to allow for non-string valued ID Token Claims. Also updates exp claim type in IdTokenClaims type from string to number (#2105)",
```
Comment (tnorling) [inline change/@azure-msal-common-2020-08-11-16-45-31-fix-id-token-claims-type.json:3]: nit: In the interest of easily digestible change files we should aim to keep these comments pretty small. People can then open the relevant PR for more detail. Something like "Update typing of IdTokenClaims (#2105)" would be fine here.

Comment (pkanher617) [reply change/@azure-msal-common-2020-08-11-16-45-31-fix-id-token-claims-type.json:3]: +1

Comment (technical-boy) [reply change/@azure-msal-common-2020-08-11-16-45-31-fix-id-token-claims-type.json:3]: Cool, I'll keep this in mind for the future as well!

Comment (technical-boy) [inline change/@azure-msal-common-2020-08-11-16-45-31-fix-id-token-claims-type.json:3]:
```suggestion
  "comment": "Update typing of IdTokenClaims (#2105)",
```
