### PR TITLE
Fixed bug in msal-node's httpClient

### LINKED ISSUE #4879: Getting ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints with @azure/msal-node 1.9.1
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.9.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Since upgrading from 1.9.0 to 1.9.1 we are running into the error listed in this issue below. We have a node application that runs on an interval to update profile pictures in [Backstage a Developer Portal](https://backstage.io/) we are using. It's very simple.

Rolling back to 1.9.0 the error goes away. I'm not sure what specifically is causing this issue but I feel like it is something in PR #4744. That being said there might be simply something that we need to include to resolve this like some additional configuration.

Any help with this would be greatly appreciated!

### Error Message

ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/{tenantId}/v2.0/.well-known/openid-configuration

Note that `{tenantId}` in the URL above is our actual tenantId, just removed for security reasons.

### Msal Logs

_No response_

### MSAL Configuration

```javascript
const clientConfig = {
      auth: {
        clientId,
        clientSecret,
        authority: `https://login.microsoftonline.com/${tenantId}`,
      },
    };
```

### Relevant Code Snippets

```javascript
const clientConfig = {
      auth: {
        clientId,
        clientSecret,
        authority: `https://login.microsoftonline.com/${tenantId}`,
      },
    };

    const authClient = new ConfidentialClientApplication(clientConfig);

    const tokens = await authClient.acquireTokenByClientCredential({
      scopes: ['https://graph.microsoft.com/.default'],
    });
```

### Reproduction Steps

I'm not totally sure how to describe this:

1. Upgrade to @azure/msal-node 1.9.1
2. Run the application

Notice in the logs the error listed in this issue occurs

### Expected Behavior

There should be no error and the process should continue to work as it did with version 1.9.0

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

@azure/msal-node 1.9.0

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by Robbie-Microsoft**
We've been receiving reports of users receiving the error:

`Error: TypeError
Error Description: The "listener" argument must be of type function. Received an instance of Object - []`

I wasn't able to reproduce the issue from any user reports, however, a fellow Microsoft employee who works on the VSCode team received the same error in a VSCode extension she was building. She walked me through the build steps for her VSCode extension and reproduction steps, and then I was finally able to reproduce the issue.

As it relates to msal-node's HttpClient: I'm not sure why this error was being thrown, because the nodejs code where the error occurs adheres to the documentation on NodeJS's website. Specifically, I'm talking about [https.request](https://nodejs.org/docs/latest-v16.x/api/http.html#httprequesturl-options-callback).

The relevant code in msal-node's code base is [located here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/network/HttpClient.ts#L249). According to the docs, we can make a https request this way:
 ```https.request(url, options)```.

However, I needed to change that linked code to the following to resolve the error:
```
const customOptions: https.RequestOptions = {
        hostname: url.hostname, // <-- new code
        path: url.pathname, // <-- new code
        method: httpMethod,
        headers: options?.headers || emptyHeaders,
    };
...
https.request(customOptions)
```

Update: I have been looking into this for a while, and the only conclusion I can draw is that maybe the NodeJS docs are incorrect, or this is a NodeJS bug.

### CODE REVIEW

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts [hunk 1]
```diff
@@ -264,11 +267,17 @@ const networkRequestViaHttps = <T>(
     const isPostRequest = httpMethod === HttpMethod.POST;
     const body: string = options?.body || "";
 
+    const url = new URL(urlString);
     const emptyHeaders: Record<string, string> = {};
     const customOptions: https.RequestOptions = {
+        hostname: url.hostname,
```
Comment (bgavrilMS) [inline samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts]: We should not be writing this type of code, you are bound to get it wrong. There seems to be a library function for this `https://nodejs.org/api/url.html#urlurltohttpoptionsurl`

(for example, you are missing the port)

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts [hunk 2]
```diff
@@ -287,7 +296,7 @@ const networkRequestViaHttps = <T>(
     }
 
     return new Promise<NetworkResponse<T>>((resolve, reject) => {
-        const request = https.request(url, customOptions);
+        const request = https.request(customOptions);
```
Comment (bgavrilMS) [inline samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:317]: Can you please create a minimal repro and open a bug on NodeJS repo and see what they say ? It looks to me that the issue is with them. You can then reference the bug in you "workaround" code. 

https://github.com/nodejs/node/blob/v13.14.0/lib/_http_client.js#L86

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts [hunk 3]
```diff
@@ -255,7 +258,7 @@ const networkRequestViaProxy = <T>(
 };
 
 const networkRequestViaHttps = <T>(
```
Comment (bgavrilMS) [inline samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:282]: Would this bug happen if we were using an HttpClient based on Axios?

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts [hunk 4]
```diff
@@ -287,7 +296,7 @@ const networkRequestViaHttps = <T>(
     }
 
     return new Promise<NetworkResponse<T>>((resolve, reject) => {
-        const request = https.request(url, customOptions);
```
Comment (bgavrilMS) [inline samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:290]: Does the bug still happen if you use `https.request(url: Url, customOptions: Options)` instead of `https.request(url: string, customOptions: Options)` ?

Comment (Robbie-Microsoft) [reply samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:290]: Yep

**Review by bgavrilMS — CHANGES_REQUESTED** [review]
See comments.

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts (hunk 1 above)
Comment (Robbie-Microsoft) [reply samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:273]: What do you mean by "We should not be writing this type of code"? What "type of code" are you referring to? What am I bound to get wrong? I'm using the URL as it's defined on the MDN web docs [here](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL). I'm following the example RequestOptions as defined in the NodeJS docs [here](https://nodejs.org/api/https.html#httpsrequesturl-options-callback), and it does appear that I forgot the port.

It looks like:
```
const options = {
  hostname: 'encrypted.google.com',
  port: 443,
  path: '/',
  method: 'GET',
};
```

Comment (Robbie-Microsoft) [reply samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:273]: Actually, because this is an htpps request, the port is automatically assumed to be 443.

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts (hunk 2 above)
Comment (sameerag) [reply samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:317]: Yes, this issue is definitely on Node.js. I tested it the other day and had the same issue.

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts (hunk 3 above)
Comment (Robbie-Microsoft) [reply samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:282]: I can confirm that this bug does not occur in the old implementation of HttpClient (axios).

Comment (Robbie-Microsoft) [reply samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:282]: I'll be making a new PR adding back the old implementation for cases when proxyUrl isn't used.

File: samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts (hunk 2 above)
Comment (Robbie-Microsoft) [reply samples/msal-node-samples/custom-INetworkModule-and-network-tracing/HttpClientCurrent.ts:317]: @bgavrilMS I'm unable to create a minimal repro that reproduces the bug.

**Review by sameerag — APPROVED** [review]
Approved. As discussed, lets work on Axios based client as an option in a separate PR.

**Review by bgavrilMS — APPROVED** [review]

File: lib/msal-node/src/network/HttpClient.ts [hunk 5]
```diff
@@ -223,10 +224,12 @@ const networkRequestViaHttps = <T>(
...
     const body: string = options?.body || "";
 
-    const emptyHeaders: Record<string, string> = {};
+    const url = new URL(urlString);
+    const headers = options?.headers || {} as Record<string, string>;
     const customOptions: https.RequestOptions = {
         method: httpMethod,
-        headers: options?.headers || emptyHeaders,
+        headers: headers,
+        ...urlToHttpOptions(url),
```
Comment (bgavrilMS) [inline lib/msal-node/src/network/HttpClient.ts]: if you can't use this method `urlToHttpOptions` from the library, copy it's source code (it's on GH, see in Teams where I provided a link) and also the unit test associated.
