### PR TITLE
Ensure interceptor uses ID token property if response is of type id_token

### LINKED ISSUE #1475: MsalInterceptor renews token but Authorization header is missing from intercepted call
## Library
- [x] `msal@1.2.2`
- [x] `@azure/msal-angular@1.0.0-beta.4`
- [x] `@angular@9.0.1`

## Framework
Angular 9

## Description
We have angular front and are using @azure/msal-angular@1.0.0-beta.4. After an hour after login when token expires, next api calls fails, because it has null in Authorization header:

`Authorization: Bearer null`

Renewal itself seems to work because api calls after this failed one work ok. Shouldn't MsalInterceptor renew token and apply it to the intercepted request?

This is msal log from the renewal:

```
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:43 GMT:1.2.2-Info renewidToken is called
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:43 GMT:1.2.2-Info Add msal frame to document:msalIdTokenFrame
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:43 GMT:1.2.2-Info LoadFrame: msalIdTokenFrame
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:44 GMT:1.2.2-Info Add msal frame to document:msalIdTokenFrame
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:44 GMT:1.2.2-Info Returned from redirect url
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:44 GMT:1.2.2-Info Processing the callback from redirect response
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:44 GMT:1.2.2-Info State status:true; Request type:LOGIN
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:44 GMT:1.2.2-Info State is right
main-es2015.f4c8c8ef197a06fb7d31.js:1 MSAL:  Tue, 07 Apr 2020 08:11:44 GMT:1.2.2-Info Fragment has id token
```

## Security
No

## Regression
Unknown

## Configuration

```
{
      auth: {
        clientId: environment.clientId,
        authority: 'https://login.microsoftonline.com/' + environment.tenantId,
      },
      cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: isIE
      },
    }, 

    {
        unprotectedResources: [
          '/xxx/yyy',
        ]
    }
```

## Reproduction steps
1. Login to angular application using AAD and msal-angular
2. Wait an hour for the token to expire
3. Initiate api call from frontend.

## Expected behavior
token renewal should happen in background and api call should not fail.

### PR DESCRIPTION
**Pull request by jasonnutter**
Since it is technically possible to use an ID token to protect a route, the interceptor needs to properly differentiate between access tokens and id tokens and use the correct properties. 

Currently, in situations where an ID token is used to protect a route, the interceptor will attach a `Bearer null` header to outgoing requests, because it naively assumes that the token will always be present on the `accessToken` property. This is because when we retrieve a cached ID token, the response sets the ID token as `accessToken`, however, we retrieving a new ID token from the network, the ID token is only set as `idToken`.

This PR ensures we inspect the `tokenType` value first, and properly use the correct field instead of relying on `accessToken` always being set.

Fixes:
- #1475

### CODE REVIEW

**Review by tnorling — APPROVED** [review]

File: lib/msal-angular/src/msal.interceptor.ts [hunk 1]
```diff
@@ -27,14 +27,14 @@ export class MsalInterceptor implements HttpInterceptor {
...
-        let accessToken: string;
+        let token: string;
 
         // Acquire a token for this request, and attach as proper auth header.
         return from(
             this.auth.acquireTokenSilent({ scopes })
                 .then((response: AuthResponse) => {
-                    accessToken = response.accessToken;
-                    const authHeader = `Bearer ${response.accessToken}`;
+                    token = response.tokenType === ServerHashParamKeys.ID_TOKEN ? response.idToken.rawIdToken : response.accessToken;
```
Comment (DarylThayil) [inline lib/msal-angular/src/msal.interceptor.ts:36]: Can you add a test for this ?

Comment (jasonnutter) [reply lib/msal-angular/src/msal.interceptor.ts:36]: Done.

**Comment by DarylThayil** [comment]
Thanks for adding tests, approved

**Review by DarylThayil — APPROVED** [review]
