### PR TITLE
Fix typing for expiresOn field

### LINKED ISSUE #2991: Null expiresOn for tokens?
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.10.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

When can AuthenticationResult.expiresOn be null? I get this object back from handleRedirectPromise, acquireTokenSilent, etc.

```
const msalConfig: Configuration = {
  auth: {
    clientId: 'XXX',
    authority: 'https://login.microsoftonline.com/consumers/',
    postLogoutRedirectUri: `${window.location.origin}/logout`,
  },
  cache: { cacheLocation: 'localStorage' },
};
```

### PR DESCRIPTION
**Pull request by pkanher617**
Fixes #2991.

Also throws if no access token entity is present in `generateAuthenticationResult`

### CODE REVIEW

File: lib/msal-common/src/response/ResponseHandler.ts [hunk 1]
```diff
@@ -316,6 +316,8 @@ export class ResponseHandler {
             responseScopes = ScopeSet.fromString(cacheRecord.accessToken.target).asArray();
             expiresOn = new Date(Number(cacheRecord.accessToken.expiresOn) * 1000);
             extExpiresOn = new Date(Number(cacheRecord.accessToken.extendedExpiresOn) * 1000);
+        } else {
+            throw ClientAuthError.createAccessTokenEntityNullError();
```
Comment (jasonnutter) [inline lib/msal-common/src/response/ResponseHandler.ts:320]: This might cause a problem for angular with the b2c issue where it returns a blank access token: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.interceptor.ts#L62

It might be better to wait until b2c fixes that issue before we include this specific change, given there could be apps (and wrapper libraries) that are relying upon a blank access token to be returned, instead of a new error.

File: lib/msal-common/src/response/ResponseHandler.ts [hunk 2]
```diff
@@ -299,7 +299,7 @@ export class ResponseHandler {
         resourceRequestUri?: string): Promise<AuthenticationResult> {
         let accessToken: string = "";
         let responseScopes: Array<string> = [];
-        let expiresOn: Date | null = null;
+        let expiresOn: Date;
```
Comment (tnorling) [inline lib/msal-common/src/response/ResponseHandler.ts:302]: This implicitly becomes `Date | undefined`, what was the original issue?

Comment (pkanher617) [reply lib/msal-common/src/response/ResponseHandler.ts:302]: Below we assign the value in the AuthenticationResult object to this variable, which caused a type mismatch.

File: lib/msal-common/src/response/ResponseHandler.ts (hunk 1 above)
Comment (pkanher617) [reply lib/msal-common/src/response/ResponseHandler.ts:320]: Do we know when that fix is going to get implemented? In the meantime that means we DO have scenarioes where no access token is returned.

Comment (jasonnutter) [reply lib/msal-common/src/response/ResponseHandler.ts:320]: This quarter, I believe. And yes, it means we do, although its technically a bug and not by design.

**Review by hectormmg — APPROVED** [review]

**Review by tnorling — APPROVED** [review]

**Review by jasonnutter — APPROVED** [review]
