### PR TITLE
Fix React inProgress startup bug

### LINKED ISSUE #4282: MSAL in Storybook
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I'm Trying to set up MSAL in Storybook using a decorator, https://storybook.js.org/docs/react/writing-stories/decorators

It works fine on pageload and if refresh the page, but if i click between the stories I can see that "inProgress" is "startup" and nothing else happens.

I have tried with different configurations for cache, but to no avail.

Anyone got any tips or have done this themself?

I reckon it is something on Storybooks side and how they handle routing as it the same configration i use for the other apps and they work fine.

I dont want to add MSALProvider for each story

### MSAL Configuration

```javascript
auth: {
    clientId: xxx,
    authority: xxx,
    redirectUri: '/',
  },
  cache: {
    secureCookies: true,
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
  },
```

### Relevant Code Snippets

```javascript
./storybook/preview.js

const withMSALProvider = (Story) => {
  return (
    <MsalProvider instance={publicClientApplication}>
      <MsalAuthenticationTemplate
        interactionType={InteractionType.Popup}
        loadingComponent={InProgressComponent}
        errorComponent={ErrorComponent}
      >
        <Story />
      </MsalAuthenticationTemplate>

      <UnauthenticatedTemplate>
        <LoggInn />
      </UnauthenticatedTemplate>
    </MsalProvider>
  );
};

export const decorators = [withMSALProvider];
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by tnorling**
If `handleRedirectPromise` is called before `MsalProvider` is rendered, the event callbacks that `MsalProvider` relies on to set `inProgress` state won't be available yet resulting in `inProgress` being forever stuck in `startup`. This PR fixes this by setting `inProgress` to `none` in the `finally` block of its own call to `handleRedirectPromise`

Fixes #4282

### CODE REVIEW

File: lib/msal-react/src/MsalProvider.tsx [hunk 1]
```diff
@@ -86,6 +86,15 @@ export function MsalProvider({instance, children}: MsalProviderProps): React.Rea
         instance.handleRedirectPromise().catch(() => {
             // Errors should be handled by listening to the LOGIN_FAILURE event
             return;
+        }).finally(() => {
```
Comment (jasonnutter) [inline lib/msal-react/src/MsalProvider.tsx:89]: We've had problems with ".finally" in the past with old browsers/polyfills, FYI.

**Review by jasonnutter — APPROVED** [review]
One comment, otherwise looks good!

File: lib/msal-react/src/MsalProvider.tsx (hunk 1 above)
Comment (tnorling) [reply lib/msal-react/src/MsalProvider.tsx:89]: Is it a large enough concern to not use it here or can we address it if and when it comes up?

**Review by pkanher617 — APPROVED** [review]
