### PR TITLE
Clear interaction status even if there is no ongoing request

### LINKED ISSUE #4295: Login fails with interaction_in_progress error
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Eventhough, handleRedirectPromise is the first thing that happens in our SPA app, interaction_in_progress is thrown when logging-in. 

`storeAuthStateInCookie` is set to true.

This is the cookie I see in Chrome's dev tools:
image

### Error Message

(with verbose logs enabled) 
image

### Msal Logs

MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Verbose - handleRedirectPromise called
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getIdTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getAccessTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getRefreshTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getAccessTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 2: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:handleRedirectStart
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : [2ef17b53-b723-4562-932d-a253ca219c99] : msal.js.browser@2.18.0 : Verbose - initializeServerTelemetryManager called
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getTemporaryCache: storeAuthStateInCookies set to true, retrieving from cookies
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : [2ef17b53-b723-4562-932d-a253ca219c99] : msal.js.browser@2.18.0 : Verbose - getRedirectResponseHash called
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.removeItem: storeAuthStateInCookie is true, clearing item cookie
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : [2ef17b53-b723-4562-932d-a253ca219c99] : msal.js.browser@2.18.0 : Verbose - Hash does not contain known properties, returning cached hash
MsalPublicClientApplicationConfig.ts:37 msal: 2: [Thu, 25 Nov 2021 03:06:42 GMT] : [2ef17b53-b723-4562-932d-a253ca219c99] : msal.js.browser@2.18.0 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.cleanRequestByInteractionType called
MsalPublicClientApplicationConfig.ts:37 msal: 2: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:handleRedirectEnd
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Verbose - loginRedirect called
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Verbose - preflightBrowserEnvironmentCheck started
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Verbose - acquireTokenRedirect called
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Verbose - getAllAccounts called
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getIdTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getAccessTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getRefreshTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getAccessTokenCredential: cache hit
MsalPublicClientApplicationConfig.ts:37 msal: 2: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:acquireTokenStart
MsalPublicClientApplicationConfig.ts:37 msal: 3: [Thu, 25 Nov 2021 03:06:42 GMT] : [e64d39f1-8604-477f-a90d-b0ef2d7381f9] : msal.js.browser@2.18.0 : Verbose - preflightInteractiveRequest called, validating app environment
MsalPublicClientApplicationConfig.ts:37 msal: 4: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Trace - BrowserCacheManager.getTemporaryCache: storeAuthStateInCookies set to true, retrieving from cookies
MsalPublicClientApplicationConfig.ts:37 msal: 2: [Thu, 25 Nov 2021 03:06:42 GMT] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:acquireTokenFailure
AuthError.ts:45 
        
       Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (AuthError.ts:45)
    at new BrowserAuthError (BrowserAuthError.ts:159)
    at Function.BrowserAuthError.createInteractionInProgressError (BrowserAuthError.ts:240)
    at RedirectClient.StandardInteractionClient.preflightInteractiveRequest (StandardInteractionClient.ts:206)
    at RedirectClient.<anonymous> (RedirectClient.ts:24)
    at step (viewportRowModelModule.js:4)
    at Object.next (viewportRowModelModule.js:4)
    at viewportRowModelModule.js:4
    at new Promise (<anonymous>)
    at __awaiter (viewportRowModelModule.js:4)
    at RedirectClient.acquireToken (RedirectClient.ts:23)
    at PublicClientApplication.<anonymous> (ClientApplication.ts:205)
    at step (viewportRowModelModule.js:4)
    at Object.next (viewportRowModelModule.js:4)
    at viewportRowModelModule.js:4
    at new Promise (<anonymous>)
    at __awaiter (viewportRowModelModule.js:4)
    at PublicClientApplication.ClientApplication.acquireTokenRedirect (ClientApplication.ts:191)
    at PublicClientApplication.<anonymous> (PublicClientApplication.ts:65)
    at step (viewportRowModelModule.js:4)
    at Object.next (viewportRowModelModule.js:4)
    at viewportRowModelModule.js:4
    at new Promise (<anonymous>)
    at __awaiter (viewportRowModelModule.js:4)
    at PublicClientApplication.loginRedirect (PublicClientApplication.ts:63)
    at MsalAuthenticationProvider._callee5$ (MsalAuthenticationProvider.ts:108)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at MsalAuthenticationProvider.<anonymous> (asyncToGenerator.js:21)
    at MsalAuthenticationProvider.login (MsalAuthenticationProvider.ts:24)
    at _callee3$ (index.tsx:63)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)

### MSAL Configuration

```javascript
auth: {
        clientId: "f9818e52-50bd-463e-8932-a1650bd3fad2",
        authority: "https://login.microsoftonline.com/organizations", // organizations changes to [tenantId] in some scenarios.
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: true,
    },
```

### Relevant Code Snippets

```javascript
handleRedirectPromise is the first thing that happens when the app loads. 
handleRedirectPromise is awaited. 
loginRedirect is only called after handleRedirectPromise finishes.
```

### Reproduction Steps

I am not sure what causes the cookie msal.interaction.status to be added, but if I manually add the cookie `msal.interaction.status` with the clientId as its value, loading the site again (Which calls handleRedirectPromise) doesn't delete it. 

### Expected Behavior

msal.interaction.status should always be deleted when calling `handleRedirectPromise` (At least for the same clientId). 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

@azure/msal-browser@2.15.0

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by jasonnutter**
It appears application can get in a state where `msal.interaction.status` temporary cache value is present, but msal does not have an ongoing request. In this scenario, `cleanRequestByInteractionType` does not result in clearing interaction status. This ensures we always clear interaction status regardless.

### CODE REVIEW

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 1]
```diff
@@ -853,6 +853,7 @@ export class BrowserCacheManager extends CacheManager {
             }
         });
         this.clearMsalCookies();
+        this.setInteractionInProgress(false);
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: Is this perhaps more an issue with `clearMsalCookies` not properly accounting for the fact that the interaction status key doesn't contain clientId anymore?

I'm wondering if always clearing both local/session storage and cookies here might cause new problems. For example there's an ongoing popup request but we called `cleanRequestByInteractionType("redirect")`. I would not expect to clear interaction in progress in this case.

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: Should we instead update `clearMsalCookies` to correctly clear the interaction in progress cookie?

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: I thought about that, this seemed a bit easier given we already have a method that understands how to clear the interaction in progress cache value.

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: I'm more concerned about whether or not it's the right thing to clear session storage here (given that we're specifically trying to match interaction types). Were you able to determine how you can get into this state where the cookie still exists but session storage has been cleared?

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: > I'm more concerned about whether or not it's the right thing to clear session storage here (given that we're specifically trying to match interaction types)

This should just clear the `msal.interaction.status` entry. That seems safe in this context (app is loaded and there is no hash in the url)?

> Were you able to determine how you can get into this state where the cookie still exists but session storage has been cleared?

Linked ticket has the context, but I'm not sure how to reproduce it outside manually creating teh cookie.

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: > This should just clear the msal.interaction.status entry. That seems safe in this context (app is loaded and there is no hash in the url)?

This function is called in a couple different contexts, not just on page load, so I don't think we can just assume it's ok to clear it.

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: `cleanRequestByInteractionType` is only called one other place aside from `RedirectClient#handleRedirectPromise`, which is here: 

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/e3c66105f3bf617dc4fd06905e04b37e865c303c/lib/msal-browser/src/utils/PopupUtils.ts#L142

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: Should this method check for interactiontype and only call `setInteractionProgress(false)` if the type is redirect?

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: We can leave this as is for now but we should take a deeper look at our cache clearing logic in the future.

**Review by tnorling — APPROVED** [review]

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 1 above)
Comment (sameerag) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: I have the same concerns. That there should be more clarity for cookies vs session storage clearance and no ambiguity there.

Comment (sameerag) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: Does checking this in have side effects?

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: Nothing comes to mind. I guess the question for me is that when we call `cealnRequestByInteractionType`, is there any reason we wouldn't want the interaction status to be cleared as well?

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: Note that this value was getting cleared before, but then stopped getting cleared when the temp cache key for interaction status changed.

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: > Nothing comes to mind. I guess the question for me is that when we call `cealnRequestByInteractionType`, is there any reason we wouldn't want the interaction status to be cleared as well?

A scenario I had in mind is if you call `loginPopup` and then while that is in progress you call `handleRedirectPromise`. We could argue that's incorrect usage and not likely something people would run into, though potentially a possible scenario with our wrapper libraries that call `handleRedirectPromise` in the background. This scenario would theoretically work today, but break with this change.

> Note that this value was getting cleared before, but then stopped getting cleared when the temp cache key for interaction status changed.

This value was getting cleared in **cookies** before, not necessarily also `sessionStorage` and I think that distinction is important for the scenario above.

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: > A scenario I had in mind is if you call loginPopup and then while that is in progress you call handleRedirectPromise. We could argue that's incorrect usage and not likely something people would run into, though potentially a possible scenario with our wrapper libraries that call handleRedirectPromise in the background. This scenario would theoretically work today, but break with this change.

I thought about that, which is why I was curious if I should add a check to only clear interaction status here if the interaction type is redirect.

> This value was getting cleared in cookies before, not necessarily also sessionStorage and I think that distinction is important for the scenario above.

Was this nuance intentional?

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: > I thought about that, which is why I was curious if I should add a check to only clear interaction status here if the interaction type is redirect.

That wouldn't solve the problem since `handleRedirectPromise` would still clear an ongoing popup interaction.

> Was this nuance intentional?

I don't remember specifically why this was but I suspect it's because request cookies are only important for redirect scenarios so it doesn't matter what the interaction type is.

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:856]: > That wouldn't solve the problem since handleRedirectPromise would still clear an ongoing popup interaction.

I only see references to `this.browserStorage.cleanRequestByInteractionType(InteractionType.Redirect);` in `handleRedirectPromise`?

> I don't remember specifically why this was but I suspect it's because request cookies are only important for redirect scenarios so it doesn't matter what the interaction type is.

Ah, makes sense. But as you note, invoking `handleRedirectPromise` during a popup operation is not correct, so this clearing session storage shouldn't be an issue, yeah?

**Review by hectormmg — APPROVED** [review]
Lgtm
