### PR TITLE
Fixed broken homeAccountId check in CacheManager

### LINKED ISSUE #5134: multiple_matching_tokens The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account.
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.12.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

After adding 2 new MSAL flows for acquireTokenByRefreshToken and acquireTokenOnBehalfOf we started seeing some errors in existing workflows that had no issues (acquireTokenByClientCredential). The error we are receiving from MSAL is "multiple_matching_tokens". We only see this issue in acquireTokenByClientCredential for our singleton client.

We added `authority` to all of our client codes as suggested by the error message below but we are still receiving these errors. 

We noticed 2 similar incidents that were supposed to fix this issue:
[#4486](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4486)
[#4691](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4691)

### Error Message

>"stack": "ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..\n    at ClientAuthError.AuthError [as constructor] (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:496:24)\n    at new ClientAuthError (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:790:28)\n    at Function.ClientAuthError.createMultipleMatchingTokensInCacheError (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:885:16)\n    at ClientCredentialClient.readAccessTokenFromCache (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:6036:35)\n    at ClientCredentialClient.<anonymous> (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:5996:50)\n    at step (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)\n    at Object.next (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)\n    at /app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:53:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:49:12)",
>     "message": "**multiple_matching_tokens**: **The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..**",
>     "errorCode": "multiple_matching_tokens",
>     "errorMessage": "The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..",
>     "subError": "",
>     "name": "ClientAuthError"
>   }

### Msal Logs

_No response_

### MSAL Configuration

```javascript
auth: {
                clientId: "9edfcdd9-0bc5-4bd4-b287-c3afc716aac7"
                authority: "https://login.microsoftonline.com/organizations",
                clientCertificate: {
                    thumbprint: pem.thumbprint,
                    privateKey: pem.privateKey,
                    x5c: pem.certificate,
                },
            },
```

### Relevant Code Snippets

```javascript
this._client.acquireTokenByClientCredential({
  "scopes": [
    "https://management.azure.com/.default"
  ],
  "authority": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47"
}),
```

### Reproduction Steps

N/A

### Expected Behavior

Expectation would be for `acquireTokenBYClientCredential` to return a valid access token matching the passed in requirements.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

_No response_

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by Robbie-Microsoft**
The homeAccountId check in CacheManager.ts did not account for a homeAccountId that was an empty string.

For example, say the following two access tokens exist in the cache for a confidential client application - one for an application and the other for a user account:

```
        "-login.windows.net-accesstoken-[...]-https://graph.microsoft.com/.default--": {
            "home_account_id": "",
            "credential_type": "AccessToken",
            ...
        },
        "[...]-login.windows.net-accesstoken-[...]-profile openid email https://graph.microsoft.com/user.read https://graph.microsoft.com/user.read.all https://graph.microsoft.com/.default--": {
            "home_account_id": "[...]",
            "credential_type": "AccessToken",
            ...
        }
```

Under the old homeAccountId logic, both access tokens were returned when an application called `acquireTokenByClientCredential` because !!("") equates to false, and the rest of the homeAccountId comparison was not being performed. Now, only the matching access token is returned.

### CODE REVIEW

File: lib/msal-common/src/cache/CacheManager.ts [hunk 1]
```diff
@@ -390,7 +390,8 @@ export abstract class CacheManager implements ICacheManager {
                 return;
             }
 
-            if (!!homeAccountId && !this.matchHomeAccountId(entity, homeAccountId)) {
+            // homeAccountId can be an empty string, and !!("") = false
+            if (!!(typeof homeAccountId === "string") && !this.matchHomeAccountId(entity, homeAccountId)) {
```
Comment (bgavrilMS) [inline lib/msal-common/src/cache/CacheManager.ts]: Quite subtle, good catch. 

Is it possible to write a regression test for this?

Comment (Robbie-Microsoft) [reply lib/msal-common/src/cache/CacheManager.ts]: I've been working on that

File: lib/msal-common/src/cache/CacheManager.ts [hunk 2]
```diff
@@ -390,7 +390,8 @@ export abstract class CacheManager implements ICacheManager {
                 return;
             }
 
-            if (!!homeAccountId && !this.matchHomeAccountId(entity, homeAccountId)) {
+            // homeAccountId can be an empty string, and !!("") = false
```
Comment (bgavrilMS) [inline lib/msal-common/src/cache/CacheManager.ts]: Consider adding a comment more about the WHY and not the WHAT, i.e. 

"In client_credentials, homeAccountId is null, and the logic should filter out tokens with homeAccountId, because these are user tokens"

File: lib/msal-common/src/cache/CacheManager.ts (hunk 1 above)
Comment (jasonnutter) [reply lib/msal-common/src/cache/CacheManager.ts]: `!!` shouldnt be needed, as `typeof var === "type"` will return a boolean.

File: change/@azure-msal-common-f46053c3-36ec-417f-b7a2-250e2a580f76.json [hunk 3]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "Fixed broken homeAccountId check in CacheManager",
```
Comment (jasonnutter) [inline change/@azure-msal-common-f46053c3-36ec-417f-b7a2-250e2a580f76.json]:
```suggestion
  "comment": "Fixed broken homeAccountId check in CacheManager #5246",
```

File: lib/msal-common/src/cache/CacheManager.ts [hunk 4]
```diff
@@ -390,7 +390,8 @@ export abstract class CacheManager implements ICacheManager {
                 return;
             }
 
-            if (!!homeAccountId && !this.matchHomeAccountId(entity, homeAccountId)) {
+            // homeAccountId can undefined, and we want to filter out cached items that have a homeAccountId of ""
```
Comment (sameerag) [inline lib/msal-common/src/cache/CacheManager.ts]: Cached items that have a homeAccountId as "null" or "empty string"??

File: lib/msal-common/src/cache/CacheManager.ts [hunk 5]
```diff
@@ -390,7 +390,8 @@ export abstract class CacheManager implements ICacheManager {
...
+            if ((typeof homeAccountId === "string") && !this.matchHomeAccountId(entity, homeAccountId)) {
```
Comment (sameerag) [inline lib/msal-common/src/cache/CacheManager.ts:397]: Why are we checking "type"? Are we expecting data corruption? and should we check for "null" or "empty string" or both?

Comment (Robbie-Microsoft) [reply lib/msal-common/src/cache/CacheManager.ts:394]: @sameerag homeAccountId can be undefined or empty string. If it's undefined, we're skipping this check. Otherwise we need to account for a client credential application which has a homeAccountId of empty string.

File: lib/msal-common/src/cache/CacheManager.ts [hunk 6]
```diff
@@ -390,7 +390,8 @@ export abstract class CacheManager implements ICacheManager {
                 return;
             }
 
-            if (!!homeAccountId && !this.matchHomeAccountId(entity, homeAccountId)) {
```
Comment (bgavrilMS) [inline lib/msal-common/src/cache/CacheManager.ts:393]: I don't know JS that well to comment on the topic of "falsy" variables, but the algorithm here should be: 

- if the `homeAccountId` filter is `falsy` (i.e. we're asking for an app token), then only an entity with `homeAccountId` which is `falsy` may be returned.

Comment (tnorling) [reply lib/msal-common/src/cache/CacheManager.ts:393]: > if the homeAccountId filter is falsy (i.e. we're asking for an app token)

I'm not so sure we can make this assumption. If we want to explicitly ask for a token with no homeAccountId we should explicitly provide `null` or perhaps empty string. This API may be called with any combination of filters and the absence of one just means "don't check".

File: lib/msal-common/src/cache/CacheManager.ts (hunk 5 above)
Comment (Robbie-Microsoft) [reply lib/msal-common/src/cache/CacheManager.ts:397]: @sameerag In the [generateHomeAccountId function](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/cache/entities/AccountEntity.ts#L255) homeAccountId is being set to empty string, in this case for a confidential client application.

File: lib/msal-common/src/cache/CacheManager.ts (hunk 6 above)
Comment (bgavrilMS) [reply lib/msal-common/src/cache/CacheManager.ts:393]: Agreed @tnorling. I'm just stating the intent: app tokens do not have home_account_id, user tokens do. A `client_credential` request (i.e. no user is involved) must not retrieve a token from the cache which has a `home_account_id`. I will happily learn how to transform this to js/ts code :)

File: lib/msal-common/test/client/ClientCredentialClient.spec.ts [hunk 7]
```diff
@@ -75,6 +79,45 @@ describe("ClientCredentialClient unit tests", () => {
         expect(returnVal.includes(`${AADServerParamKeys.X_MS_LIB_CAPABILITY}=${ThrottlingConstants.X_MS_LIB_CAPABILITY_VALUE}`)).toBe(true);
     });
 
+    it.only("Multiple access tokens would match, but one of them has a Home Account ID of \"\"", async () => {
```
Comment (bgavrilMS) [inline lib/msal-common/test/client/ClientCredentialClient.spec.ts]: nit: add a link to the bug, saying that it is a regression test for it

**Review by bgavrilMS — APPROVED** [review]
LGTM from MSAL logic / E2E test perspective, but please work with @tnorling and @sameerag to get consensus on the "javascriptness"

File: lib/msal-common/src/cache/CacheManager.ts (hunk 6 above)
Comment (sameerag) [reply lib/msal-common/src/cache/CacheManager.ts:393]: Can we stick to "null" or "empty_string" - only one of it - and be consistent? I think the check has to be "homeAccountId == <<expected null or empty_string>> for `clientCredential` flow (where we explicitly set it to that value while caching).

File: lib/msal-common/test/client/ClientCredentialClient.spec.ts (hunk 7 above)
Comment (jasonnutter) [inline lib/msal-common/test/client/ClientCredentialClient.spec.ts]:
```suggestion
    it("Multiple access tokens would match, but one of them has a Home Account ID of \"\"", async () => {
```

Comment (Robbie-Microsoft) [reply lib/msal-common/test/client/ClientCredentialClient.spec.ts]: Yikes! Good catch.

File: lib/msal-common/src/cache/CacheManager.ts (hunk 4 above)
Comment (jasonnutter) [inline lib/msal-common/src/cache/CacheManager.ts]: I would expand on this, with the details from @bgavrilMS comment above, e.g.:

```suggestion
            // homeAccountId can undefined, and we want to filter out cached items that have a homeAccountId of ""
            // because we don't want a client_credential request to return a cached token that has a home_account_id
```

**Comment by jasonnutter** [comment]
> LGTM from MSAL logic / E2E test perspective, but please work with @tnorling and @sameerag to get consensus on the "javascriptness"

Agree on the need to agree on semantics for `""` versus `null` here.

**Review by sameerag — APPROVED** [review]
Synced up offline. The check ensures "empty string" is always matched and "null" isn't, which satisfies the use case here. Approving.

**Comment by Robbie-Microsoft** [comment]
^ Synced with @sameerag and we agreed to leave the check as it is, because we still want to do the comparison even when the homeAccountId is equivalent to empty string. The only time we don't want to do it is when the homeAccountId is null/undefined, and checking for the type accounts for that.
