### PR TITLE
Fix unexpected empty hash errors in popups

### LINKED ISSUE #4573: Hash value cannot be processed because it is empty
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

The user cannot log in after entering email & password. The login popup gets closed and nothing happens.

After getting the error, that does not happen all times, it's possible to login after clicking the login button again (sometimes, it is needed to click it several times). This intermittence makes it difficult to debug.

I basically followed this tutorial: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react

The Azure AD app in portal.azure.com (Microsoft_AAD_RegisteredApps) was configured with Single Page Application redirect URIs having the URI set matching the one configured in the msal configuration (`auth.redirectUri` property)

Screenshot 2022-03-04 at 17 17 12

### Error Message

`
error BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: https://myUrl.com/
`

### Msal Logs

_No response_

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: '930b1k1b-...',
    authority: 'https://login.microsoftonline.com/l2cba3e8-...',
    redirectUri: 'https://myUrl.com/'
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
}
```

### Relevant Code Snippets

```javascript
ClientApp instantiation:
---------------------------------------------------------------------
import { PublicClientApplication } from '@azure/msal-browser';
import { MsalProvider } from '@azure/msal-react';
import { msalConfig } from './config';

const msaInstance = new PublicClientApplication(msalConfig);

ReactDOM.render(
  <React.StrictMode>
    <MsalProvider instance={msaInstance}>
      <App />
    </MsalProvider>
  </React.StrictMode>,
  document.getElementById('root')
);
---------------------------------------------------------------------
Signing in:

const { instance } = useMsal();
const navigate = useNavigate();

let signin = () => {
    return instance
      .loginPopup({
       scopes: ['User.Read'],
      })
      .then((response) => {
          setUserData(response);
          navigate('welcomPagePath');
      })
      .catch((e) => {
        console.log('error', e);
      });
};
```

### Reproduction Steps

1. Enter Microsoft email
2. Enter password

### Expected Behavior

The user can log in

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

_No response_

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by tnorling**
- Fixes race conditions where the response hash in a popup may be cleared between the time the popup returns to the redirectUri and when MSAL.js attempts to read the hash

Fixes #4573

Note: this will not fix issues related to client side routers removing the hash before MSAL.js has a chance to extract it. These will manifest as timeout errors that point back to our error docs which explain this.

- Consolidates popup related code from `PopupUtils`, `PopupHandler` and `PopupClient` into `PopupClient`
- Refactors static functions into member functions on `PopupClient`

Behavior changes are in `monitorPopupForHash` in `PopupClient.ts`, the rest of the PR is merely moving functions between classes.

### CODE REVIEW

File: lib/msal-browser/src/interaction_client/PopupClient.ts [hunk 1]
```diff
@@ -250,4 +259,274 @@ export class PopupClient extends StandardInteractionClient {
...
+
+                if (hash) {
+                    this.logger.verbose("PopupHandler.monitorPopupForHash - found hash in url");
+                    clearInterval(intervalId);
+                    this.cleanPopup(popupWindow);
+    
+                    if (UrlString.hashContainsKnownProperties(hash)) {
+                        resolve(hash);
+                    } else {
+                        reject(BrowserAuthError.createHashDoesNotContainKnownPropertiesError());
```
Comment (jasonnutter) [inline lib/msal-browser/src/interaction_client/PopupClient.ts:342]: Can we add an error log message here with notes about an app router potentially clearing the hash (in addition the text in the error itself)?

File: lib/msal-browser/src/interaction_client/PopupClient.ts [hunk 2]
```diff
@@ -111,19 +129,19 @@ export class PopupClient extends StandardInteractionClient {
...
                 popupName,
                 popupWindowAttributes
             };
-            const popupWindow: Window = interactionHandler.initiateAuthRequest(navigateUrl, popupParameters);
+            const popupWindow: Window = this.initiateAuthRequest(navigateUrl, popupParameters);
             this.eventHandler.emitEvent(EventType.POPUP_OPENED, InteractionType.Popup, {popupWindow}, null);
 
             // Monitor the window for the hash. Return the string value and close the popup when the hash is received. Default timeout is 60 seconds.
-            const hash = await interactionHandler.monitorPopupForHash(popupWindow);
+            const hash = await this.monitorPopupForHash(popupWindow, );
```
Comment (jasonnutter) [inline lib/msal-browser/src/interaction_client/PopupClient.ts]:
```suggestion
            const hash = await this.monitorPopupForHash(popupWindow);
```

File: lib/msal-browser/src/interaction_client/PopupClient.ts (hunk 1 above)
Comment (tnorling) [reply lib/msal-browser/src/interaction_client/PopupClient.ts:342]: Done. Also added these errors to the error docs and included a link to the docs in the error message.

File: change/@azure-msal-browser-7c285756-a14a-401d-a5cb-ad75ef9f9b5b.json [hunk 3]
```diff
@@ -0,0 +1,6 @@
+{
+  "type": "patch",
+  "packageName": "@azure/msal-browser",
+  "email": "thomas.norling@microsoft.com",
+  "dependentChangeType": "patch"
+}
```
Comment (jasonnutter) [inline change/@azure-msal-browser-7c285756-a14a-401d-a5cb-ad75ef9f9b5b.json]: Why two of these?

Comment (tnorling) [reply change/@azure-msal-browser-7c285756-a14a-401d-a5cb-ad75ef9f9b5b.json]: Good question...

Comment (tnorling) [reply change/@azure-msal-browser-7c285756-a14a-401d-a5cb-ad75ef9f9b5b.json]: Removed

File: lib/msal-browser/docs/errors.md [hunk 4]
```diff
@@ -159,6 +161,8 @@ This error can be thrown when calling `ssoSilent`, `acquireTokenSilent`, `acquir
 1. You are being throttled by your identity provider
 1. Your identity provider did not redirect back to your `redirectUri`.
 
+Note: If you are using a router, please make sure it does not strip the hash or auto-redirect while MSAL token acquisition is in progress. When possible it's best if your `redirectUri` page does not invoke the router at all.
```
Comment (jasonnutter) [inline lib/msal-browser/docs/errors.md]:
```suggestion
**Important**: If your application uses a router library (e.g. React Router, Angular Router), please make sure it does not strip the hash or auto-redirect while MSAL token acquisition is in progress. If possible, it is best if your `redirectUri` page does not invoke the router at all.
```

File: lib/msal-browser/docs/errors.md [hunk 5]
```diff
@@ -224,6 +228,25 @@ const msalConfig = {
 };
 ```
 
+### hash_empty_error
+
+**Error Messages**:
+
+- Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash.
```
Comment (jasonnutter) [inline lib/msal-browser/docs/errors.md]:
```suggestion
> Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash.
```

File: lib/msal-browser/docs/errors.md [hunk 6]
```diff
@@ -224,6 +228,25 @@ const msalConfig = {
...
+
+This error occurs when the page you use as your redirectUri is removing the hash, or auto-redirecting to another page. This most commonly happens when the application implements a router which navigates to another route, dropping the hash.
+
+To resolve this error we recommend using a dedicated redirectUri page which is not subject to the router. For silent and popup calls it's best to use a blank page. If this is not possible please make sure the router does not navigate while MSAL token acquisition is in progress. You can do this by detecting if your application is loaded in an iframe for silent calls, in a popup for popup calls or by awaiting `handleRedirectPromise` for redirect calls.
+
+### hash_does_not_contain_known_properties
+
+**Error Messages**:
+
+- Hash does not contain known properites. Please verify that your redirectUri is not changing the hash.
```
Comment (jasonnutter) [inline lib/msal-browser/docs/errors.md]:
```suggestion
> Hash does not contain known properites. Please verify that your redirectUri is not changing the hash.
```

**Comment by jasonnutter** [comment]
#4800 shoudl fix the angular 14 samples.

**Review by jasonnutter — APPROVED** [review]

**Review by sameerag — APPROVED** [review]
Lgtm. Like the re-arrangement and fewer files.
