### PR TITLE
Fix authority endpoint version for B2C authorities

### LINKED ISSUE #6340: The scope provided in the request is not supported
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.1

### Public or Confidential Client?

Public

### Description

After updating to Angular 15 and MSAL 3.0.1, we are getting an error when trying to authenticate.

Since nothing in this regard is documented in the Upgrade Guide, I would not expect any change to be required in this regard or any deprecations.

### Error Message

```
invalid_request: AADB2C90012: The scope '<our-scopes> openid profile offline_access' provided in request is not supported.
```

### Msal Logs

_No response_

### MSAL Configuration

```javascript
new PublicClientApplication({
    auth: {
      clientId: environment.AzureClientId,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: "/",
      postLogoutRedirectUri: "/",
      knownAuthorities: [`${environment.AzureB2CName}.b2clogin.com`],
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Warning,
        piiLoggingEnabled: false,
      },
    },
  });
```

### Relevant Code Snippets

```javascript
-
```

### Reproduction Steps

1. Start the login flow
2. The page blanks out and this error appears in the console

### Expected Behavior

Nothing should error out, because there are no deprecations in the [Upgrade Guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-v3-upgrade-guide.md)

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Regression

@azure/msal-browser 2.x

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by hectormmg**
This PR:

- Fixes a bug where B2C authority URLs were not having /v2 appended because they were not in the list of known Microsoft authorities

### CODE REVIEW

File: lib/msal-common/src/authority/Authority.ts [hunk 1]
```diff
@@ -356,7 +356,8 @@ export class Authority {
         const canonicalAuthorityHost = this.hostnameAndPort;
         if (
             this.authorityType === AuthorityType.Adfs ||
-            !this.isAliasOfKnownMicrosoftAuthority(canonicalAuthorityHost)
+            (this.protocolMode !== ProtocolMode.AAD &&
```
Comment (hectormmg) [inline lib/msal-common/src/authority/Authority.ts:359]: Note: This is an immediate solution, but it may be a good idea to add a way to either detect B2C authorities or indicate the authority is B2C in some way so B2C can be used in OIDC mode.

**Review by konstantin-msft — APPROVED** [review]

**Review by tnorling — APPROVED** [review]

**Comment by tnorling** [comment]
Tests?

**Comment by hectormmg** [comment]
@tnorling on it, will update the PR a bit later.

File: lib/msal-common/src/authority/Authority.ts (hunk 1 above)
Comment (sameerag) [reply lib/msal-common/src/authority/Authority.ts:359]: We are not detecting CIAM so detecting B2C should be okay. The decision not to was made when we wanted to be IDP agnostic which is no longer true in many cases.

**Review by sameerag — APPROVED** [review]
