### PR TITLE
sanitize client credentials request against oidc scopes

### LINKED ISSUE #4939: Does msal-node support Client credentials flow for Azure AD B2C
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.10.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Description

Recently, Client credentials flow for Azure AD B2C moved to public preview. Works okay when you make an HTTP call, but it seems not to work when using msal-node.  

### Error Message

ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: `https://tenant-name.b2clogin.com/tenant-name.onmicrosoft.com/policy-name/oauth2/v2.0/token`

### Msal Logs

[Mon, 27 Jun 2022 10:45:33 GMT] : @azure/msal-node@1.10.0 : Info - acquireTokenByClientCredential called
[Mon, 27 Jun 2022 10:45:33 GMT] : @azure/msal-node@1.10.0 : Verbose - initializeRequestScopes called
Client credentials app listening accessToken = 3000
[Mon, 27 Jun 2022 10:45:33 GMT] : [40fa6b2a-7e02-4aa5-a576-cc3b9306f8af] : @azure/msal-node@1.10.0 : Verbose - buildOauthClientConfiguration called
[Mon, 27 Jun 2022 10:45:33 GMT] : [40fa6b2a-7e02-4aa5-a576-cc3b9306f8af] : @azure/msal-node@1.10.0 : Verbose - building oauth client configuration with the authority: https://tenant-name.b2clogin.com/tenant-name.onmicrosoft.com/policy-name
[Mon, 27 Jun 2022 10:45:33 GMT] : [40fa6b2a-7e02-4aa5-a576-cc3b9306f8af] : @azure/msal-node@1.10.0 : Verbose - createAuthority called[Mon, 27 Jun 2022 10:45:35 GMT] : [40fa6b2a-7e02-4aa5-a576-cc3b9306f8af] : @azure/msal-node@1.10.0 : Verbose - Client credential client created

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        clientId: APP_CLIENT_ID,
        authority: POLICY_AUTHORITY in the form of https://tenant-name.b2clogin.com/tenant-name.onmicrosoft.com/policy-name,
        clientSecret: APP_CLIENT_SECRET,
        knownAuthorities: [tenant-name.b2clogin.com]
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Verbose,
        }
    }
   };
```

### Relevant Code Snippets

```javascript
const msalConfig = {
    auth: {
        clientId: APP_CLIENT_ID,
        authority: POLICY_AUTHORITY in the form of https://tenant-name.b2clogin.com/tenant-name.onmicrosoft.com/policy-name,
        clientSecret: APP_CLIENT_SECRET,
        knownAuthorities: [tenant-name.b2clogin.com]
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Verbose,
        }
    }
   }; 

// With client credentials flows permissions need to be granted in the portal by a tenant administrator. 
// The scope is always in the format '<resource>/.default'.
const tokenRequest = {
    //Use this scope to receive an access token you use to access resources protected by Azure AD B2C itself. 
    scopes: ['https://tenant-name.onmicrosoft.com/client-credentials-api/.default']
};
//Create msal application object
const cca = new msal.ConfidentialClientApplication(msalConfig);

cca.acquireTokenByClientCredential(tokenRequest).then((authResponse)=>{
    console.log('accessToke: ' + authResponse.accessToken)

}).catch((error)=>{
    console.log("\nErrorAtLogin: \n" + error);
});
```

### Reproduction Steps

1. Follow the steps in [Register Azure AD B2C web API](https://docs.microsoft.com/azure/active-directory-b2c/client-credentials-grant-flow?pivots=b2c-user-flow#step-1-register-the-web-api-app) to register web api
2. Follow the steps in [Register a web app](https://docs.microsoft.com/azure/active-directory-b2c/client-credentials-grant-flow?pivots=b2c-user-flow#step-2-register-an-application) to register the web app
3. Use the code snippet in **Relevant Code Snippets** section above to request an access token. Make sure you replace the client ID, client secret, Azure AD B2C policy and Azure AD B2C tenant name with your own values. 

### Expected Behavior

I should have received an access token for my web app. The web app can then access resources (in this case the web API) as needed. 

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

None (Server)

### Regression

It didn't work

### Source

Internal (Microsoft)

### PR DESCRIPTION
**Pull request by derisen**
Currently default OIDC scopes are attached to all token requests in all clients. This breaks token requests via client credentials grant against B2C (apparently AAD ignores these scopes, hence this issue did not raise earlier). This PR removes the OIDC scopes added by the library from the `validRequest` object in msal-node's `acquireTokenByClientCredential` API.

Fixes #4939 

cc @Robbie-Microsoft freel free to close this if another PR is to take precedence over

### CODE REVIEW

File: lib/msal-node/src/client/ConfidentialClientApplication.ts [hunk 1]
```diff
@@ -69,17 +70,23 @@ export class ConfidentialClientApplication extends ClientApplication implements
...
             ...request,
             ...await this.initializeBaseRequest(request),
             clientAssertion
         };
 
+        // a valid client credentials request should not contain delegated permissions
+        const validRequest: CommonClientCredentialRequest = {
+            ...originalRequest,
+            scopes: originalRequest.scopes.filter(scope => !OIDC_DEFAULT_SCOPES.includes(scope))
+        };
```
Comment (jasonnutter) [inline lib/msal-node/src/client/ConfidentialClientApplication.ts:98]: This could be done in one step if you put the result of `await this.initializeBaseRequest(request)` into a variable.

**Comment by jasonnutter** [comment]
I would personally prefer we didn't do this, and instead had B2C gracefully handle receiving requests with those scopes (that way apps dont necessarily need to update to the latest version).

**Comment by derisen** [comment]
> I would personally prefer we didn't do this, and instead had B2C gracefully handle receiving requests with those scopes (that way apps dont necessarily need to update to the latest version).

Makes sense -I wasn't aware of the discussion prior so converted to draft for now. Happy to close it depending on the outcome.

File: lib/msal-node/src/client/ConfidentialClientApplication.ts (hunk 1 above)
Comment (derisen) [reply lib/msal-node/src/client/ConfidentialClientApplication.ts:98]: I was also attempting to remove any oidc scopes added by the end developer, but perhaps that was unnecessary.

**Review by bgavrilMS — APPROVED** [review]
LGTM, thanks @derisen

**Review by bgavrilMS — APPROVED** [review]

**Review by Robbie-Microsoft — APPROVED** [review]

**Review by jennyf19 — APPROVED** [review]

**Review by bmahall — APPROVED** [review]
LGTM
