### PR TITLE
Gracefully handle old interaction format

### LINKED ISSUE #7717: msal-browser crashes with SyntaxError in version v4.10.0
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

v4.10.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

3.0.9

### Public or Confidential Client?

Public

### Description

msal-browser started to crash with SyntaxError in version v4.10.0. I tried to update to v4.11.0 but it has the same issue. The issue seems to have been introduced in this commit:
https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/972b9938c6c545da1687a3e1eb89188395161fcc

This seems to happen to users that have an expired session.

### Error Message

```
SyntaxError: Unexpected token 'b', "fb11733e-6b"... is not valid JSON
  at JSON.parse(<anonymous>)
  at BrowserCacheManager.getInteractionInProgress(../../node_modules/@azure/msal-browser/dist/cache/BrowserCacheManager.mjs:759:29)
  at BrowserCacheManager.setInteractionInProgress(../../node_modules/@azure/msal-browser/dist/cache/BrowserCacheManager.mjs:774:18)
  at BrowserCacheManager.resetRequestCache(../../node_modules/@azure/msal-browser/dist/cache/BrowserCacheManager.mjs:693:14)
  at StandardController.acquireTokenRedirect(../../node_modules/@azure/msal-browser/dist/controllers/StandardController.mjs:395:33)
  at StandardController.loginRedirect(../../node_modules/@azure/msal-browser/dist/controllers/StandardController.mjs:1156:21)
  at PublicClientApplication.loginRedirect(../../node_modules/@azure/msal-browser/dist/app/PublicClientApplication.mjs:231:32)
  at login(../../node_modules/@azure/msal-react/dist/hooks/useMsalAuthentication.js:65:22)
```

### MSAL Logs

_No response_

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    auth: {
      clientId: msalClientId,
      authority,
      knownAuthorities: b2cLoginDomain
      redirectUri,
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false,
      secureCookies: true,
    },
  }
}
```

### Relevant Code Snippets

```javascript
This is the code we are calling in our application:

import { useMsalAuthentication } from "@azure/msal-react";

const { login } = useMsalAuthentication(InteractionType.Redirect, authRequest);
await login(InteractionType.Redirect, request);
```

### Reproduction Steps

See the code example.

### Expected Behavior

MSAL library shouldn't throw an error.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Regression

msal-browser v4.8.0 (maybe also msal-browser v4.9.x)

### PR DESCRIPTION
**Pull request by konstantin-msft**
- Gracefully handle old interaction format

### CODE REVIEW

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 1]
```diff
@@ -1203,7 +1203,15 @@ export class BrowserCacheManager extends CacheManager {
     } | null {
         const key = `${Constants.CACHE_PREFIX}.${TemporaryCacheKeys.INTERACTION_STATUS_KEY}`;
         const value = this.getTemporaryCache(key, false);
-        return value ? JSON.parse(value) : null;
+        try {
+            return value ? JSON.parse(value) : null;
+        } catch (e) {
+            // Remove interaction and other temp keys when redirect begins on version <4.10.0 and completes on 4.10.0+
```
Comment (peterzenz) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: This comment isn't really accurate here.  You're not checking versions explicitly, you're really saying if I can't parse the old state then let's clean it up for a subsequent go.  We can note for historic reasons that there we a break in 4.10.0 that needs this.

**Review by peterzenz — DISMISSED** [review]

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 2]
```diff
@@ -1203,7 +1203,15 @@ export class BrowserCacheManager extends CacheManager {
...
+            this.removeTemporaryItem(key);
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:1214]: We should add a warning log here

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 3]
```diff
@@ -1203,7 +1203,15 @@ export class BrowserCacheManager extends CacheManager {
...
+            this.resetRequestCache();
+            return null;
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:1217]: Is the auth code still in the url if I get into this state?

Comment (konstantin-msft) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:1217]: Good catch. Added hash clean up as well

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 2 above)
Comment (konstantin-msft) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:1214]: done

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 1 above)
Comment (konstantin-msft) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Updated the comment

**Review by tnorling — APPROVED** [review]

**Review by jo-arroyo — APPROVED** [review]

**Review by peterzenz — APPROVED** [review]
