### PR TITLE
Fix bug with activeAccount when two accounts have same local account id

### LINKED ISSUE #4601: Incorrect active account selection when there are multiple same accounts but with different authority
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.1.1

### Description

We've got multiple web applications using Azure B2C SSO and 2 login flows: SingInAndUp and JustSignIn. Therefore there are 2 accounts listed when calling ``getAllAccounts()``. Here's our example
```json
[
  {
    "homeAccountId": "590cd179-49b3-4266-828f-c0b3955a66ae-b2c_1_justsignin.81ff9595-acc4-480c-887d-cc1c10bd31e0",
    "environment": "rapidplanstaging.b2clogin.com",
    "tenantId": "",
    "username": "john.doe@invarion.com",
    "localAccountId": "590cd179-49b3-4266-828f-c0b3955a66ae",
    "name": "John Doe",
    "idTokenClaims": {
      "exp": 1647009520,
      "nbf": 1647005920,
      "ver": "1.0",
      "iss": "https://rapidplanstaging.b2clogin.com/81ff9595-acc4-480c-887d-cc1c10bd31e0/v2.0/",
      "sub": "590cd179-49b3-4266-828f-c0b3955a66ae",
      "aud": "eb3169e8-ff98-43f9-b02c-c91ef9006ab8",
      "nonce": "3c20ead3-986e-41ce-93d5-6a2cacc0e0d0",
      "iat": 1647005920,
      "auth_time": 1646923676,
      "oid": "590cd179-49b3-4266-828f-c0b3955a66ae",
      "name": "John Doe",
      "given_name": "John",
      "extension_InvarionId": "5afb1a56-758e-4f25-9580-b744ac7a5676",
      "family_name": "Doe",
      "emails": [
        "john.doe@invarion.com"
      ],
      "tfp": "B2C_1_JustSignIn",
      "at_hash": "ma7IEet5b2I7xs2SDpqRDw"
    }
  },
  {
    "homeAccountId": "590cd179-49b3-4266-828f-c0b3955a66ae-b2c_1_singinandup.81ff9595-acc4-480c-887d-cc1c10bd31e0",
    "environment": "rapidplanstaging.b2clogin.com",
    "tenantId": "",
    "username": "john.doe@invarion.com",
    "localAccountId": "590cd179-49b3-4266-828f-c0b3955a66ae",
    "name": "John Doe",
    "idTokenClaims": {
      "exp": 1647247524,
      "nbf": 1647243924,
      "ver": "1.0",
      "iss": "https://rapidplanstaging.b2clogin.com/81ff9595-acc4-480c-887d-cc1c10bd31e0/v2.0/",
      "sub": "590cd179-49b3-4266-828f-c0b3955a66ae",
      "aud": "eb3169e8-ff98-43f9-b02c-c91ef9006ab8",
      "nonce": "95b4c656-9d39-413e-b9f0-357b74e96848",
      "iat": 1647243924,
      "auth_time": 1647243923,
      "oid": "590cd179-49b3-4266-828f-c0b3955a66ae",
      "given_name": "John",
      "family_name": "Doe",
      "extension_InvarionId": "5afb1a56-758e-4f25-9580-b744ac7a5676",
      "name": "John Doe",
      "extension_CompanyId": "fa11a1d9-f8b0-4d04-a16c-29118cfa660f",
      "emails": [
        "john.doe@invarion.com"
      ],
      "tfp": "B2C_1_SingInAndUp",
      "at_hash": "428EFEgC_luMkcIbZZVNSA"
    }
  }
]
```
As you can see they have identical ``localAccountId`` which is picked up by ``getAccountInfoByFilter`` ([code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/305422535d93dfe5ff4fb1246eb5e9dde939b985/lib/msal-browser/src/cache/BrowserCacheManager.ts#L429)) and picks up the first record which is incorrect when web app wants to use ``B2C_1_SingInAndUp`` flow.
Then it causes error during token refresh when calling ``POST: https://rapidplanstaging.b2clogin.com/rapidplanstaging.onmicrosoft.com/b2c_1_singinandup/oauth2/v2.0/token`` with message: "AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_SingInAndUp and Expected Value : B2C_1_JustSignIn" which, in turn, causes infinite loop between web app and azure login screen.

### Error Message

AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1_SingInAndUp and Expected Value : B2C_1_JustSignIn

core.js:6210 ERROR Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (AuthError.js:27:1)
    at new BrowserAuthError (BrowserAuthError.js:169:1)
    at Function.push.vgJv.BrowserAuthError.createInteractionInProgressError (BrowserAuthError.js:236:1)
    at BrowserCacheManager.push.YBFq.BrowserCacheManager.setInteractionInProgress (BrowserCacheManager.js:813:39)
    at PublicClientApplication.push.nFfJ.ClientApplication.preflightInteractiveRequest (ClientApplication.js:540:1)
    at PublicClientApplication.push.nFfJ.ClientApplication.preflightBrowserEnvironmentCheck (ClientApplication.js:527:1)
    at PublicClientApplication.<anonymous> (ClientApplication.js:156:1)
    at step (_tslib.js:75:1)
    at Object.next (_tslib.js:56:45)
    at _tslib.js:49:1
    at resolvePromise (zone-evergreen.js:1213:1)
    at new ZoneAwarePromise (zone-evergreen.js:1390:1)
    at __awaiter (_tslib.js:45:1)
    at PublicClientApplication.push.nFfJ.ClientApplication.acquireTokenRedirect (ClientApplication.js:150:25)
    at MsalService.acquireTokenRedirect (azure-msal-angular.js:42:20)
    at MsalInterceptor.acquireTokenInteractively (azure-msal-angular.js:390:1)
    at CatchSubscriber.selector (azure-msal-angular.js:362:1)
    at CatchSubscriber.error (catchError.js:27:1)
    at subscribeToPromise.js:8:6
    at ZoneDelegate.invoke (zone-evergreen.js:372:1)

### Msal Logs

MSAL Logging:  [Mon, 14 Mar 2022 08:48:44 GMT] : @azure/msal-angular@2.1.1 : Info - Interceptor - 1 scopes found for endpoint
MSAL Logging:  [Mon, 14 Mar 2022 08:48:47 GMT] : @azure/msal-angular@2.1.1 : Error - Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.

### MSAL Configuration

```javascript
{
  "auth": {
    "clientId": "eb3169e8-ff98-43f9-b02c-c91ef9006ab8",
    "authority": "https://RapidPlanStaging.b2clogin.com/RapidPlanStaging.onmicrosoft.com/B2C_1_SingInAndUp",
    "knownAuthorities": [
      "https://RapidPlanStaging.b2clogin.com/RapidPlanStaging.onmicrosoft.com/B2C_1_SingInAndUp",
      "https://RapidPlanStaging.b2clogin.com/RapidPlanStaging.onmicrosoft.com/B2C_1_SingInAndUp"
    ],
    "redirectUri": "http://localhost:4200/login-redirect",
    "postLogoutRedirectUri": "http://localhost:4200/logged-out",
    "navigateToLoginRequestUrl": true
  },
  "cache": {
    "cacheLocation": "localStorage",
    "storeAuthStateInCookie": false
  },
  "system": {
    "loggerOptions": {
      "piiLoggingEnabled": true,
      "logLevel": 0
    }
  }
}
```

### Relevant Code Snippets

```javascript
Necessary information has been provided in the issue description
```

### Reproduction Steps

1. Have 2 web apps requiring different user flows
2. Login on the first one
3. Login on the second one
4. The 2nd web app would pick up the first account as active one

### Expected Behavior

The library should respect required authority provided in the configuration when picking up active account.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

_No response_

### Source

External (Customer)

### LINKED ISSUE #4915: Multiple B2C policies used in the one app
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.2

### Description

Hi, 

I've been working on an Angular/B2C app based on the sample https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-b2c-sample. 

I have created a number of custom B2C policies, but I think this same issue would occur with the built in B2C policies as well. I'm hoping to sign the user in via a B2C sign in policy, once they're logged in I want to provide links to other policies to change password and edit profile. 

I notice on line 59 of the sample app.component.ts: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts it appears the user is logged out after completing the edit profile flow and returning to the app. Ideally I want to keep the user signed in after completing these flows, and let them continue as normal, however, if they are not logged out there will be a new set of tokens issued from the secondary policy, which causes problems with acquireTokenSilent in MSALInterceptor when calling backend APIs, as the wrong tokens can _sometimes_ be used. 

I've experimented with trying to set the account from the sign in flow as the 'active' account using setActiveAccount, however, this does not seem to work as, I'm guessing, the 'accountKey' used to reference the active account will be the same for both sets of tokens, they just have a different authority.

I can see a couple of options:

1. Use a single B2C custom policy, pass in an extraQueryParameter when calling for password change or edit profile - and use the query parameter to jump to the appropriate orchestration step. I haven't completely built this option, but it seems like it will work and the user will have only a single set of tokens after completing each flow.
2. Develop a custom version of MSALInterceptor and always pass in the tokens from the sign in flow - this doesn't seem like a great option and I can imagine dealing with multiple sets of tokens could cause other problems as well.

Is there a better to way to use multiple policies without needing to sign the user out? 

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
     auth: {
         clientId: environment.clientId, // This is the ONLY mandatory field that you need to supply.
         authority: b2cPolicies.authorities.signUpSignIn.authority, // Defaults to "https://login.microsoftonline.com/common"
         knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
         redirectUri: '/', // Points to window.location.origin. You must register this URI on Azure portal/App Registration.
         postLogoutRedirectUri: environment.host + "#/signout"
     },
     cache: {
         cacheLocation: BrowserCacheLocation.SessionStorage, // Configures cache location. use "sessionStorage" to log user out when closing window.
         storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge
     }
}
```

### Relevant Code Snippets

```javascript
/*This is the section and comment from the sample app.component.ts which logs the user out after completing edit profile (lines 54-62)*/
/**
         * For the purpose of setting an active account for UI update, we want to consider only the auth response resulting
         * from SUSI flow. "tfp" claim in the id token tells us the policy (NOTE: legacy policies may use "acr" instead of "tfp").
         * To learn more about B2C tokens, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview
         */
        if (payload.idTokenClaims['tfp'] === b2cPolicies.names.editProfile) {
          window.alert('Profile has been updated successfully. \nPlease sign-in again.');
          return this.logout();
        }

/*This is the section in MSALInterceptor where the wrong tokens can sometimes be used (lines 50-62 of https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.interceptor.ts*/

 // Sets account as active account or first account
        let account: AccountInfo;
        if (!!this.authService.instance.getActiveAccount()) {
            this.authService.getLogger().verbose("Interceptor - active account selected");
            account = this.authService.instance.getActiveAccount();
        } else {
            this.authService.getLogger().verbose("Interceptor - no active account, fallback to first account");
            account = this.authService.instance.getAllAccounts()[0];
        }

        const authRequest = typeof this.msalInterceptorConfig.authRequest === "function"
            ? this.msalInterceptorConfig.authRequest(this.authService, req, { account: account })
            : { ...this.msalInterceptorConfig.authRequest, account };
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

### PR DESCRIPTION
**Pull request by shylasummers**
Currently, in the browser, if there are two accounts with the same local account id but different home account ids (say, the same account logged in with two different sign in flows in a B2C app), the active account may not be set to the correct one. 

This PR changes the active-account object in the cache to contain both localAccountId and homeAccountId (instead of just localAccountId). getActiveAccount() and setActiveAccount() are also changed to use the new object.

Fixes #4601

### CODE REVIEW

File: lib/msal-common/src/account/AccountInfo.ts [hunk 1]
```diff
@@ -26,3 +26,8 @@ export type AccountInfo = {
     idTokenClaims?: TokenClaims & { [key: string]: string | number | string[] | object | undefined | unknown };
     nativeAccountId?: string;
 };
+
+export type ActiveAccountIds = {
+    homeAccountId: string;
+    localAccountId: string;
+};
```
Comment (jasonnutter) [inline lib/msal-common/src/account/AccountInfo.ts]: FYI could also be:

```suggestion
export type ActiveAccountIds = Pick<AccountInfo, "homeAccountId" | "localAccountId">;
```

File: lib/msal-common/src/utils/Constants.ts [hunk 2]
```diff
@@ -81,7 +81,8 @@ export enum PersistentCacheKeys {
     ADAL_ID_TOKEN = "adal.idtoken",
     ERROR = "error",
     ERROR_DESC = "error.description",
-    ACTIVE_ACCOUNT = "active-account"
+    ACTIVE_ACCOUNT = "active-account",
+    ACTIVE_ACCOUNT_NEW = "active-account-new" //new cache entry for active_account for a more robust version for browser
```
Comment (jasonnutter) [inline lib/msal-common/src/utils/Constants.ts]: Instead of "new", can we describe it? For example:

```suggestion
    ACTIVE_ACCOUNT_HOME_LOCAL_IDS = "active-account-home-local-ids" //new cache entry for active_account for a more robust version for browser
```

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 3]
```diff
@@ -400,26 +400,60 @@ export class BrowserCacheManager extends CacheManager {
      * Gets the active account
      */
     getActiveAccount(): AccountInfo | null {
-        const activeAccountIdKey = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
-        const activeAccountId = this.browserStorage.getItem(activeAccountIdKey);
-        if (!activeAccountId) {
+        const activeAccountKeyNew = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT_NEW);
+        const activeAccountValueNew = this.getItem(activeAccountKeyNew);
+        if (!activeAccountValueNew) {
```
Comment (jasonnutter) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: A comment would be helpful here to describe that were first looking for an account cached with the old key.

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 4]
```diff
@@ -400,26 +400,60 @@ export class BrowserCacheManager extends CacheManager {
      * Gets the active account
      */
     getActiveAccount(): AccountInfo | null {
-        const activeAccountIdKey = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
-        const activeAccountId = this.browserStorage.getItem(activeAccountIdKey);
-        if (!activeAccountId) {
+        const activeAccountKeyNew = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT_NEW);
+        const activeAccountValueNew = this.getItem(activeAccountKeyNew);
```
Comment (jasonnutter) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: Same comment here about "new". Maybe this?

```suggestion
        const activeAccountByLocalHomeAccountIds = this.getItem(activeAccountKeyNew);
```

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 5]
```diff
@@ -400,26 +400,60 @@ export class BrowserCacheManager extends CacheManager {
...
+        if (!activeAccountValueNew) {
+            const activeAccountKeyOld = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
```
Comment (jasonnutter) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]:
```suggestion
            const activeAccountByLocalId = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
```

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 6]
```diff
@@ -400,26 +400,60 @@ export class BrowserCacheManager extends CacheManager {
...
+            {
+                this.setActiveAccount(activeAccount);
+                this.browserStorage.removeItem(activeAccountKeyOld);
+                return activeAccount;
+            }
+            return null;
+        }
+        else
+        {
+            const activeAccountValueObj = this.validateAndParseJson(activeAccountValueNew);
```
Comment (jasonnutter) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]:
```suggestion
            const activeAccountValueObj = this.validateAndParseJson(activeAccountValueNew) as AccountInfo;
```

Then you shouldn't need `hasOwnProperty`, square bracket notation, below.

File: lib/msal-common/src/account/AccountInfo.ts (hunk 1 above)
Comment (jasonnutter) [reply lib/msal-common/src/account/AccountInfo.ts]: And I would suggest being a little more explicit, maybe `ActiveAccountIdKeys` or `ActiveAccountIdProperties`?

**Comment by jasonnutter** [comment]
A few comments, otherwise looks good, thanks for the tests!

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 7]
```diff
@@ -400,26 +400,60 @@ export class BrowserCacheManager extends CacheManager {
...
+            const activeAccountValueOld = this.getItem(activeAccountKeyOld);
+            if(!activeAccountValueOld)
+            {
+                return null;
+            }
+            const activeAccount = this.getAccountInfoByFilter({localAccountId: activeAccountValueOld})[0] || null;
+            if(activeAccount)
+            {
+                this.setActiveAccount(activeAccount);
+                this.browserStorage.removeItem(activeAccountKeyOld);
```
Comment (jasonnutter) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: I don't think removing the old entries is a good idea, as then the active account value wouldn't be present for old versions if an application upgrades and then downgrades. Instead, please always set both values, but prioritize the new version, if present.

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 8]
```diff
@@ -400,26 +400,60 @@ export class BrowserCacheManager extends CacheManager {
...
     /**
      * Sets the active account's localAccountId in cache
      * @param account 
      */
     setActiveAccount(account: AccountInfo | null): void {
-        const activeAccountIdKey = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
+        const activeAccountKey = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT_NEW);
         if (account) {
             this.logger.verbose("setActiveAccount: Active account set");
-            this.browserStorage.setItem(activeAccountIdKey, account.localAccountId);
```
Comment (jasonnutter) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts:420]: Per comment above, keep this (instead of deleting on line 452), so that both the "old" and "new" values are in teh cache (and kept in sync) to ensure backwards and forwards compatibility.

File: change/@azure-msal-browser-587c8bb4-93ee-4c52-b182-a16394d24251.json [hunk 9]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "Fix bug with activeAccount when two accounts have same local account id #5004",
+  "packageName": "@azure/msal-browser",
+  "email": "shylasummers@users.noreply.github.com",
```
Comment (shylasummers) [inline change/@azure-msal-browser-587c8bb4-93ee-4c52-b182-a16394d24251.json]:
```suggestion
  "email": "t-ssummers@microsoft.com",
```

File: change/@azure-msal-common-11d08fd3-32cd-4c87-b5b3-62a3537acc03.json [hunk 10]
```diff
@@ -0,0 +1,7 @@
+{
+  "type": "patch",
+  "comment": "Fix bug with activeAccount when two accounts have same local account id #5004",
+  "packageName": "@azure/msal-common",
+  "email": "shylasummers@users.noreply.github.com",
```
Comment (shylasummers) [inline change/@azure-msal-common-11d08fd3-32cd-4c87-b5b3-62a3537acc03.json]:
```suggestion
  "email": "t-ssummers@microsoft.com",
```

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 8 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts:420]: Updated with all of these comments! Thank you

File: lib/msal-common/src/client/AuthorizationCodeClient.ts [hunk 11]
```diff
@@ -125,7 +125,7 @@ export class AuthorizationCodeClient extends BaseClient {
         }
         const queryString = this.createLogoutUrlQueryString(logoutRequest);
 
-        // Construct logout URI.
+        // Construct logout URI
```
Comment (peterzenz) [inline lib/msal-common/src/client/AuthorizationCodeClient.ts]: @hectormmg are you using this branch just to test out your CI pipeline changes?  If so, maybe make a separate PR just for that?

**Review by peterzenz — APPROVED** [review]

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 12]
```diff
@@ -400,26 +400,54 @@ export class BrowserCacheManager extends CacheManager {
...
-        const activeAccountIdKey = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
-        const activeAccountId = this.browserStorage.getItem(activeAccountIdKey);
-        if (!activeAccountId) {
+        const activeAccountKeyHomeLocalIds = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT_HOME_LOCAL_IDS);
+        const activeAccountValueHomeLocalIds = this.getItem(activeAccountKeyHomeLocalIds);
+        if (!activeAccountValueHomeLocalIds) { 
+            // if new active account cache type isn't found, it's an old version, so look for that instead
+            const activeAccountKeyLocal = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
+            const activeAccountValueLocal = this.getItem(activeAccountKeyLocal);
+            if(!activeAccountValueLocal)
```
Comment (derisen) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: @shylasummers nit: JS code in general (as well as this code base) follows the [K&R style](https://en.wikipedia.org/wiki/Indentation_style#K&R_style), can we do the same here and elsewhere?

```javascript
            if (!activeAccountValueLocal) {
                 // ...
            }
```

File: lib/msal-common/src/client/AuthorizationCodeClient.ts (hunk 11 above)
Comment (hectormmg) [reply lib/msal-common/src/client/AuthorizationCodeClient.ts]: @shylasummers and I were looking at the CI pipeline issue together since we first realized it was there when she created this PR. We pulled my branch into this one to see if the CI fixes were actually working, but next time I'll make sure it's on a completely separate branch.

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 12 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Fixed! Thanks for letting me know

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 13]
```diff
@@ -400,26 +400,49 @@ export class BrowserCacheManager extends CacheManager {
...
+                return null;
+            }
+            const activeAccount = this.getAccountInfoByFilter({localAccountId: activeAccountValueLocal})[0] || null;
+            if(activeAccount) {
+                this.setActiveAccount(activeAccount); // update old active account cache type to new type
+                return activeAccount;
+            }
+            return null;
+        } else {
+            const activeAccountValueObj = this.validateAndParseJson(activeAccountValueHomeLocalIds) as AccountInfo;
```
Comment (derisen) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: Seems like the else clause is superfluous here, since you are doing early return above

**Review by derisen — APPROVED** [review]
Looks pretty good to me, and seems to resolve the multiple accounts issue in B2C scenarios -thanks @shylasummers

**Review by Alino — APPROVED** [review]

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 13 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Fixed! Thanks for pointing that out.

File: lib/msal-common/src/account/AccountInfo.ts [hunk 14]
```diff
@@ -26,3 +26,8 @@ export type AccountInfo = {
     idTokenClaims?: TokenClaims & { [key: string]: string | number | string[] | object | undefined | unknown };
     nativeAccountId?: string;
 };
+
+export type ActiveAccountHomeLocalIds = {
```
Comment (tnorling) [inline lib/msal-common/src/account/AccountInfo.ts]:
```suggestion
export type ActiveAccountFilters = {
```

Comment (tnorling) [reply lib/msal-common/src/account/AccountInfo.ts]: Something a bit more generic in case we want to add additional filter properties in the future

File: lib/msal-common/src/utils/Constants.ts [hunk 15]
```diff
@@ -81,7 +81,8 @@ export enum PersistentCacheKeys {
     ADAL_ID_TOKEN = "adal.idtoken",
     ERROR = "error",
     ERROR_DESC = "error.description",
-    ACTIVE_ACCOUNT = "active-account"
+    ACTIVE_ACCOUNT = "active-account",
+    ACTIVE_ACCOUNT_HOME_LOCAL_IDS = "active-account-home-local-ids" // new cache entry for active_account for a more robust version for browser
```
Comment (tnorling) [inline lib/msal-common/src/utils/Constants.ts]:
```suggestion
    ACTIVE_ACCOUNT_FILTERS = "active-account-filters" // new cache entry for active_account for a more robust version for browser
```

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 16]
```diff
@@ -400,26 +400,48 @@ export class BrowserCacheManager extends CacheManager {
...
+        if (!activeAccountValueHomeLocalIds) { 
+            // if new active account cache type isn't found, it's an old version, so look for that instead
+            const activeAccountKeyLocal = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
+            const activeAccountValueLocal = this.getItem(activeAccountKeyLocal);
+            if(!activeAccountValueLocal) {
+                return null;
+            }
+            const activeAccount = this.getAccountInfoByFilter({localAccountId: activeAccountValueLocal})[0] || null;
+            if(activeAccount) {
+                this.setActiveAccount(activeAccount); // update old active account cache type to new type
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: Can we also remove the old cache schema here?

Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Jason suggested not to, in case we roll back

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 17]
```diff
@@ -400,26 +400,48 @@ export class BrowserCacheManager extends CacheManager {
      * Gets the active account
      */
     getActiveAccount(): AccountInfo | null {
-        const activeAccountIdKey = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
-        const activeAccountId = this.browserStorage.getItem(activeAccountIdKey);
-        if (!activeAccountId) {
+        const activeAccountKeyHomeLocalIds = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT_HOME_LOCAL_IDS);
+        const activeAccountValueHomeLocalIds = this.getItem(activeAccountKeyHomeLocalIds);
+        if (!activeAccountValueHomeLocalIds) {
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]: Can we add some `Trace` level logs in this function to help us debug what's going on?

File: lib/msal-common/src/utils/Constants.ts [hunk 18]
```diff
@@ -81,7 +81,8 @@ export enum PersistentCacheKeys {
     ADAL_ID_TOKEN = "adal.idtoken",
     ERROR = "error",
     ERROR_DESC = "error.description",
-    ACTIVE_ACCOUNT = "active-account"
+    ACTIVE_ACCOUNT = "active-account",
```
Comment (tnorling) [inline lib/msal-common/src/utils/Constants.ts]:
```suggestion
    ACTIVE_ACCOUNT = "active-account", // Legacy active-account cache key, use new key instead
```

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 16 above)
Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: If we want to properly support rollback we need the `setActiveAccount` function to set both cache keys, otherwise they will get out of sync. I'd prefer to fully migrate and tell customers rolling back that they need to reset their active account, given we only commit to not erroring in rollback scenarios but do not make promises that we will fully support backward compat. @jasonnutter

Comment (jasonnutter) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Right, I think we should continue to set both (until v3).

File: lib/msal-common/src/account/AccountInfo.ts (hunk 14 above)
Comment (shylasummers) [reply lib/msal-common/src/account/AccountInfo.ts]: Fixed

File: lib/msal-common/src/utils/Constants.ts (hunk 15 above)
Comment (shylasummers) [reply lib/msal-common/src/utils/Constants.ts]: Fixed

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 17 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Fixed

File: lib/msal-common/src/utils/Constants.ts (hunk 18 above)
Comment (shylasummers) [reply lib/msal-common/src/utils/Constants.ts]: Fixed

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 16 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: I think Thomas is saying that we should not set the old schema and remove it when applicable in get, while Jason is saying that we should set the old schema and not remove it in get. It's an easy change either way, but I would like to choose one so this PR can make it into the release later today. @tnorling @jasonnutter

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: I'm fine with setting both in the setter and not removing in the getter for now.

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 19]
```diff
@@ -400,26 +400,52 @@ export class BrowserCacheManager extends CacheManager {
...
+            if(activeAccount) {
+                this.logger.trace("Old active account cache type found");
+                return activeAccount;
+            }
             return null;
         }
-        return this.getAccountInfoByFilter({localAccountId: activeAccountId})[0] || null;
+        const activeAccountValueObj = this.validateAndParseJson(activeAccountValueFilters) as AccountInfo;
+        if(activeAccountValueObj) {
+            this.logger.trace("New active account cache type found");
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]:
```suggestion
            this.logger.trace("Active account cache filters found");
```

File: lib/msal-browser/src/cache/BrowserCacheManager.ts [hunk 20]
```diff
@@ -400,26 +400,52 @@ export class BrowserCacheManager extends CacheManager {
...
+            this.logger.trace("No new active account cache type found, looking for old version");
+            const activeAccountKeyLocal = this.generateCacheKey(PersistentCacheKeys.ACTIVE_ACCOUNT);
+            const activeAccountValueLocal = this.getItem(activeAccountKeyLocal);
+            if(!activeAccountValueLocal) {
+                this.logger.trace("No active account found");
+                return null;
+            }
+            const activeAccount = this.getAccountInfoByFilter({localAccountId: activeAccountValueLocal})[0] || null;
+            if(activeAccount) {
+                this.logger.trace("Old active account cache type found");
```
Comment (tnorling) [inline lib/msal-browser/src/cache/BrowserCacheManager.ts]:
```suggestion
                this.logger.trace("Legacy active account cache schema found.");
```

Comment (tnorling) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: I thought we were creating a new cache value with the new schema here. Was that removed?

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 16 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Sounds good, fixed!

File: lib/msal-common/src/account/AccountInfo.ts (hunk 14 above)
Comment (tnorling) [reply lib/msal-common/src/account/AccountInfo.ts]: Don't see these changes, have they been pushed?

Comment (shylasummers) [reply lib/msal-common/src/account/AccountInfo.ts]: You're right, I missed this one, will push soon.

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 19 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: Fixed!

File: lib/msal-browser/src/cache/BrowserCacheManager.ts (hunk 20 above)
Comment (shylasummers) [reply lib/msal-browser/src/cache/BrowserCacheManager.ts]: You're right, just changed that

File: lib/msal-common/src/account/AccountInfo.ts (hunk 14 above)
Comment (shylasummers) [reply lib/msal-common/src/account/AccountInfo.ts]: Pushed

**Review by tnorling — APPROVED** [review]
Looks good! Thanks for promptly addressing feedback!
